#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2034

confirm(){
    while true
    do
        read -r -p "Ban muon cai dat ClamAV ? (y/n) " prompt_clamav
        echo
        if [[ "${prompt_clamav}" =~ ^([yY])$ || "${prompt_clamav}" =~ ^([nN])$ ]]; then
            break
        else
            printf "%s\n"  "${RED}Gia tri khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done
}

install(){
    if [ -f "/etc/clamd.d/scan.conf" ]; then
        printf "%s\n" "${RED}ClamAV da duoc cai dat. Ban khong can cai dat lai.${NC}"
    else
        if [[ ${OS_VER} -eq 8 ]]; then
            dnf install clamav-server clamav-update clamav-filesystem clamav clamav-scanner-systemd clamav-devel clamav-lib clamav-server-systemd -y
        else
            yum -y install clamav-server clamav-update clamav-filesystem clamav clamav-scanner-systemd clamav-devel clamav-lib clamav-server-systemd
        fi

        setsebool -P antivirus_can_scan_system 1
        setsebool -P clamd_use_jit 1
        sed -i -e "s/^Example/#Example/" /etc/clamd.d/scan.conf
        sed -i -e "s/#LocalSocket /LocalSocket /" /etc/clamd.d/scan.conf
        sed -i -e "s/^Example/#Example/" /etc/freshclam.conf
        {
            echo "DatabaseCustomURL http://cdn.malware.expert/malware.expert.ndb"
            echo "DatabaseCustomURL http://cdn.malware.expert/malware.expert.hdb"
            echo "DatabaseCustomURL http://cdn.malware.expert/malware.expert.ldb"
            echo "DatabaseCustomURL http://cdn.malware.expert/malware.expert.fp"
        } >> /etc/freshclam.conf
        clear
        printf "%s\n" "${GREEN}Cai dat ClamAV thanh cong.${NC}"
        echo ""
    fi
}

prompt_clamav=""
confirm
if [[ "${prompt_clamav}" =~ ^([yY])$ ]];then
    install
else
    clear
    printf "%s\n" "${GREEN}Ban da huy cai dat ClamAV.${NC}"
fi

menu_security