#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

select_remote(){
    echo "Chon Remote: "
    selects=$(rclone listremotes)
    for entry in ${selects}; do
        select=${entry//:}
        remotes+=(${select})
    done

    PS3="Nhap lua chon cua ban [0 = Thoat]: "
    select remote in "${remotes[@]}"
    do
        remote=${remote}
        break
    done

    if [[ -z "${remote}" || ${remote} != ^[_a-zA-Z][_a-zA-Z0-9]*$ ]]; then
        ALERT=$(printf "${RED}Remote ban chon khong chinh xac.${NC}\n")
    fi
}

set_var(){
	db_name=$(grep "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

backup(){
	if [[ ! -d "/home/backup/${DATE}/${domain}" ]]; then
		mkdir -p /home/backup/${DATE}/${domain}
	fi
	rm -rf /home/backup/${DATE}/${domain}/*
	cd_dir /home/backup/${DATE}/${domain}
	mysqldump -uadmin -p${mysql_pwd} ${db_name} > ${db_name}.sql

	cd_dir /home/${user}/${domain}
	tar -cpzvf /home/backup/"${DATE}"/"${domain}"/${domain}.tar.gz ${public}
}

_run(){
	if [[ -z "${ALERT}" ]]; then
		set_var

		for users in /home/*; do
			if [[ -d "${users}" ]]; then
				user=${users##*/}
				for domains in /home/${user}/*; do
					if [[ -d "${domains}" ]]; then
						domain=${domains##*/}
						for publics in /home/${user}/${domain}/public_html; do
							if [[ -d "${publics}" ]]; then
								public=${publics##*/}
								set_var
								backup
							fi
						done
					fi
				done
			fi
		done

		rclone copy /home/backup ${remote}:${IPADDRESS} >> /var/log/rclone.log 2>&1
		rm -rf /home/backup/*
		clear
		printf "${GREEN}Sao luu du lieu thanh cong.${NC}\n"
	else
		printf "${ALERT}\n"
	fi
}

_run
menu_ggdrive