#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

input(){
    while true
    do
        echo "Username khong chua ky tu dac biet va dai 5 ky tu tro len."
        read -r -p "Nhap vao ten ket noi muon tao (Viet lien, khong dau) [0 = Thoat]: " remote_name
        echo
        if validate_user "${remote_name}" || [ "${remote_name}" == "0" ]; then
            break
        else
            printf "%s\n" "${RED}Ten ket noi khong dung dinh dan. Vui long nhap lai.${NC}"
        fi
    done
}

config_rclone(){
    rclone config create "${remote_name}" drive config_is_local false scope drive use_trash false
}

_run(){
    input

    if [ "${remote_name}" == "0" ]; then
        printf "%s\n" "${RED}Huy hanh dong.${NC}"
    else
        config_rclone
    fi
}

remote_name=""

_run
menu_ggdrive