#!/bin/bash

input(){
	read -r -p "Nhap vao ten ket noi muon tao (Viet lien, khong dau): " remote_name
}

validate_input(){
	if [[ -z "${remote_name}" ]]; then
		ALERT=$(printf "${RED}Ban chua nhap ten ket noi.${NC}}\n")
	fi

	if ! [[ ${remote_name} =~ ^[_a-zA-Z][_a-zA-Z0-9]*$ ]]; then
		ALERT=$(printf "${RED}Ten ket noi khong dung dinh dang.${NC}}\n")
	fi
}

config_rclone(){
	rclone config create "${remote_name}" drive config_is_local false scope drive use_trash false
}

run(){
	input
	validate_input

	if [[ -z "${ALERT}" ]]; then
		config_rclone
	else
		printf "${ALERT}\n"
	fi
}

run
menu_ggdrive