#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
source /var/hostvn/ipaddress
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

confirm_destroy(){
    while true
    do
        read -r -p "Ban muon xoa backup ? (y/n) " promt_destroy
        echo
        if [[ "${promt_destroy}" =~ ^([yY])$ || "${promt_destroy}" =~ ^([nN])$ ]]; then
            break
        else
            printf "%s\n"  "${RED}Gia tri khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done
}

select_backup(){
    echo "Chon ngay ban muon xoa: "
    selects=$(rclone lsf "${remote}":"${IPADDRESS}")
    for entry in ${selects}; do
        select=${entry///}
        dates+=("${select}")
    done
    PS3="Nhap lua chon cua ban [0 = Thoat]: "
    select date in "${dates[@]}"
    do
        date=${date}
        break
    done
}

choose_domain(){
    echo "Chon ten mien ban muon xoa: "
    selects=$(rclone lsf "${remote}":"${IPADDRESS}"/"${date}")
    for entry in ${selects}; do
        select=${entry///}
        domains+=("${select}")
    done
    PS3="Nhap lua chon cua ban [0 = Thoat]: "
    select domain in "${domains[@]}"
    do
        domain=${domain}
        break
    done
}

_run(){
    select_backup
    if [ -z "${date}" ]; then
        clear
        printf "%s\n" "${GREEN}Ban da huy xoa backup.${NC}"
    else
        choose_domain

        if [ -z "${domain}" ]; then
            clear
            printf "%s\n" "${GREEN}Ban da huy xoa backup.${NC}"
        else
            rclone delete "${remote}":/"${IPADDRESS}"/"${date}"/"${domain}" --rmdirs > /dev/null  2>&1
            rclone cleanup "${remote}":"${IPADDRESS}" > /dev/null  2>&1
            rm -rf /home/backup/"${date}"/"${domain}"
            clear
            printf "%s\n" "${GREEN}Xoa backup thanh cong.${NC}"
        fi
    fi
}

if [ -f "/root/.config/rclone/rclone.conf" ]; then
    date=""
    remote=""
    domain=""
    promt_destroy="n"
    confirm_destroy
    if [[ "${promt_destroy}" =~ ^([yY])$ ]]; then
        if [[ $(ls -A "${USER_DIR}") ]]; then
            select_remote
            if [ -z "${remote}" ]; then
                clear
                printf "%s\n" "${GREEN}Ban da huy xoa backup.${NC}"
            else
                _run
            fi
        else
            printf "%s\n" "${RED}Khong co ten mien nao tren VPS.${NC}"
        fi
    else
        clear
        printf "%s\n" "${GREEN}Ban da huy xoa backup.${NC}"
    fi
else
    printf "%s\n" "${RED}Ban chua cau hinh ket noi voi Google Drive.${NC}"
fi
menu_ggdrive