#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

confirm_destroy(){
	read -r -p "Ban muon xoa backup ? (y\n) " promt_destroy
}

_run(){
	confirm_destroy
	if [[ "${promt_destroy}" =~ ^([yY])$ ]]; then
		select_remote
		if [[ -z "${ALERT}" ]]; then
			rclone config delete ${remote}
			printf "${GREEN}Xoa remote thanh cong.${NC}\n"
		else
			printf "${ALERT}\n"
		fi
	fi
}

_run
menu_ggdrive