#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

confirm_destroy(){
	read -r -p "Ban muon xoa backup ? (y\n) " promt_destroy
}

select_backup(){
	echo "Chon ngay ban muon khoi phuc: "
    selects=$(rclone lsf "${remote}":"${IPADDRESS}")
    for entry in ${selects}; do
    	select=${entry///}
        dates+=("${select}")
    done
    PS3="Nhap lua chon cua ban [0 = Thoat]: "
    select date in "${dates[@]}"
    do
        date=${date}
        break
    done

    if ! valid_date "${date}"; then
    	ALERT=$(printf "${RED}Ngay ban chon khong dung dinh dang.${NC}\n")
    else
    	choose_domain
    fi
}

choose_domain(){
	echo "Chon ten mien ban muon khoi phuc: "
    selects=$(rclone lsf "${remote}":"${IPADDRESS}"/"${date}")
    for entry in ${selects}; do
    	select=${entry///}
        domains+=("${select}")
    done
    PS3="Nhap lua chon cua ban [0 = Thoat]: "
    select domain in "${domains[@]}"
    do
        domain=${domain}
        break
    done

    if ! validate_domain "${domain}"; then
      ALERT=$(printf "${RED}Ten mien khong dung dinh dang.${NC}\n")
    fi
}

_run(){
	if [[ "${promt_destroy}" =~ ^([yY])$ ]]; then
    select_remote
    select_backup

		if [[ -z "${ALERT}" ]]; then
			rclone delete "${remote}":/"${IPADDRESS}"/"${date}"/"${domain}" --rmdirs > /dev/null  2>&1
			rclone cleanup "${remote}":"${IPADDRESS}" > /dev/null  2>&1
			rm -rf /home/backup/"${date}"/"${domain}"
			clear
			printf "${GREEN}Xoa backup thanh cong.${NC}\n"
		else
		  clear
			printf "${ALERT}\n"
		fi
	else
	  clear
		printf "${GREEN}Ban da huy xoa backup.${NC}\n"
	fi
}

_run
menu_ggdrive