#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

confirm_restore(){
	read -r -p "Ban muon khoi phuc du lieu ? (y\n) " promt_restore
}

set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
	username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
	db_name=$(grep -w "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

select_backup(){
	echo "Chon ngay ban muon khoi phuc: "
	  dates=()
    selects=$(rclone lsf "${remote}":"${IPADDRESS}")
    for entry in ${selects}; do
    	select=${entry///}
        dates+=("${select}")
    done
    PS3="Nhap lua chon cua ban [0 = Thoat]: "
    select date in "${dates[@]}"
    do
        date=${date}
        break
    done

    if ! valid_date "${date}"; then
        ALERT=$(printf "${RED}Gia tri ban nhap khong dung.${NC}\n")
    fi
}

choose_domain(){
	echo "Chon ten mien ban muon khoi phuc: "
    selects=$(rclone lsf "${remote}":"${IPADDRESS}"/"${date}")
    for entry in ${selects}; do
    	select=${entry///}
        domains+=("${select}")
    done
    PS3="Nhap lua chon cua ban [0 = Thoat]: "
    select domain in "${domains[@]}"
    do
        domain=${domain}
        break
    done

    if ! validate_domain "${domain}"; then
      ALERT=$(printf "${RED}Ten mien khong dung dinh dang.${NC}\n")
    fi
}

download_backup(){
  if [ -d "/home/backup/${date}/${domain}" ]; then
      rm -rf /home/backup/"${date}"/"${domain}"
  else
    mkdir -p /home/backup/"${date}"/"${domain}"
  fi
	rclone copy "${remote}:/${IPADDRESS}/${date}/${domain}" /home/backup/"${date}"
}

restore_source(){
	if [[ ! -d "/home/${username}/${domain}/public_html" ]]; then
		mkdir -p /home/"${username}"/"${domain}"/public_html
	fi
	rm -rf /home/"${username}"/"${domain}"/public_html/*
	tar xvzf /home/backup/"${date}"/"${domain}"/"${domain}".tar.gz -C /home/"${username}"/"${domain}"/
	chown -R "${username}":"${username}" /home/"${username}"
}

restore_db(){
	cd_dir /home/backup/"${date}"/"${domain}"
	mysql -uadmin -p"${mysql_pwd}" "${db_name}" < "${db_name}".sql
}

_run(){
	confirm_restore
	if [[ "${promt_restore}" =~ ^([yY])$ ]]; then
	    ALERT=""
		domain=""
		select_remote
		select_backup

		if [[ -n "${domain}" ]]; then
			set_var
			if ! if_domain_exists ${domain}; then
				ALERT=$(printf "${RED}Website khong ton tai tren VPS.${NC}\n")
			fi

			if ! if_db_exists "${db_name}"; then
				ALERT=$(printf "${RED}Database khong ton tai.${NC}\n")
			fi
		fi

		if [[ -z "${ALERT}" ]]; then
			download_backup
			restore_source
			empty_db
			restore_db
			rm -rf /home/backup/"${date}"/"${domain}"
			clear
			printf "${GREEN}Khoi phuc du lieu thanh cong.${NC}\n"
		else
			clear
			printf "${ALERT}\n"
		fi
	else
		clear
		printf "${RED}Ban da chon huy khoi phuc du lieu.${NC}\n"
	fi
}

_run
menu_ggdrive