#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

select_date(){
	echo "Chon ngay: "
    selects=$(rclone lsf "${remote}":"${IPADDRESS}")
    dates=()
    for entry in ${selects}; do
    	select=${entry///}
      dates+=("${select}")
    done
    PS3="Nhap lua chon cua ban [0 = Thoat]: "
    select date in "${dates[@]}"
    do
        date=${date}
        break
    done

    if ! [[ ${date} =~ ^[0-9]{2}-[0-9]{2}-[0-9]{4}$ ]]; then
    	ALERT=$(printf "${RED}Gia tri ban nhap khong dung.${NC}\n")
    fi
}

_run(){
    ALERT=""
	select_remote
	select_date

	if [[ -z "${ALERT}" ]]; then
		echo ""
		echo "Dang load danh sach. Vui long doi..."
		echo ""
		rclone lsf "${remote}":/"${IPADDRESS}"/"${date}"
		echo ""
	else
		printf "${ALERT}\n"
	fi
}

_run
menu_ggdrive