#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

select_date(){
    echo "Chon ngay: "
    selects=$(rclone lsf "${remote}":"${IPADDRESS}")
    dates=()
    for entry in ${selects}; do
        select=${entry///}
        dates+=("${select}")
    done
    PS3="Nhap lua chon cua ban [0 = Thoat]: "
    select date in "${dates[@]}"
    do
        date=${date}
        break
    done
}

_run(){
    select_date

    if [ -z "${date}" ]; then
        clear
        printf "%s\n" "${RED}Ban da chon huy thao tac.${NC}"
    else
        echo ""
        echo "Dang load danh sach. Vui long doi..."
        echo ""
        rclone lsf "${remote}":/"${IPADDRESS}"/"${date}"
        echo ""
    fi
}

if [ -f "/root/.config/rclone/rclone.conf" ]; then
    remote=""
    date=""

    select_remote
    if [ -z "${remote}" ]; then
        clear
        printf "%s\n" "${RED}Ban da chon huy thao tac.${NC}"
    else
        _run
    fi
else
    printf "%s\n" "${RED}Ban chua cau hinh ket noi voi Google Drive.${NC}"
fi
menu_ggdrive