#!/bin/bash

printf "${GREEN}-----------------${NC}\n"
printf "${GREEN}Thay đoi port SSH${NC}\n"
printf "${GREEN}-----------------${NC}\n"

set_var(){
	current_port=$(grep "admin_port" "${FILE_INFO}" | cut -f2 -d'=')
	csf_port=$(grep "csf_port" "${FILE_INFO}" | cut -f2 -d'=')
	ftp_port=$(grep "ftp_port" "${FILE_INFO}" | cut -f2 -d'=')
	ssh_port=$(grep "Port " /etc/ssh/sshd_config | cut -f2 -d" ")
}

input(){
	read -r -p "Nhap vao port ban muon đoi: " new_port
}

check_port(){
	set_var
	if [ -z "${new_port}" ]; then
	    ALERT=$(printf "${RED}Ban chua nhap Port.${NC}\n")
	fi

	if [[ ! ${new_port} =~ ^-?[0-9]+$ ]]; then
	    ALERT=$(printf "${RED}Port khong dung dinh dang, vui long nhap lai.${NC}\n")
	fi

	if [[ "${new_port}" == "${current_port}" ]]; then
	    ALERT=$(printf "${RED}Port ban nhap trung vui Port Admin hien tai.${NC}\n")
	fi

	if [[ "${new_port}" == "${ssh_port}" || "${new_port}" == "${csf_port}" || "${new_port}" == "${ftp_port}" ]]; then
	    ALERT=$(printf "${RED}Port ban chon da duoc su dung. Vui long chon port khac.${NC}\n")
	fi
}

change_port(){
	echo "Dang tien hanh thay đoi port SSH..."
   	echo ""
   	sleep 1
    sed -i 's/,'${current_port}'/,'${new_port}'/g' /etc/csf/csf.conf
    sed -i 's/'${current_port}'/'${new_port}'/g' /etc/nginx/web_apps.conf
    sed -i '/admin_port=/d' "${FILE_INFO}"
    echo "admin_port=${new_port}" >> "${FILE_INFO}"
    csf -x
    csf -e
    systemctl restart csf
    systemctl restart lfd
    clear
    printf "${GREEN}Da thay đoi Port Admin sang ${new_port} thanh cong.${NC}\n"
}

_run(){
	input
	check_port
	if [ -z "${ALERT}" ]; then
		change_port
	else
		clear
		printf "${ALERT}\n"
	fi
}

_run
echo ""
menu_ssh