#!/bin/bash

#################################################
# Auto Install & Optimize LEMP Stack on CentOS 7#
# Version: 1.0                                  #
# Author: Sanvv - HOSTVN Technical              #
#                                               #
# Please don't remove copyright. Thank!         #
#################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

update(){
	cd_dir "${DEFAULT_DIR_TOOL}"/opcache
	rm -rf ./*
	wget -q https://raw.githubusercontent.com/amnuts/opcache-gui/master/index.php -O  "${DEFAULT_DIR_TOOL}"/opcache/index.php &> /dev/null
	chown -R nginx:nginx "${DEFAULT_DIR_TOOL}"/opcache
	clear
	printf "${GREEN}Update Opcache Dashboard thanh cong.${NC}\n"
}

update
menu_admin