#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    phpmyadmin_v=$(curl -s "${UPDATE_LINK}"/version | grep "phpmyadmin_version=" | cut -f2 -d'=')
    php_v=$(rpm -qa php-fpm | cut -f3 -d'-')

    if [ "${php_v}" -lt 7 ]; then
        phpmyadmin_v="4.9.5"
    fi
}

check_dir(){
    if [ -d "${DEFAULT_DIR_TOOL}/phpmyadmin" ]; then
        rm -rf "${DEFAULT_DIR_TOOL}"/phpmyadmin
        rm -rf "${DEFAULT_DIR_TOOL}"/phpmyadmin
    fi
}

update(){
    cd_dir "${DEFAULT_DIR_TOOL}"
    rm -rf phpmyadmin
    wget -O "${DEFAULT_DIR_TOOL}"/phpmyadmin.zip  https://files.phpmyadmin.net/phpMyAdmin/"${phpmyadmin_v}"/phpMyAdmin-"${phpmyadmin_v}"-english.zip
    unzip phpmyadmin.zip
    rm -rf phpmyadmin.zip
    mv phpMyAdmin-"${phpmyadmin_v}"-english phpmyadmin
}

config_phpmyadmin(){
    blowfish_secret=$(date +%s%N | sha256sum | base64 | head -c 82)
    rm -rf "${DEFAULT_DIR_TOOL}"/phpmyadmin/setup
    mkdir -p "${DEFAULT_DIR_TOOL}"/phpmyadmin/tmp

    if [ "${phpmyadmin_v}" != "4.9.5" ]; then
        declare="declare(strict_types=1);"
    fi

    cat > "${DEFAULT_DIR_TOOL}/phpmyadmin/config.inc.php" <<EOCONFIGINC
<?php
${declare}
\$cfg['blowfish_secret'] = '${blowfish_secret}';
\$i = 0;
\$i++;
\$cfg['Servers'][\$i]['auth_type'] = 'http';
\$cfg['Servers'][\$i]['host'] = 'localhost';
\$cfg['Servers'][\$i]['connect_type'] = 'tcp';
\$cfg['Servers'][\$i]['compress'] = false;
\$cfg['Servers'][\$i]['AllowNoPassword'] = false;
\$cfg['UploadDir'] = '';
\$cfg['SaveDir'] = '';
\$cfg['PmaNoRelation_DisableWarning'] = true;
\$cfg['VersionCheck'] = false;
\$cfg['TempDir'] = '${DEFAULT_DIR_TOOL}/phpmyadmin/tmp';
\$cfg['CaptchaLoginPublicKey'] = '';
\$cfg['CaptchaLoginPrivateKey'] = '';
\$cfg['ExecTimeLimit'] = 600;
EOCONFIGINC

    chown -R nginx:nginx "${DEFAULT_DIR_TOOL}"/phpmyadmin
    chown -R nginx:nginx "${DEFAULT_DIR_TOOL}"/phpmyadmin
}

run(){
    set_var

    check_dir
    update
    config_phpmyadmin
    restart_service
    clear
    printf "%s\n" "${GREEN}Update phpMyAdmin thanh cong.${NC}"
}

run
menu_admin