#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
	phpsysinfo_v=$(curl -s "${UPDATE_LINK}"/version | grep "phpsysinfo_version=" | cut -f2 -d'=')
}

check_dir(){
	if [ -d "${DEFAULT_DIR_TOOL}/serverinfo" ]; then
		rm -rf "${DEFAULT_DIR_TOOL}"/serverinfo
	fi
}

update(){
	cd_dir "${DEFAULT_DIR_TOOL}"
	wget https://github.com/phpsysinfo/phpsysinfo/archive/v"${phpsysinfo_v}".zip &> /dev/null
	unzip v"${phpsysinfo_v}".zip &> /dev/null
	mv phpsysinfo-"${phpsysinfo_v}" serverinfo
	rm -rf v"${phpsysinfo_v}".zip
	mv serverinfo/phpsysinfo.ini.new serverinfo/phpsysinfo.ini
	chown -R nginx:nginx serverinfo
	clear
	printf "${GREEN}Update phpSysInfo thanh cong.${NC}\n"
}

run(){
	set_var
	check_dir
	update
}

run
menu_admin