#!/bin/bash

#################################################
# Auto Install & Optimize LEMP Stack on CentOS 7#
# Version: 1.0                                  #
# Author: Sanvv - HOSTVN Technical              #
#                                               #
# Please don't remove copyright. Thank!         #
#################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

update(){
	cd_dir /usr/share/nginx/html
	rm -rf ./redis
	git clone https://github.com/ErikDubbelboer/phpRedisAdmin.git
    mv phpRedisAdmin redis
    cd_dir /usr/share/nginx/html/redis
    git clone https://github.com/nrk/predis.git vendor
    cd .. && chown -R nginx:nginx redis
	clear
	printf "${GREEN}Update Redis Dashboard thanh cong.${NC}\n"
}

update
menu_admin