#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# Set link
SCRIPT_LINK="https://scripts.hostvn.net"

# VPS Info

OS_VER=$(rpm -E %centos)
RAM_TOTAL=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
LOW_RAM='524288'

# Control Panel path
CPANEL="/usr/local/cpanel/cpanel"
DIRECTADMIN="/usr/local/directadmin/custombuild/build"
PLESK="/usr/local/psa/version"
WEBMIN="/etc/init.d/webmin"
SENTORA="/root/passwords.txt"
HOCVPS="/etc/hocvps/scripts.conf"
VPSSIM="/home/vpssim.conf"
EEV3="/usr/local/bin/ee"
WORDOPS="/usr/local/bin/wo"
KUSANAGI="/home/kusanagi"
CWP="/usr/local/cwpsrv"
VESTA="/usr/local/vesta/"
EEV4="/opt/easyengine"
LARVPS="/etc/larvps/.info.conf"
TINO="/opt/tinopanel"

# Set Lang
ROOT_ERR="Ban can chay script voi user root. Chay lenh \"sudo su\" de co quyen root!"
CANCEL_INSTALL="Huy cai dat..."
OS_WRONG="Script chi hoat dong tren \"CentOS 7\" va \"CentOS 8\"!"
RAM_NOT_ENOUGH="Canh bao: Dung luong RAM qua thap de cai Script. (it nhat 512MB)"
OTHER_CP_EXISTS="May chu cua ban da cai dat Control Panel khac. Vui long rebuild de cai dat Script."
HOSTVN_EXISTS="May chu cua ban da cai dat HOSTVN Script. Vui long rebuild neu muon cai dat lai."

# Set Color
RED='\033[0;31m'
NC='\033[0m'

welcome(){
    clear
    printf "========================================================\n"
    echo   "                   HOSTVN.VN Scripts                     "
    echo   "     Auto Install & Optimize LEMP Stack on CentOS 7, 8    "
    printf " Neu can ho tro vui long lien he %s\n" "kythuat@hostvn.net"
    printf "========================================================\n"
    echo ""
    echo "Chuan bi cai dat..."
    sleep 3
}

###################
#Check conditions #
###################

# Check if user not root
check_root(){
    if [[ "$(id -u)" != "0" ]]; then
        printf "${RED}%s${NC}\n" "${ROOT_ERR}"
        printf "${RED}%s${NC}\n" "${CANCEL_INSTALL}"
        exit
    fi
}

# Check if not enough ram
check_low_ram(){
    if [[ ${RAM_TOTAL} -lt ${LOW_RAM} ]]; then
        printf "${RED}%s${NC}\n" "${RAM_NOT_ENOUGH}"
        printf "${RED}%s${NC}\n" "${CANCEL_INSTALL}"
        exit
    fi
}

# Check if other Control Panel has installed before
check_control_panel(){
    if [[ -f "${CPANEL}" || -f "${DIRECTADMIN}" || -f "${PLESK}" || -f "${WEBMIN}" || -f "${SENTORA}" || -f "${HOCVPS}" || -f "${LARVPS}" ]]; then
        printf "${RED}%s${NC}\n" "${OTHER_CP_EXISTS}"
        printf "${RED}%s${NC}\n" "${CANCEL_INSTALL}"
        exit
    fi

    if [[ -f "${VPSSIM}" || -f "${WORDOPS}" || -f "${EEV3}" || -d "${EEV4}" || -d "${VESTA}" || -d "${CWP}" || -d "${KUSANAGI}" || -d "${TINO}" ]]; then
        printf "${RED}%s${NC}\n" "${OTHER_CP_EXISTS}"
        printf "${RED}%s${NC}\n" "${CANCEL_INSTALL}"
        exit
    fi

    if [[ -f "/etc/hostvn.lock" ]]; then
        printf "${RED}%s${NC}\n" "${HOSTVN_EXISTS}"
        printf "${RED}%s${NC}\n" "${CANCEL_INSTALL}"
        exit
    fi
}

check_before_install(){
    echo ""
    check_root
    check_low_ram
    check_control_panel
}

###################
# Prepare Install #
###################

# Remove unnecessary services
remove_old_ervice(){
    yum -y remove mysql* php* httpd* sendmail* postfix* rsyslog* nginx*
    yum clean all
}

# Install requirement service
install_repo(){
    if [[ "${OS_VER}" -eq 8 ]]; then
        yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y
        yum -y install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
        yum -y update
        yum -y install hostname libsepol boost-program-options
    elif [ "${OS_VER}" -eq 7 ]; then
        yum -y install epel-release ntpdate
        yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y
        yum -y update
    else
        printf "${RED}${OS_WRONG}${NC}\n"
        sleep 2
        exit
    fi
}

install_requirement(){
    yum -y install gawk bc wget tar gcc gcc-c++ flex bison make bind bind-libs bind-utils yum-utils dos2unix openssl openssl-devel perl quota libaio \
          libcom_err-devel libcurl-devel gd jpegoptim zlib-devel zip unzip libcap-devel cronie bzip2 cyrus-sasl-devel perl-ExtUtils-Embed logrotate \
          autoconf automake libtool which patch mailx bzip2-devel lsof glibc-headers kernel-devel expat-devel nano htop git syslog-ng syslog-ng-libdbi \
          psmisc net-tools systemd-devel libdb-devel perl-DBI perl-Perl4-CoreLibs perl-libwww-perl pngquant xfsprogs rsyslog crontabs file kernel-headers \
          perl-LWP-Protocol-https perl-GDGraph perl-IO-Socket-SSL.noarch perl-Net-SSLeay perl-Net-LibIDN perl-IO-Socket-INET6 perl-Socket6 libpng-devel
}

create_swap(){
    swap="$(swapon -s)"
    if [[ -z "${swap}" && ${RAM_TOTAL} -le 2099152 ]]; then
        fallocate -l 1G /swapfile
        chmod 600 /swapfile
        mkswap /swapfile
        swapon /swapfile
        echo "/swapfile   none    swap    sw    0   0" >> /etc/fstab
    fi
}

#########################
#Dowload primary Script #
#########################
dowload_script(){
    curl -sO ${SCRIPT_LINK}/hostvn && dos2unix hostvn &> /dev/null && chmod +x hostvn && sh hostvn
}

welcome
check_before_install
remove_old_ervice
install_repo
install_requirement
create_swap
dowload_script