#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s================================%s\n" "${GREEN}" "${NC}"
printf "  %sKiem tra thong tin tai khoan%s\n  " "${GREEN}" "${NC}"
printf "%s=================================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Thong tin dang nhap Admin Tool%s\n" "${GREEN}" "${NC}"
    printf "%s2. Thong tin dang nhap phpMyAdmin%s\n" "${GREEN}" "${NC}"
    printf "%s3. Kiem tra SSH Port%s\n" "${GREEN}" "${NC}"
    printf "%s4. Thong tin theo website%s\n" "${GREEN}" "${NC}"
    printf "%s ================================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; c_tool ;;
        2) clear; pma_info ;;
        3) clear; ssh_info ;;
        4) clear; user_info ;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done