#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s===========================%s\n" "${GREEN}" "${NC}"
printf "     %sQuan ly Admin Tool %s\n   " "${GREEN}" "${NC}"
printf "%s===========================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Cap nhat phpMyAdmin%s\n" "${GREEN}" "${NC}"
    printf "%s2. Cap nhat phpSysInfo%s\n" "${GREEN}" "${NC}"
    printf "%s3. Cap nhat Opcache Panel%s\n" "${GREEN}" "${NC}"
    printf "%s4. Cap nhat Memcached Admin%s\n" "${GREEN}" "${NC}"
    printf "%s5. Cap nhat Redis Admin%s\n" "${GREEN}" "${NC}"
    printf "%s6. Doi mat khau Admin Tool%s\n" "${GREEN}" "${NC}"
    printf "%s7. Doi port Admin Tool%s\n" "${GREEN}" "${NC}"
    printf "%s =========================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) update_phpmyadmin ;;
        2) update_phpsysinfo ;;
        3) update_opcache_panel ;;
        4) update_memcached_panel ;;
        5) update_redis_panel ;;
        6)
            admin_new_pwd=$(< /dev/urandom tr -dc A-Za-z0-9 | head -c16)
            htpasswd -b -c /usr/share/nginx/auth/.htpasswd admin "${admin_new_pwd}"
            sed -i '/admin_pwd=/d' "${FILE_INFO}"
            echo "admin_pwd=${admin_new_pwd}" >> "${FILE_INFO}"
            sed -i "s/UI_PASS/#UI_PASS/g" /etc/csf/csf.conf
            sed -i "/#UI_PASS/a UI_PASS = \"${admin_new_pwd}\"" /etc/csf/csf.conf
            sed -i '/#UI_PASS/d' /etc/csf/csf.conf
            csf -x
            csf -e
            clear
            printf "%s\n" "${GREEN}Doi mat khau Admin Tool thanh cong.${NC}"
            menu_admin
            ;;
        7) change_port_admin ;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done