#!/bin/bash

#################################################
# Auto Install & Optimize LEMP Stack on CentOS 7#
# Version: 1.0                                  #
# Author: Sanvv - HOSTVN Technical              #
#                                               #
# Please don't remove copyright. Thank!         #
#################################################

CHOICE=1

printf "${GREEN}===================${NC}\n"
printf "${GREEN}  Sao luu du lieu  ${NC}\n"
printf "${GREEN}===================${NC}\n"
echo ""

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Sao luu du lieu (Local)${NC}\n"
    printf "${GREEN}2. Khoi phuc du lieu (Local)${NC}\n"
    printf "${GREEN}3. Xoa ban sao luu (Local)${NC}\n"
    printf "${GREEN}4. Sao luu len Google Drive${NC}\n"
    printf "${GREEN}5. Thiet lap backup tu dong${NC}\n"
    printf "${GREEN} --------------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; select_backup;;
        2) clear; select_restore ;;
        3) clear; delete_backup ;;
        4) clear; menu_ggdrive ;;
        5) clear; menu_cronjob ;;
        0) clear; menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done