#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s=====================================%s\n" "${GREEN}" "${NC}"
printf "%s     Sao luu/Khoi phuc du lieu       %s\n" "${GREEN}" "${NC}"
printf "%s=====================================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Sao luu du lieu (Local)%s\n" "${GREEN}" "${NC}"
    printf "%s2. Khoi phuc du lieu (Local)%s\n" "${GREEN}" "${NC}"
    printf "%s3. Xoa ban sao luu (Local)%s\n" "${GREEN}" "${NC}"
    printf "%s4. Khoi phuc/Sao luu voi Google Drive%s\n" "${GREEN}" "${NC}"
    printf "%s5. Thiet lap backup tu dong%s\n" "${GREEN}" "${NC}"
    printf "%s ====================================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; select_backup;;
        2) clear; select_restore ;;
        3) clear; delete_backup ;;
        4) clear; menu_ggdrive ;;
        5) clear; menu_cronjob ;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done