#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "${GREEN}=============${NC}\n"
printf "${GREEN}Quan ly Cache${NC}\n"
printf "${GREEN}=============${NC}\n"
echo ""

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Memcached${NC}\n"
    printf "${GREEN}2. Redis${NC}\n"
    printf "${GREEN}3. Quan ly Opcache${NC}\n"
    printf "${GREEN}4. Xoa Cache${NC}\n"
    printf "${GREEN}5. Cai dat Memcached${NC}\n"
    printf "${GREEN}6. Cai dat Redis${NC}\n"
    printf "${GREEN} -----------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; memcached_c ;;
        2) clear; redis_c ;;
        3) clear; manage_opcache ;;
        4) clear; clear_cache ;;
        5) clear; inst_memcached ;;
        6) clear; inst_redis ;;
        0) clear; menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done