#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s====================%s\n" "${GREEN}" "${NC}"
printf "    %sQuan ly Cache%s   \n" "${GREEN}" "${NC}"
printf "%s====================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Memcached%s\n" "${GREEN}" "${NC}"
    printf "%s2. Redis%s\n" "${GREEN}" "${NC}"
    printf "%s3. Quan ly Opcache%s\n" "${GREEN}" "${NC}"
    printf "%s4. Xoa Cache%s\n" "${GREEN}" "${NC}"
    printf "%s5. Cai dat Memcached%s\n" "${GREEN}" "${NC}"
    printf "%s6. Cai dat Redis%s\n" "${GREEN}" "${NC}"
    printf "%s =================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; memcached_c ;;
        2) clear; redis_c ;;
        3) clear; manage_opcache ;;
        4) clear; clear_cache ;;
        5) clear; inst_memcached ;;
        6) clear; inst_redis ;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n"  "${GREEN}Lua chon cua ban khong chinh xac. Vui long chon lai.${RED}";;
    esac
done