#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154

CHOICE=1

printf "%s=====================================%s\n" "${GREEN}" "${NC}"
printf "%s         Quan ly CSF Firewall        %s\n" "${GREEN}" "${NC}"
printf "%s=====================================%s\n" "${GREEN}" "${NC}"
printf "%sCSF GUI:%s %s%s%s\n" "${GREEN}" "${NC}" "${RED}" "https://${IPADDRESS}:${csf_port}" "${NC}"
printf "%s======================================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Mo Port%s\n" "${GREEN}" "${NC}"
    printf "%s2. Kiem tra Block IP%s\n" "${GREEN}" "${NC}"
    printf "%s3. Block IP%s\n" "${GREEN}" "${NC}"
    printf "%s4. Go Block IP%s\n" "${GREEN}" "${NC}"
    printf "%s5. Go Block toan bo IP%s\n" "${GREEN}" "${NC}"
    printf "%s6. Allow IP%s\n" "${GREEN}" "${NC}"
    printf "%s7. Cap quyen truy cap CSF GUI%s\n" "${GREEN}" "${NC}"
    printf "%s8. Restart CSF%s\n" "${GREEN}" "${NC}"
    printf "%s9. Tat CSF%s\n" "${GREEN}" "${NC}"
    printf "%s10. Bat CSF%s\n" "${GREEN}" "${NC}"
    printf "%s ============================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; csf_open_port ;;
        2)
            read -r -p "Nhap vao IP muon kiem tra: " ip
            csf -g "${ip}"
            echo ""
            menu_csf
            ;;
        3)
            read -r -p "Nhap vao IP muon block: " ip
            csf -d "${ip}"
            csf -x
            csf -e
            systemctl restart csf
            systemctl restart lfd
            clear
            printf "%s\n" "${GREEN}Block IP thanh cong.${NC}"
            echo ""
            menu_csf
            ;;
        4)
            read -r -p "Nhap vao IP muon go block: " ip
            csf -dr "${ip}"
            csf -x
            csf -e
            systemctl restart csf
            systemctl restart lfd
            clear
            printf "%s\n" "${GREEN}Go Block IP thanh cong.${NC}"
            echo ""
            menu_csf
            ;;
        5)
            csf -tf
            csf -df
            csf -x
            csf -e
            systemctl restart csf
            systemctl restart lfd
            clear
            printf "%s\n" "${GREEN}Go Block toan bo IP thanh cong.${NC}"
            echo ""
            menu_csf
            ;;
        6)
            read -r -p "Nhap vao IP muon allow: " ip
            csf -a "${ip}"
            csf -x
            csf -e
            systemctl restart csf
            systemctl restart lfd
            clear
            printf "%s\n" "${GREEN}Allow IP thanh cong.${NC}"
            echo ""
            menu_csf
            ;;
        7)
            read -r -p "Nhap vao IP muon cap quyen truy cap CSF GUI: " ip
            cat >> "/etc/csf/ui/ui.allow" << EOcsfui

${ip}
EOcsfui
            csf -a "${ip}"
            csf -x
            csf -e
            systemctl restart csf
            systemctl restart lfd
            clear
            printf "%s\n" "${GREEN}Cap quyen truy cap CSF GUI thanh cong.${NC}"
            echo ""
            menu_csf
            ;;
        8)
            csf -x
            csf -e
            systemctl restart lfd
            clear
            printf "%s\n" "${GREEN}Khoi dong lai CSF thanh cong.${NC}"
            echo ""
            menu_csf
            ;;
        9)
            csf -x
            systemctl stop csf
            systemctl stop lfd
            systemctl disable csf
            systemctl disable lfd
            clear
            printf "%s\n" "${GREEN}Tat CSF thanh cong.${NC}"
            echo ""
            menu_csf
            ;;
        10)
            csf -e
            systemctl start csf
            systemctl start lfd
            systemctl enable csf
            systemctl enable lfd
            clear
            printf "%s\n" "${GREEN}Bat CSF thanh cong.${NC}"
            echo ""
            menu_csf
            ;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n"  "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done