#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154

CHOICE=1

printf "${GREEN}=============================${NC}\n"
printf "${GREEN}    Quan ly CSF Firewall     ${NC}\n"
printf "${GREEN}=============================${NC}\n"
printf "${GREEN}CSF GUI:${NC} ${RED}%s${NC}\n" "https://${IPADDRESS}:${csf_port}"
printf "${GREEN}-----------------------------${NC}\n"
echo ""

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Kiem tra Block IP${NC}\n"
    printf "${GREEN}2. Block IP${NC}\n"
    printf "${GREEN}3. Go Block IP${NC}\n"
    printf "${GREEN}4. Go Block toan bo IP${NC}\n"
    printf "${GREEN}5. Allow IP${NC}\n"
    printf "${GREEN}6. Cap quyen truy cap CSF GUI${NC}\n"
    printf "${GREEN}7. Restart CSF${NC}\n"
    printf "${GREEN}8. Tat CSF${NC}\n"
    printf "${GREEN}9. Bat CSF${NC}\n"
    printf "${GREEN} ----------------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1)
            read -r -p "Nhap vao IP muon kiem tra: " ip
            csf -g "${ip}"
            echo ""
            menu_csf
            ;;
        2)
            read -r -p "Nhap vao IP muon block: " ip
            csf -d "${ip}"
            clear
            printf "${GREEN}Block IP thanh cong.${NC}\n"
            echo ""
            menu_csf
            ;;
        3)
            read -r -p "Nhap vao IP muon go block: " ip
            csf -dr "${ip}"
            clear
            printf "${GREEN}Go Block IP thanh cong.${NC}\n"
            echo ""
            menu_csf
            ;;
        4)
            csf -tf
            csf -df
            systemctl restart lfd
            clear
            printf "${GREEN}Go Block toan bo IP thanh cong.${NC}\n"
            echo ""
            menu_csf
            ;;
        5)
            read -r -p "Nhap vao IP muon allow: " ip
            csf -a "${ip}"
            csf -x
            csf -e
            clear
            printf "${GREEN}Allow IP thanh cong.${NC}\n"
            echo ""
            menu_csf
            ;;
        6)
            read -r -p "Nhap vao IP muon cap quyen truy cap CSF GUI: " ip
            echo "${ip}" >>  /etc/csf/ui/ui.allow
            csf -x
            csf -e
            clear
            printf "${GREEN}Cap quyen truy cap CSF GUI thanh cong.${NC}\n"
            echo ""
            menu_csf
            ;;
        7)
            csf -x
            csf -e
            systemctl restart lfd
            clear
            printf "${GREEN}Khoi dong lai CSF thanh cong.${NC}\n"
            echo ""
            menu_csf
            ;;
        8)
            csf -x
            systemctl stop csf
            systemctl stop lfd
            systemctl disable csf
            systemctl disable lfd
            clear
            printf "${GREEN}Tat CSF thanh cong.${NC}\n"
            echo ""
            menu_csf
            ;;
        9)
            csf -e
            systemctl start csf
            systemctl start lfd
            systemctl enable csf
            systemctl enable lfd
            clear
            printf "${GREEN}Bat CSF thanh cong.${NC}\n"
            echo ""
            menu_csf
            ;;
        0) clear; menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done