#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s==========================%s\n" "${GREEN}" "${NC}"
printf "%sQuan ly Database - MariaDB%s\n" "${GREEN}" "${NC}"
printf "%s==========================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Danh sach Database%s\n" "${GREEN}" "${NC}"
    printf "%s2. Tao Database%s\n" "${GREEN}" "${NC}"
    printf "%s3. Doi mat khau DB User%s\n" "${GREEN}" "${NC}"
    printf "%s4. Xoa Database%s\n" "${GREEN}" "${NC}"
    printf "%s5. Backup Database%s\n" "${GREEN}" "${NC}"
    printf "%s6. Khoi phuc Database%s\n" "${GREEN}" "${NC}"
    printf "%s7. Xoa backup Database%s\n" "${GREEN}" "${NC}"
    printf "%s8. Khoi dong lai MariaDB%s\n" "${GREEN}" "${NC}"
    printf "%s9. Tat MariaDB%s\n" "${GREEN}" "${NC}"
    printf "%s10. Bat MariaDB%s\n" "${GREEN}" "${NC}"
    printf "%s ======================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; db_list ;;
        2) clear; db_create ;;
        3) clear; db_change_pass ;;
        4) clear; db_destroy ;;
        5) clear; db_backup ;;
        6) clear; db_restore ;;
        7) clear; destroy_backup ;;
        8)
            systemctl restart mariadb
            menu_database
            ;;
        9)
            systemctl stop mariadb
            systemctl disable mariadb
            printf "%s\n" "${GREEN}Tat MariaDB thanh cong.${NC}"
            menu_database
            ;;
        10)
            systemctl start mariadb
            systemctl enable mariadb
            printf "%s\n" "${GREEN}Bat MariaDB thanh cong.${NC}"
            menu_database
            ;;
        0) clear; menu_lemp ;;
        *) clear; printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done