#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
# Please don't copy copy under any circumstance for business reason! #
######################################################################

CHOICE=1

printf "${GREEN}==========================${NC}\n"
printf "${GREEN}Quan ly Database - MariaDB${NC}\n"
printf "${GREEN}==========================${NC}\n"

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Danh sach Database${NC}\n"
    printf "${GREEN}2. Tao Database${NC}\n"
    printf "${GREEN}3. Doi mat khau DB User${NC}\n"
    printf "${GREEN}4. Xoa Database${NC}\n"
    printf "${GREEN}5. Backup Database${NC}\n"
    printf "${GREEN}6. Khoi phuc Database${NC}\n"
    printf "${GREEN}7. Xoa backup Database${NC}\n"
    printf "${GREEN}8. Khoi dong lai MariaDB${NC}\n"
    printf "${GREEN}9. Tat MariaDB${NC}\n"
    printf "${GREEN}10. Bat MariaDB${NC}\n"
    printf "${GREEN} ----------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; db_list ;;
        2) clear; db_create ;;
        3) clear; db_change_pass ;;
		4) clear; db_destroy ;;
        5) clear; db_backup ;;
        6) clear; db_restore ;;
        7) clear; destroy_backup ;;
        8)
			systemctl restart mariadb
			menu_database
        	;;
    	9)
			systemctl stop mariadb
			systemctl disable mariadb
            printf "{GREEN}Tat MariaDB thanh cong.${NC}\n"
			menu_database
        	;;
    	10)
			systemctl start mariadb
			systemctl enable mariadb
            printf "{GREEN}Bat MariaDB thanh cong.${NC}\n"
			menu_database
        	;;
        0) clear; menu_lemp ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done