#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s===================%s\n" "${GREEN}" "${NC}"
printf "%s   Quan ly Domain  %s\n" "${GREEN}" "${NC}"
printf "%s===================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Danh sach ten mien%s\n" "${GREEN}" "${NC}"
    printf "%s2. Them ten mien%s\n" "${GREEN}" "${NC}"
    printf "%s3. Xoa ten mien%s\n" "${GREEN}" "${NC}"
    printf "%s4. Thay doi ten mien%s\n" "${GREEN}" "${NC}"
    printf "%s5. Rewrite Vhost Config%s\n" "${GREEN}" "${NC}"
    printf "%s ==================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; domain_list;;
        2) clear; domain_create ;;
        3) clear; domain_destroy ;;
        4) clear; domain_change ;;
        5) clear; rewrite_config ;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done