#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "${GREEN}===================${NC}\n"
printf "${GREEN}   Quan ly Domain  ${NC}\n"
printf "${GREEN}===================${NC}\n"
echo ""

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Danh sach ten mien${NC}\n"
    printf "${GREEN}2. Them ten mien${NC}\n"
    printf "${GREEN}3. Xoa ten mien${NC}\n"
    printf "${GREEN}4. Thay doi ten mien${NC}\n"
    printf "${GREEN} ------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; domain_list;;
        2) clear; domain_create ;;
        3) clear; domain_destroy ;;
        4) clear; domain_change ;;
        0) clear; menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done