#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
CHOICE=1

printf "%s===================%s\n" "${GREEN}" "${NC}"
printf "%s   Quan ly FTP     %s\n" "${GREEN}" "${NC}"
printf "%s   Port FTP:  %s   %s\n" "${GREEN}" "${ftp_port}" "${NC}"
printf "%s===================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Tao user FTP%s\n" "${GREEN}" "${NC}"
    printf "%s2. Doi mat khau FTP%s\n" "${GREEN}" "${NC}"
    printf "%s3. Xoa User FTP%s\n" "${GREEN}" "${NC}"
    printf "%s4. Doi Port FTP%s\n" "${GREEN}" "${NC}"
    printf "%s5. Cai dat PURE-FTPD%s\n" "${GREEN}" "${NC}"
    printf "%s ==================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; ftp_create_user;;
        2) clear; ftp_change_pwd ;;
        3) clear; ftp_destroy ;;
        4) clear; ftp_port ;;
        5) clear; ftp_install ;;
        0) clear; menu_lemp ;;
        *) clear; printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done