#!/bin/bash

#################################################
# Auto Install & Optimize LEMP Stack on CentOS 7#
# Version: 1.0                                  #
# Author: Sanvv - HOSTVN Technical              #
#                                               #
# Please don't remove copyright. Thank!         #
#################################################

CHOICE=1

printf "${GREEN}===================${NC}\n"
printf "${GREEN}   Quan ly Domain  ${NC}\n"
printf "${GREEN}===================${NC}\n"
echo ""

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Tao user FTP${NC}\n"
    printf "${GREEN}2. Doi mat khau FTP${NC}\n"
    printf "${GREEN}3. Xoa User FTP${NC}\n"
    printf "${GREEN}4. Doi Port FTP${NC}\n"
    printf "${GREEN} ------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; ftp_create_user;;
        2) clear; ftp_change_pwd ;;
        3) clear; ftp_destroy ;;
        4) clear; ftp_port ;;
        0) clear; menu_lemp ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done