#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s=================================%s\n" "${GREEN}" "${NC}"
printf "%s           Google Drive          %s\n" "${GREEN}" "${NC}"
printf "%s=================================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Thiet lap Google Drive%s\n" "${GREEN}" "${NC}"
    printf "%s2. Backup len GG Drive%s\n" "${GREEN}" "${NC}"
    printf "%s3. Khoi phuc du lieu tu GG Drive%s\n" "${GREEN}" "${NC}"
    printf "%s4. Xoa du lieu tren GG Drive%s\n" "${GREEN}" "${NC}"
    printf "%s5. Danh sach backup tren GG Drive%s\n" "${GREEN}" "${NC}"
    printf "%s6. Xoa Google Drive remote%s\n" "${GREEN}" "${NC}"
    printf "%s ================================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; ggdrive_connect;;
        2) clear; ggdrive_backup ;;
        3) clear; ggdrive_restore ;;
        4) clear; ggdrive_destroy ;;
        5) clear; ggdrive_list_backup ;;
		    6) clear; ggdrive_del_remote ;;
        0) clear; menu_backup ;;
        *) clear; printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done