#!/bin/bash

CHOICE=1

printf "${GREEN}===================${NC}\n"
printf "${GREEN}    Google Drive   ${NC}\n"
printf "${GREEN}===================${NC}\n"
echo ""

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Thiet lap Google Drive${NC}\n"
    printf "${GREEN}2. Backup len GG Drive${NC}\n"
    printf "${GREEN} ------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; connect_gg;;
        2) clear; backup_gg ;;
        0) clear; menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done