#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "${GREEN}=====================${NC}\n"
printf "${GREEN}Quan ly Let's Encrypt${NC}\n"
printf "${GREEN}=====================${NC}\n"
echo

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Them Let's Encrypt${NC}\n"
    printf "${GREEN}2. Kiem tra thoi han${NC}\n"
    printf "${GREEN}3. Go bo Let's Encrypt${NC}\n"
    printf "${GREEN} ---------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; le_create ;;
        2) clear; le_check_expired ;;
        3) clear; le_remove ;;
        0) clear; menu_ssl ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done