#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s===================%s\n" "${GREEN}" "${NC}"
printf "%s    Quan ly Log    %s\n" "${GREEN}" "${NC}"
printf "%s===================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Xem Log Nginx%s\n" "${GREEN}" "${NC}"
    printf "%s2. Xem Log PHP%s\n" "${GREEN}" "${NC}"
    printf "%s3. Xem Log MariaDB%s\n" "${GREEN}" "${NC}"
    printf "%s4. Xem theo ten mien%s\n" "${GREEN}" "${NC}"
    printf "%s ==================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1)
            clear
            printf "%s\n" "${RED}Hien thi 10 dong log moi nhat...${NC}"
            echo ""
            tail /var/log/nginx/error.log
            printf "%s\n" "${RED}Vi tri file log: /var/log/nginx/error.log${NC}"
            menu_log
            ;;
        2)
            clear
            printf "%s\n" "${RED}Hien thi 10 dong log moi nhat...${NC}"
            echo ""
            tail /var/log/php-fpm/error.log
            printf "%s\n" "${RED}Vi tri file log: /var/log/php-fpm/error.log${NC}"
            menu_log
            ;;
        3)
            clear
            printf "%s\n" "${RED}Hien thi 10 dong log moi nhat...${NC}"
            echo ""
            tail /var/log/mysql/mysqld.log
            printf "%s\n" "${RED}Vi tri file log: /var/log/mysql/mysqld.log${NC}"
            menu_log
            ;;
        4) clear; domain_log;;
        0) clear; menu_lemp ;;
        *) clear; printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done