#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

nginx_status=$(systemctl status nginx.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)
nginx_v=$(nginx -v 2>&1 | grep -o '[0-9.]*$'; echo)
set_cl(){
    if [[ ${nginx_status} == "active" ]]; then
        nginx_status=$(printf "${GREEN}${nginx_status}${NC}")
    else
        nginx_status=$(printf "${RED}${nginx_status}${NC}")
    fi
}

set_cl

printf "${GREEN}=============================${NC}\n"
printf "${GREEN}        Quan ly Nginx        ${NC}\n"
printf "${GREEN}=============================${NC}\n"
printf "${GREEN}Phien ban : %s${NC}\n" "${nginx_v}"
printf "${GREEN}-----------------------------${NC}\n"
printf "${GREEN}Trạng thái: %s${NC}\n" "${nginx_status}"
printf "${GREEN}-----------------------------${NC}\n"
echo

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Khoi đong lai nginx${NC}\n"
    printf "${GREEN}2. Kiem tra cau hinh Nginx${NC}\n"
    printf "${GREEN}3. Cap nhat Nginx${NC}\n"
    printf "${GREEN} -------------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1)
            clear
            printf "${RED}Dang khoi đong lai...${NC}\n"
            sleep 1
            systemctl restart nginx
            sleep 2
            echo
            menu_nginx
            ;;
        2)
            clear
            sleep 1
            nginx -t
            sleep 2
            echo
            menu_nginx
            ;;
        3)
            printf "${RED}Chuan bi cap nhat...${NC}\n"
            sleep 1
            yum -y update nginx
            echo
            menu_nginx
            ;;
        0) clear; menu_lemp ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done