#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

nginx_status=$(pgrep -f nginx)
nginx_v=$(nginx -v 2>&1 | grep -o '[0-9.]*$'; echo)
set_cl(){
    if [[ -n ${nginx_status} ]]; then
        nginx_status=$(printf "%sHoat dong%s" "${GREEN}" "${NC}")
    else
        nginx_status=$(printf "%sKhong hoat dong%s" "${RED}" "${NC}")
    fi
}

set_cl

printf "%s=============================%s\n" "${GREEN}" "${NC}"
printf "%s        Quan ly Nginx        %s\n" "${GREEN}" "${NC}"
printf "%s=============================%s\n" "${GREEN}" "${NC}"
printf "%sPhien ban : %s%s\n" "${GREEN}" "${nginx_v}" "${NC}"
printf "%s=============================%s\n" "${GREEN}" "${NC}"
printf "%sTrang thai: %s%s\n" "${GREEN}" "${nginx_status}" "${NC}"
printf "%s=============================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Khoi đong lai nginx%s\n" "${GREEN}" "${NC}"
    printf "%s2. Kiem tra cau hinh Nginx%s\n" "${GREEN}" "${NC}"
    printf "%s3. Cap nhat Nginx%s\n" "${GREEN}" "${NC}"
    printf "%s =========================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1)
            clear
            printf "%s\n" "${RED}Dang khoi đong lai...${NC}"
            sleep 1
            systemctl restart nginx
            clear
            printf "%s\n" "${GREEN}Khoi đong lai Nginx thanh cong.${NC}"
            sleep 1
            echo
            menu_nginx
            ;;
        2)
            clear
            sleep 1
            nginx -t
            sleep 1
            echo
            menu_nginx
            ;;
        3)
            printf "%s\n" "${RED}Chuan bi cap nhat...${NC}"
            sleep 1
            yum -y update nginx
            clear
            printf "%s\n" "${GREEN}Hoan tat cap nhat.${NC}"
            echo
            menu_nginx
            ;;
        0) clear; menu_lemp ;;
        *) clear; printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done