#!/bin/bash

#################################################
# Auto Install & Optimize LEMP Stack on CentOS 7#
# Version: 1.0                                  #
# Author: Sanvv - HOSTVN Technical              #
#                                               #
# Please don't remove copyright. Thank!         #
#################################################

CHOICE=1

printf "${GREEN}======================${NC}\n"
printf "${GREEN}Phan quyen Chown/Chmod${NC}\n"
printf "${GREEN}======================${NC}\n"
echo

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Phan quyen website${NC}\n"
    printf "${GREEN}2. Phan quyen toan bo website${NC}\n"
    printf "${GREEN} ----------------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) permission_one ;;
        2) permission_all ;;
        0) clear; menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done