#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154

CHOICE=1

printf "%s==================================%s\n" "${GREEN}" "${NC}"
printf "%s           Quan ly PHP            %s\n" "${GREEN}" "${NC}"
printf "%s==================================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Kiem tra phien ban PHP mac dinh%s\n" "${GREEN}" "${NC}"
    printf "%s2. Kiem tra phien ban PHP 2%s\n" "${GREEN}" "${NC}"
    printf "%s3. Cap nhat phien ban PHP%s\n" "${GREEN}" "${NC}"
    printf "%s4. Khoi đong lai PHP              %s\n" "${GREEN}" "${NC}"
    printf "%s5. Cau hinh thong so PHP          %s\n" "${GREEN}" "${NC}"
    printf "%s6. Thay doi phien ban PHP mac dinh%s\n" "${GREEN}" "${NC}"
    printf "%s7. Thay doi phien ban PHP 2       %s\n" "${GREEN}" "${NC}"
    printf "%s8. Cai dat phien ban PHP thu 2    %s\n" "${GREEN}" "${NC}"
    printf "%s9. Cai dat ionCube    %s\n" "${GREEN}" "${NC}"
    printf "%s10. Bat/Tat Open Basedir    %s\n" "${GREEN}" "${NC}"
    printf "%s =================================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) php -v; menu_php ;;
        2)
            if [[ "${php2_release}" != "yes" ]]; then
                clear
                printf "${RED}Ban chua cai dat phien ban PHP thu 2.%s\n"
            else
                #https://www.howtoforge.com/tutorial/linux-grep-command/
                #https://stackoverflow.com/a/6284370
                php2_ver=$(grep -w "php2_version" "${FILE_INFO}" | cut -f2 -d'=')
                echo ""
                echo "phien ban PHP thu 2 dang su dung la: ${php2_ver}"
                echo ""
            fi
            menu_php
            ;;
        3)
            yum -y update php-fpm
            clear
            printf "%s\n" "${RED}Phien ban PHP mac dinh da la moi nhat.${NC}"

            if [[ "${php2_release}" == "yes" ]]; then
                yum -y update "${php2_version}"-php-fpm
                clear
                printf "%s\n" "${RED}Phien ban PHP 2 dang la moi nhat.${NC}"
            fi
            menu_php
            ;;
        4)
            systemctl restart php-fpm
            if [[ "${php2_release}" == "yes" ]]; then
                systemctl restart "${php2_version}"-php-fpm
            fi
            clear
            printf "%s\n" "${GREEN}Khoi dong lai PHP thanh cong.${NC}"
            menu_php
            ;;
        5) clear; php_setting ;;
        6) clear; php1_change ;;
        7) clear; php2_change ;;
        8) clear; php_inst_ver_2 ;;
        9) clear; php_inst_ioncube ;;
        10) clear; php_open_basedir ;;
        0) clear; menu_lemp ;;
        *) clear; printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done