#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154

CHOICE=1

printf "${GREEN}==================================${NC}\n"
printf "${GREEN}           Quan ly PHP            ${NC}\n"
printf "${GREEN}==================================${NC}\n"
echo

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Kiem tra phien ban PHP mac dinh${NC}\n"
    printf "${GREEN}2. Kiem tra phien ban PHP 2${NC}\n"
    printf "${GREEN}3. Cap nhat phien ban PHP${NC}\n"
    printf "${GREEN}4. Khoi đong lai PHP              ${NC}\n"
    printf "${GREEN}5. Cau hinh thong so PHP          ${NC}\n"
    printf "${GREEN}6. Thay doi phien ban PHP mac dinh${NC}\n"
    printf "${GREEN}7. Thay doi phien ban PHP 2       ${NC}\n"
    printf "${GREEN}8. Cai dat phien ban PHP thu 2    ${NC}\n"
    printf "${GREEN} ---------------------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) php -v; menu_php ;;
        2)
            if [[ "${php2_release}" != "yes" ]]; then
                clear
                printf "${RED}Ban chua cai dat phien ban PHP thu 2.${NC}\n"
            else
                php2_ver=$(grep "php2_version" "${FILE_INFO}" | cut -f2 -d'=')
                echo ""
                echo "phien ban PHP thu 2 dang su dung la: ${php2_ver}"
                echo ""
            fi
            menu_php
            ;;
        3)
            yum -y update php-fpm
            clear
            printf "${RED}Phien ban PHP mac dinh da la moi nhat.${NC}\n"

            if [[ "${php2_release}" == "yes" ]]; then
                yum -y update "${php2_version}"-php-fpm
                clear
                printf "${RED}Phien ban PHP 2 dang la moi nhat.${NC}\n"
            fi
            menu_php
            ;;
        4)
            systemctl restart php-fpm
            if [[ "${php2_release}" == "yes" ]]; then
                systemctl restart "${php2_version}"-php-fpm
            fi
            clear
            printf "${GREEN}Khoi dong lai PHP thanh cong.${NC}\n"
            menu_php
            ;;
        5) clear; php_setting ;;
        6) clear; php1_change ;;
        7) clear; php2_change ;;
        8) clear; php_inst_ver_2 ;;
        0) clear; menu_lemp ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done