#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
CHOICE=1

printf "%s======================%s\n" "${GREEN}" "${NC}"
printf "     %sQuan ly SSH%s     \n" "${GREEN}" "${NC}"
printf "     %sPort SSH: %s%s    \n" "${GREEN}" "${ssh_port}" "${NC}"
printf "%s======================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Doi port SSH%s\n" "${GREEN}" "${NC}"
    printf "%s2. Doi Password SSH%s\n" "${GREEN}" "${NC}"
    printf "%s ==================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE

    if [[  -z "${CHOICE}" ]]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) ssh_change_port ;;
        2)
            clear
            passwd
            menu_ssh
            ;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done