#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
CHOICE=1

printf "${GREEN}======================${NC}\n"
printf "     ${GREEN}Quan ly SSH${NC}     \n"
printf "     ${GREEN}Port SSH: %s${NC}    \n" "${ssh_port}"
printf "${GREEN}======================${NC}\n"
echo

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Doi port SSH${NC}\n"
    printf "${GREEN}2. Doi Password SSH${NC}\n"
    printf "${GREEN} ------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE

    if [[  -z "${CHOICE}" ]]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) ssh_change_port ;;
        2)
            clear
            passwd
            menu_ssh
            ;;
        0) clear; menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done