#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "${GREEN}==========================${NC}\n"
printf "${GREEN}Kiem tra thong tin may chu${NC}\n"
printf "${GREEN}==========================${NC}\n"
echo

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Trang thai Webserver${NC}\n"
    printf "${GREEN}2. Thong tin VPS${NC}\n"
    printf "${GREEN}3. Thong tin khac${NC}\n"
    printf "${GREEN}4. Xem cac tien trinh tren VPS${NC}\n"
    printf "${GREEN}5. Kiem tra dung luong VPS${NC}\n"
    printf "${GREEN}6. Thay doi thong tin SSH${NC}\n"
    printf "${GREEN}7. Cap nhat VPS${NC}\n"
    printf "${GREEN}8. Cap nhat HOSTVN Script${NC}\n"
    printf "${GREEN} ----------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; info_webserver ;;
        2) clear; info_vps ;;
        3) clear; info_other ;;
        4)
            clear
            echo ""
            printf "${GREEN}Dang mo htop. De thoat khoi htop bam CTRL + C${NC}\n"
            echo ""
            sleep 4
            htop
            ;;
        5)
            clear
            echo ""
            printf "${GREEN}Dang kiem tra dung luong VPS${NC}\n"
            echo ""
            sleep 3
            df -h
            menu_vps
            ;;
        6) clear; menu_ssh ;;
        7)
            printf "${RED}}Lưu y: Viec cap nhat he thong co the se gay ra ca loi khong mong muon.${NC}\n"
            read -r -p "Ban chac chan muon cap nhat ? (y/N)" confirm_update
            if [[ ${confirm_update} =~ ^([yY])$ ]]; then
                echo "Chuan bi cap nhat VPS..."
                sleep 2
                yum -y update
                clear
                printf "${GREEN}Qua trinh cap nhat da hoan tat.${NC}\n"
            else
                clear
                printf "${GREEN}Ban da chon huy cap nhat.${NC}\n"
            fi

            menu_vps
            ;;
        8) update_script ;;
        0) clear; menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done