#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s=========================================%s\n" "${GREEN}" "${NC}"
printf "%s            Quan ly WordPress            %s\n" "${GREEN}" "${NC}"
printf "%s=========================================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Cai dat WordPress tu dong%s\n" "${GREEN}" "${NC}"
    printf "%s2. Kiem tra phien ban WordPress%s\n" "${GREEN}" "${NC}"
    printf "%s3. Cap nhat phien ban WordPress%s\n" "${GREEN}" "${NC}"
    printf "%s4. Quan ly Plugins%s\n" "${GREEN}" "${NC}"
    printf "%s5. Quan ly Database%s\n" "${GREEN}" "${NC}"
    printf "%s6. Khoi phuc/Sao luu du lieu%s\n" "${GREEN}" "${NC}"
    printf "%s7. Chuc nang nang cao%s\n" "${GREEN}" "${NC}"
    printf "%s8. Thay doi ten mien%s\n" "${GREEN}" "${NC}"
    printf "%s9. Doi mat khau admin (wp-admin)%s\n" "${GREEN}" "${NC}"
    printf "%s ========================================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; wp_auto_install ;;
        2) clear; wp_version ;;
        3) clear; wp_update ;;
        4) clear; wp_menu_plugins ;;
        5) clear; wp_menu_database ;;
        6) clear; wp_menu_backup ;;
        7) clear; wp_menu_advanced ;;
        8) clear; wp_change_domain ;;
        9) clear; wp_change_pass_admin ;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done
