#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "${GREEN}=========================================${NC}\n"
printf "${GREEN}            Quan ly WordPress            ${NC}\n"
printf "${GREEN}=========================================${NC}\n"
echo

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Cai dat WordPress tu dong${NC}\n"
    printf "${GREEN}2. Kiem tra phien ban WordPress${NC}\n"
    printf "${GREEN}3. Cap nhat phien ban WordPress${NC}\n"
    printf "${GREEN}4. Quan ly Plugins${NC}\n"
    printf "${GREEN}5. Quan ly Database${NC}\n"
    printf "${GREEN}6. Khoi phuc/Sao luu du lieu${NC}\n"
    printf "${GREEN}7. Chuc nang nang cao${NC}\n"
    printf "${GREEN}8. Thay doi ten mien${NC}\n"
    printf "${GREEN}9. Doi mat khau admin (wp-admin)${NC}\n"
    printf "${GREEN} ----------------------------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; wp_auto_install ;;
        2) clear; wp_version ;;
        3) clear; wp_update ;;
        4) clear; wp_menu_plugins ;;
        5) clear; wp_menu_database ;;
        6) clear; wp_menu_backup ;;
        7) clear; wp_menu_advanced ;;
        8) clear; wp_change_domain ;;
        9) clear; wp_change_pass_admin ;;
        0) clear; menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done
