#!/bin/bash

#################################################
# Auto Install & Optimize LEMP Stack on CentOS 7#
# Version: 1.0                                  #
# Author: Sanvv - HOSTVN Technical              #
#                                               #
# Please don't remove copyright. Thank!         #
#################################################

CHOICE=1

printf "${GREEN}=========================================${NC}\n"
printf "${GREEN}            Quan ly WordPress            ${NC}\n"
printf "${GREEN}=========================================${NC}\n"
echo

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Kiem tra phien ban WordPress${NC}\n"
    printf "${GREEN}2. Cap nhat phien ban WordPress${NC}\n"
    printf "${GREEN}3. Cap nhat plugins (Tru plugins tra phi)${NC}\n"
    printf "${GREEN}4. Toi ưu database${NC}\n"
    printf "${GREEN}5. Repair database${NC}\n"
    printf "${GREEN}6. Sao luu du lieu (Local)${NC}\n"
    printf "${GREEN}7. Khoi phuc du lieu (Local)${NC}\n"
    printf "${GREEN}8. Thay doi ten mien${NC}\n"
    printf "${GREEN}9. Doi mat khau admin (wp-admin)${NC}\n"
    printf "${GREEN}10. Cai dat WordPress tu dong${NC}\n"
    printf "${GREEN}11. Bat/Tat Yoast Seo config${NC}\n"
    printf "${GREEN}12. Bat/Tat Rank Math Seo config${NC}\n"
    printf "${GREEN}13. Cau hinh Nginx voi plugin cache${NC}\n"
    printf "${GREEN}14. Them cache key tranh trung lap noi dung${NC}\n"
    printf "${GREEN}15. Bat/Tat Debug mode${NC}\n"
    printf "${GREEN}16. Bat/Tat che do bao tri (Maintenance mode)${NC}\n"
    printf "${GREEN}17. Huy kich hoat toan bo plugins${NC}\n"
    printf "${GREEN}18. Sao luu len Google Drive${NC}\n"
    printf "${GREEN}19. Thiet lap backup tu dong${NC}\n"
    printf "${GREEN} ----------------------------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; wp_version ;;
        2) clear; wp_update ;;
        3) clear; wp_update_plugins ;;
        4) clear; wp_optimize_db ;;
        5) clear; wp_repair_db ;;
        6) clear; wp_backup ;;
        7) clear; wp_restore ;;
        8) clear; wp_change_domain ;;
        9) clear; wp_change_pass_admin ;;
        10) clear; wp_auto_install ;;
        11) clear; wp_seo ;;
        12) clear; wp_rank_math_seo ;;
        13) clear; wp_plugin_cache ;;
        14) clear; wp_cache_key ;;
        15) clear; wp_debug ;;
        16) clear; wp_maintenance ;;
        17)
            wp plugin deactivate --all --allow-root
            printf "${GREEN}Huy kich hoat toan bo plugin thanh cong.${NC}\n"
            echo ""
            menu_wp
            ;;
        18) clear; menu_ggdrive ;;
        19) clear; menu_cronjob ;;
        0) clear; menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done
