#!/bin/bash

set_var(){
	redis_status="$(systemctl status redis.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
	memcached_status="$(systemctl status memcached.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
}

clear_cache(){
	if [ "${redis_status}" == "active" ]; then
		systemctl restart redis
		printf "${GREEN}Xoa cache thanh cong.${NC}\n"
	elif [ "${memcached_status}" == "active" ]; then
		systemctl restart memcached
		printf "${GREEN}Xoa cache thanh cong.${NC}\n"
	else
		printf "${RED}Ban chua bat cache.${NC}\n"
	fi
}

run(){
	set_var
	clear_cache
}

run
sleep 2
menu_cache