#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
# Please don't copy copy under any circumstance for business reason! #
######################################################################

# shellcheck disable=SC2154

set_var(){
	redis_status="$(systemctl status redis.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
	memcached_status="$(systemctl status memcached.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
}

clear_cache(){
    if [ "${redis_status}" == "active" ]; then
        systemctl restart redis
        printf "${GREEN}Xoa cache thanh cong.${NC}\n"
    fi
    if [ "${memcached_status}" == "active" ]; then
        systemctl restart memcached
        printf "${GREEN}Xoa cache thanh cong.${NC}\n"
    fi

    systemctl restart php-fpm

    if [[ "${php2_release}" == "yes" ]]; then
        systemctl restart "${php2_version}"-php-fpm
    fi

    printf "${GREEN}Xoa cache thanh cong.${NC}\n"
}

_run(){
	set_var
	clear_cache
}

_run
sleep 2
menu_cache