#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/helpers/variable_php

confirm(){
    read -r -p "Ban muon cai dat Redis ? (y/n) " prompt_redis
}

install(){
    yum --enablerepo=remi install redis -y
    mv /etc/redis.conf /etc/redis.conf.bak
    cat >> "/etc/redis.conf" << EOFREDIS
maxmemory ${MAX_MEMORY}mb
maxmemory-policy allkeys-lru
save ""
EOFREDIS
    semanage permissive -a redis_t
}

inst_redisdadmin(){
    cd_dir "${DEFAULT_DIR_TOOL}"
    git clone https://github.com/ErikDubbelboer/phpRedisAdmin.git
    mv phpRedisAdmin redis
    cd_dir "${DEFAULT_DIR_TOOL}"/redis
    git clone https://github.com/nrk/predis.git vendor
    cd .. && chown -R nginx:nginx redis
}

_run(){
    if [ ! -f "/etc/redis.conf" ]; then
        install
        inst_redisdadmin
        clear
        printf "Cai dat Redis thanh cong.\n"
    else
        printf "${RED}Redis da duoc cai dat truoc do roi.${NC}\n"
    fi
}

confirm
if [[ "${prompt_redis}" =~ ^([yY])$ ]];then
    _run
else
    clear
    printf "${GREEN}Ban da huy cai dat Redis.${NC}\n"
fi

menu_cache