#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu

CHOICE=1
redis_status="$(pgrep -f redis)"
memcached_status="$(pgrep -f memcached)"

printf "${GREEN}-----------------${NC}\n"
printf "Quan ly Memcached${NC}\n"
printf "${GREEN}-----------------${NC}\n"

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Mo Memcached${NC}\n"
    printf "${GREEN}2. Tat Memcached${NC}\n"
    echo " ----------------------------------------------- "
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1)
            if [ ! -f "/etc/sysconfig/memcached" ]; then
                clear
                printf "${RED}Memcached chua duoc cai dat.${NC}\n"
            else
                if [[ -n "${redis_status}" && -z "${memcached_status}" ]]; then
                    printf "${RED}Ban dang su dung Redis Cache.${NC}\n"
                elif [[ -n "${redis_status}" && -n "${memcached_status}" ]]; then
                    printf "${RED}Ban dang su dung ca Memcached va Redis Cache.${NC}\n"
                    printf "${RED}Dieu nay co the anh hương den hieu suat cua VPS. Khuyen nghi chi nen xai mot cache.${NC}\n"
                elif [[ -z "${redis_status}" && -n "${memcached_status}" ]]; then
                    printf "${RED}Memcached hien dang hoat dong.${NC}\n"
                else
                    printf "${GREEN}Dang tien hanh mo Memcached...${NC}\n"
                    sleep 2
                    systemctl start memcached
                    systemctl enable memcached
                    crontab -l > clear_memcached
                    echo "23 */37 * * * service memcached restart >/dev/null 2>&1" >> clear_memcached
                    crontab clear_memcached
                    rm -rf clear_memcached
                    clear
                    printf "${GREEN}Da bat Memcached.${NC}\n"
                fi
            fi

            menu_cache
            ;;
        2)
            if [ -n "${memcached_status}" ]; then
                printf "${GREEN}Dang tien hanh tat Memcached...${NC}\n"
                sleep 1
                systemctl stop memcached
                systemctl disable memcached
                crontab -u root -l | grep -v "memcached" | crontab -u root -
                clear
                printf "${GREEN}Da tat Memcached.${NC}\n"
            else
                printf "${RED}Memcached hien khong hoat dong.${NC}\n"
            fi

            menu_cache
            ;;
        0) menu_cache ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done