#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu

CHOICE=1
memcached_status="$(pgrep -f memcached)"

if [ -n "${memcached_status}" ]; then
    status=$(printf "%s\n" "${GREEN}Hoat dong${NC}")
else
    status=$(printf "%s\n" "${RED}Khong Hoat dong${NC}")
fi

printf "%s=====================%s\n" "${GREEN}" "${NC}"
printf "%sQuan ly Memcached%s\n" "${GREEN}" "${NC}"
printf "%s\n" "${GREEN}Trang thai:${NC} ${status}"
printf "%s=====================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Mo Memcached%s\n" "${GREEN}" "${NC}"
    printf "%s2. Tat Memcached%s\n" "${GREEN}" "${NC}"
    echo " ----------------------------------------------- "
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1)
            if [ ! -f "/etc/sysconfig/memcached" ]; then
                clear
                printf "%sMemcached chua duoc cai dat.%s\n" "${RED}" "${NC}"
            else
                printf "%sDang tien hanh mo Memcached...%s\n" "${GREEN}" "${NC}"
                sleep 2
                systemctl start memcached
                systemctl enable memcached
                cron_exists=$(crontab -l | grep -w 'memcached')
                if [ -z "${cron_exists}" ]; then
                    crontab -l > clear_memcached
                    echo "23 */37 * * * service memcached restart >/dev/null 2>&1" >> clear_memcached
                    crontab clear_memcached
                    rm -rf clear_memcached
                fi
                clear
                printf "%sDa bat Memcached.%s\n" "${GREEN}" "${NC}"
            fi

            menu_cache
            ;;
        2)
            if [ -n "${memcached_status}" ]; then
                printf "%sDang tien hanh tat Memcached...%s\n" "${GREEN}" "${NC}"
                sleep 1
                systemctl stop memcached
                systemctl disable memcached
                cron_exists=$(crontab -l | grep -w 'memcached')
                if [ -n "${cron_exists}" ]; then
                    crontab -u root -l | grep -v "memcached" | crontab -u root -
                fi
                clear
                printf "%sDa tat Memcached.%s\n" "${GREEN}" "${NC}"
            else
                printf "%sMemcached hien khong hoat dong.%s\n" "${RED}" "${NC}"
            fi

            menu_cache
            ;;
        0) clear; menu_cache ;;
        *) clear; printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done