#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
CHOICE=1

opcache_status=$(grep -w "opcache.enable" "/etc/php.d/10-opcache.ini" | cut -f2 -d'=');
if [[ ${opcache_status} -eq 1 ]]; then
    status="Bat"
else
    status="Tat"
fi

printf "%s=========================================%s\n" "${GREEN}" "${NC}"
printf "%s           Quan ly Opcache               %s\n" "${GREEN}" "${NC}"
printf "%s        Trang thai Opcache: %s           %s\n" "${GREEN}" "${status}" "${NC}"
printf "%s=========================================%s\n" "${GREEN}" "${NC}"
echo

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Bat/Tat Opcache%s\n" "${GREEN}" "${NC}"
    printf "%s2. Them website vao blacklist%s\n" "${GREEN}" "${NC}"
    printf "%s3. Xoa website khoi blacklist%s\n" "${GREEN}" "${NC}"
    printf "%s4. Xoa cache Opcache%s\n" "${GREEN}" "${NC}"
    printf "%s ========================================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; de_opcache ;;
        2) clear; opcache_add_blacklist ;;
        3) clear; opcache_remove_blacklist ;;
        4) clear; clear_opcache ;;
        0) clear; menu_cache ;;
        *) clear; printf "%sLua chon cua ban khong chinh xac. Vui long chon lai.%s\n" "${RED}" "${NC}";;
    esac
done