#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
CHOICE=1

opcache_status=$(grep -w "opcache.enable" "/etc/php.d/10-opcache.ini" | cut -f2 -d'=');
if [[ ${opcache_status} -eq 1 ]]; then
    status="Bat"
else
    status="Tat"
fi

printf "${GREEN}=========================================${NC}\n"
printf "${GREEN}           Quan ly Opcache               ${NC}\n"
printf "${GREEN}        Trang thai Opcache: %s           ${NC}\n" "${status}"
printf "${GREEN}=========================================${NC}\n"
echo

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Bat/Tat Opcache${NC}\n"
    printf "${GREEN}2. Them website vao blacklist${NC}\n"
    printf "${GREEN}3. Xoa website khoi blacklist${NC}\n"
    printf "${GREEN}4. Xoa cache Opcache${NC}\n"
    printf "${GREEN} ----------------------------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; de_opcache ;;
        2) clear; opcache_add_blacklist ;;
        3) clear; opcache_remove_blacklist ;;
        4) clear; clear_opcache ;;
        0) clear; menu_cache ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done