#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu

CHOICE=1
redis_status="$(pgrep -f redis)"

if [ -n "${redis_status}" ]; then
    status=$(printf "%s\n" "${GREEN}Hoat dong${NC}")
else
    status=$(printf "%s\n" "${RED}Khong Hoat dong${NC}")
fi

printf "%s=====================%s\n" "${GREEN}" "${NC}"
printf "%sQuan ly Redis Cache%s\n" "${GREEN}" "${NC}"
printf "%s\n" "${GREEN}Trang thai:${NC} ${status}"
printf "%s=====================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Bat Redis Cache%s\n" "${GREEN}" "${NC}"
    printf "%s2. Tat Redis Cache%s\n" "${GREEN}" "${NC}"
    printf "%s =================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1)
            if [ ! -f "/etc/redis.conf" ]; then
                clear
                printf "%s\n" "${RED}Redis chua duoc cai dat.${NC}"
            else
                printf "%s\n" "${GREEN}Dang tien hanh mo Redis Cache...${NC}"
                sleep 1
                systemctl enable redis.service
                systemctl start redis.service
                cron_exists=$(crontab -l | grep -w 'redis')
                if [ -z "${cron_exists}" ]; then
                    crontab -l > clear_redis
                    echo "23 */38 * * * service redis restart >/dev/null 2>&1" >> clear_redis
                    crontab clear_redis
                    rm -rf clear_redis
                fi
                clear
                printf "%s\n" "${GREEN}Da bat Redis Cache.${NC}"
            fi
            menu_cache
            ;;
        2)
            if [ -n "${redis_status}" ]; then
                printf "%s\n" "${GREEN}Dang tien hanh tat Redis Cache...${NC}"
                sleep 1
                systemctl stop redis.service
                systemctl disable redis.service
                cron_exists=$(crontab -l | grep -w 'redis')
                if [ -n "${cron_exists}" ]; then
                    crontab -u root -l | grep -v "redis" | crontab -u root -
                fi
                clear
                printf "%s\n" "${GREEN}Da tat Redis Cache.${NC}"
            else
                printf "%s\n" "${RED}Redis cache hien khong hoat dong.${NC}"
            fi

            menu_cache
            ;;
        0) clear; menu_cache ;;
        *) clear; printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done