#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu

CHOICE=1

echo "-------------------------------------------------------------------------"
echo "Quản lý Redis Cache"
echo "-------------------------------------------------------------------------"
status=$(systemctl status redis.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)
printf "Trạng thái: %s\n" "${status}"
echo "-------------------------------------------------------------------------"
echo

while [ "${CHOICE}" != "0" ]
do
    echo "1. Bật Redis Cache"
    echo "2. Tắt Redis Cache"
    echo " ----------------------------------------------- "
    read -p " Nhập vào lựa chọn của bạn [0 = Thoát] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1)
            echo "Đang tiến hành mở Redis Cache..."
            sleep 1
            systemctl enable redis.service
            systemctl start redis.service
            clear
            echo "Đã bật Redis Cache"
            echo
            menu_cache
            ;;
        2)
            echo "Đang tiến hành tắt Redis Cache..."
            sleep 1
            systemctl stop redis.service
            systemctl disable redis.service
            clear
            echo "Đã tắt Redis Cache"
            echo
            menu_cache
            ;;
        0) menu_primary ;;
        *) echo -e "Lựa chọn của bạn không chính xác. Vui lòng chọn lại.";;
    esac
done