#!/bin/bash

#################################################
# Auto Install & Optimize LEMP Stack on CentOS 7#
# Version: 1.0                                  #
# Author: Sanvv - HOSTVN Technical              #
#                                               #
# Please don't remove copyright. Thank!         #
#################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu

CHOICE=1
redis_status="$(systemctl status redis.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
memcached_status="$(systemctl status memcached.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"

echo "-------------------"
echo "Quan ly Redis Cache"
echo "-------------------"

while [ "${CHOICE}" != "0" ]
do
    echo "1. Bat Redis Cache"
    echo "2. Tat Redis Cache"
    echo " -----------------"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1)
            if [ "${memcached_status}" == "active" ]; then
                printf "${RED}Ban dang su dung Memcached.${NC}\n"
            else
                printf "${GREEN}Dang tien hanh mo Redis Cache...${NC}\n"
                sleep 1
                systemctl enable redis.service
                systemctl start redis.service
                clear
                printf "${GREEN}Da bat Redis Cache.${NC}\n"
            fi

            menu_cache
            ;;
        2)
            if [ "${redis_status}" == "active" ]; then
                printf "${GREEN}Dang tien hanh tat Redis Cache...${NC}\n"
                sleep 1
                systemctl stop redis.service
                systemctl disable redis.service
                clear
                printf "${GREEN}Da tat Redis Cache.${NC}\n"
            else
                printf "${RED}Redis cache hien khong hoat dong.${NC}\n"
            fi

            menu_cache
            ;;
        0) menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done