#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC2207
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/variable_php

confirm(){
    prompt_php2="n"
    read -r -p "Ban co muon thay doi phien ban PHP 2 khong ? (y/n) " prompt_php2
}

set_var(){
    OS_VER=$(rpm -E %centos)
    PECL_PHP_LINK="https://pecl.php.net/get"
    IGBINARY_VERSION=$(curl -s "${UPDATE_LINK}"/version | grep "igbinary_version=" | cut -f2 -d'=')
    PHP_MEMCACHED_VERSION=$(curl -s "${UPDATE_LINK}"/version | grep "php_memcached_version=" | cut -f2 -d'=')
    PHP_REDIS_VERSION=$(curl -s "${UPDATE_LINK}"/version | grep "php_redis_version=" | cut -f2 -d'=')
    PHP_LIST=( $(curl -s "${UPDATE_LINK}"/version | grep "php_list=" | cut -f2 -d'=') )
    if [[ "${OS_VER}" -eq 8 ]]; then
        index=0
        for keyword in "${PHP_LIST[@]}"; do
            if [[ "$keyword" = "php7.1" || "$keyword" = "php7.0" || "$keyword" = "php5.6" ]]; then
                unset "PHP_LIST[$index]"
            fi
            (( index++ ))
        done
    fi
}

check_duplicate_php(){
    if [[ "${php2_new}" == "${php2_version}" ]]; then
        ALERT=$(printf "${RED}Phien ban PHP 2 ban muon thay giong phien ban PHP 2 hien tai. Huy cai dat.${NC}\n")
    fi

    if [[ "${php2_new}" == "${php1_version}" ]]; then
    	ALERT=$(printf "${RED}Phien ban PHP 2 ban chon giong phien ban PHP 1. Huy cai dat.${NC}\n")
    fi
}

select_php_ver(){
    read -r -p "Ban co muon thay doi phien ban PHP thu 2 khong ? (y/n) " prompt_php2
    if [[ "${prompt_php2}" =~ ^([yY])$ ]]; then
        clear
        while true
        do
            printf "Lua chon phien ban PHP thu 2\n"
            PS3="Nhap vao lua chon cua ban: "
            select opt2 in "${PHP_LIST[@]}"
            do
                case $opt2 in
                    "${opt2}") php2_new="${opt2/.}"; break;;
                esac
            done
            echo

            if [[ " ${PHP_LIST[*]} " == *" $(echo "${php2_new}" | fold -w4 | paste -sd'.') "* ]]; then
                break
            else
                clear
                printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n"
            fi
        done
    fi
}

remove_old_php(){
    yum -y remove "${php2_new}" "${php2_new}"-php-fpm "${php2_new}"-php-ldap "${php2_new}"-php-zip "${php2_new}"-php-embedded "${php2_new}"-php-cli "${php2_new}"-php-mysql "${php2_new}"-php-common "${php2_new}"-php-gd "${php2_new}"-php-xml "${php2_new}"-php-mbstring \
    "${php2_new}"-php-mcrypt "${php2_new}"-php-pdo "${php2_new}"-php-soap "${php2_new}"-php-json "${php2_new}"-php-simplexml "${php2_new}"-php-process "${php2_new}"-php-curl "${php2_new}"-php-bcmath "${php2_new}"-php-snmp "${php2_new}"-php-pspell "${php2_new}"-php-gmp \
    "${php2_new}"-php-intl "${php2_new}"-php-imap "${php2_new}"-php-enchant "${php2_new}"-php-pear "${php2_new}"-php-zlib "${php2_new}"-php-xmlrpc "${php2_new}"-php-devel \
    "${php2_new}"-php-tidy "${php2_new}"-php-opcache "${php2_new}"-php-cli "${php2_new}"-php-pecl-zip "${php2_new}"-php-dom "${php2_new}"-php-ssh2 "${php2_new}"-php-xmlreader "${php2_new}"-php-date "${php2_new}"-php-exif "${php2_new}"-php-filter "${php2_new}"-php-ftp \
    "${php2_new}"-php-hash "${php2_new}"-php-iconv "${php2_new}"-php-libxml "${php2_new}"-php-pecl-imagick "${php2_new}"-php-mysqlnd "${php2_new}"-php-openssl "${php2_new}"-php-pcre "${php2_new}"-php-posix "${php2_new}"-php-sockets "${php2_new}"-php-spl \
    "${php2_new}"-php-tokenizer "${php2_new}"-php-bz2 "${php2_new}"-php-pgsql "${php2_new}"-php-sqlite3 "${php2_new}"-php-fileinfo
}

install_php_2(){
    yum -y install "${php2_new}" "${php2_new}"-php-fpm "${php2_new}"-php-ldap "${php2_new}"-php-zip "${php2_new}"-php-embedded "${php2_new}"-php-cli "${php2_new}"-php-mysql "${php2_new}"-php-common "${php2_new}"-php-gd "${php2_new}"-php-xml "${php2_new}"-php-mbstring \
    "${php2_new}"-php-mcrypt "${php2_new}"-php-pdo "${php2_new}"-php-soap "${php2_new}"-php-json "${php2_new}"-php-simplexml "${php2_new}"-php-process "${php2_new}"-php-curl "${php2_new}"-php-bcmath "${php2_new}"-php-snmp "${php2_new}"-php-pspell "${php2_new}"-php-gmp \
    "${php2_new}"-php-intl "${php2_new}"-php-imap "${php2_new}"-php-enchant "${php2_new}"-php-pear "${php2_new}"-php-zlib "${php2_new}"-php-xmlrpc "${php2_new}"-php-devel \
    "${php2_new}"-php-tidy "${php2_new}"-php-opcache "${php2_new}"-php-cli "${php2_new}"-php-pecl-zip "${php2_new}"-php-dom "${php2_new}"-php-ssh2 "${php2_new}"-php-xmlreader "${php2_new}"-php-date "${php2_new}"-php-exif "${php2_new}"-php-filter "${php2_new}"-php-ftp \
    "${php2_new}"-php-hash "${php2_new}"-php-iconv "${php2_new}"-php-libxml "${php2_new}"-php-pecl-imagick "${php2_new}"-php-mysqlnd "${php2_new}"-php-openssl "${php2_new}"-php-pcre "${php2_new}"-php-posix "${php2_new}"-php-sockets "${php2_new}"-php-spl \
    "${php2_new}"-php-tokenizer "${php2_new}"-php-bz2 "${php2_new}"-php-pgsql "${php2_new}"-php-sqlite3 "${php2_new}"-php-fileinfo

    php2_release="yes"
    php2_ini_path="/etc/opt/remi/${php2_new}/php.d"
    php2_module_dir="/opt/remi/${php2_new}/root/usr/lib64/php/modules"

    if [[ ${php2_new} == "php56" ]]; then
        php2_ini_path="/opt/remi/${php2_new}/root/etc/php.d"
    fi
}

install_igbinary_2(){
    if [[ "${php2_new}" == "php56" ]]; then
        IGBINARY_VERSION="2.0.8"
    fi

    cd_dir /root && wget "${PECL_PHP_LINK}"/igbinary-"${IGBINARY_VERSION}".tgz
    tar -xvf igbinary-"${IGBINARY_VERSION}".tgz
    cd_dir /root/igbinary-${IGBINARY_VERSION}
    /opt/remi/"${php2_new}"/root/usr/bin/phpize && ./configure --with-php-config=/opt/remi/"${php2_new}"/root/usr/bin/php-config
    make && make install
    cd_dir /root && rm -rf igbinary-"${IGBINARY_VERSION}" igbinary-"${IGBINARY_VERSION}".tgz

    if [[ -f "${php2_module_dir}/igbinary.so" ]]; then
    	if [[ -f "${php2_ini_path}/40-igbinary.ini" ]]; then
			rm -rf "${php2_ini_path}"/40-igbinary.ini
		fi
        cat >> "${php2_ini_path}/40-igbinary.ini" << EOF
extension=igbinary.so
EOF
    fi
}

install_php_memcached_2(){
    if [[ "${php2_new}" == "php56" ]]; then
        PHP_MEMCACHED_VERSION="2.2.0"
    fi

    cd "${DIR}" && wget "${PECL_PHP_LINK}"/memcached-"${PHP_MEMCACHED_VERSION}".tgz
        tar -xvf memcached-"${PHP_MEMCACHED_VERSION}".tgz
        cd_dir /root/memcached-${PHP_MEMCACHED_VERSION}
        /opt/remi/"${php2_new}"/root/usr/bin/phpize && ./configure --enable-memcached-igbinary --with-php-config=/opt/remi/"${php2_new}"/root/usr/bin/php-config
        make && make install
        cd /root && rm -rf memcached-"${PHP_MEMCACHED_VERSION}".tgz memcached-"${PHP_MEMCACHED_VERSION}"

    if [[ -f "${php2_module_dir}/memcached.so" ]]; then
    	if [[ -f "${php2_ini_path}/50-memcached.ini" ]]; then
    		rm -rf "${php2_ini_path}"/50-memcached.ini
    	fi
        cat >> "${php2_ini_path}/50-memcached.ini" << EOF
extension=memcached.so
EOF
    fi
}

install_php_redis_2(){
    if [[ "${php2_new}" == "php56" ]]; then
        PHP_REDIS_VERSION="4.3.0"
    fi

    cd /root && wget "${PECL_PHP_LINK}"/redis-"${PHP_REDIS_VERSION}".tgz
    tar -xvf redis-"${PHP_REDIS_VERSION}".tgz
    cd_dir "/root/redis-${PHP_REDIS_VERSION}"
    /opt/remi/"${php2_new}"/root/usr/bin/phpize && ./configure --enable-redis-igbinary --with-php-config=/opt/remi/"${php2_new}"/root/usr/bin/php-config
    make && make install
    cd /root && rm -rf redis-"${PHP_REDIS_VERSION}".tgz redis-"${PHP_REDIS_VERSION}"

    if [[ -f "${php2_module_dir}/redis.so" ]]; then
    	if [[ -f "${php2_ini_path}/50-redis.ini" ]]; then
    		rm -rf "${php2_ini_path}"/50-redis.ini
    	fi
        cat >> "${php2_ini_path}/50-redis.ini" << EOF
extension=redis.so
EOF
    fi
}

php2_global_config(){
    php2_fpm_config_file="/etc/opt/remi/${php2_new}/php-fpm.conf"
    php2_fpm_config_path="/etc/opt/remi/${php2_new}/php-fpm.d"
    www2_config_file="/etc/opt/remi/${php2_new}/php-fpm.d/www.conf"

    if [[ ${php2_new} == "php56" ]]; then
        php2_fpm_config_file="/opt/remi/${php2_new}/root/etc/php-fpm.conf"
        php2_fpm_config_path="/opt/remi/php56/root/etc/php-fpm.d"
        www2_config_file="/opt/remi/${php2_new}/root/etc/php-fpm.d"
    fi

    if [[ -f "${php2_fpm_config_file}" ]]; then
        rm -rf "${php2_fpm_config_file}"
    fi

    if [[ ! -d "/opt/remi/${php2_new}/root/var/run/php-fpm" ]]; then
        mkdir -p /opt/remi/"${php2_new}"/root/var/run/php-fpm
    fi

    cat >> "${php2_fpm_config_file}" << EOphp_fpm_2_conf
;;;;;;;;;;;;;;;;;;;;;
; FPM Configuration ;
;;;;;;;;;;;;;;;;;;;;;

include=${php2_fpm_config_path}/*.conf

[global]
pid = /opt/remi/${php2_new}/root/var/run/php-fpm/php-fpm.pid
error_log = /opt/remi/${php2_new}/root/var/log/php-fpm/error.log
log_level = warning
emergency_restart_threshold = 10
emergency_restart_interval = 1m
process_control_timeout = 10s
daemonize = yes
EOphp_fpm_2_conf

    if [[ -f "${www2_config_file}" ]]; then
        rm -rf "${www2_config_file}"
    fi
cat >> "${www2_config_file}" << EOwww_2_conf
[www]
listen = /opt/remi/${php2_new}/root/var/run/php-fpm/php-fpm.sock;
listen.backlog = -1
listen.allowed_clients = 127.0.0.1
listen.owner = nginx
listen.group = nginx
listen.mode = 0660
user = nginx
group = nginx
pm = dynamic
pm.max_children = ${PM_MAX_CHILDREN}
pm.start_servers = ${PM_START_SERVERS}
pm.min_spare_servers =  ${PM_MIN_SPARE_SERVER}
pm.max_spare_servers = ${PM_MAX_SPARE_SERVER}
pm.max_requests = ${PM_MAX_REQUEST}
request_terminate_timeout = 300
rlimit_files = 65536
rlimit_core = 0
;slowlog = /opt/remi/${php2_new}/root/var/log/php-fpm/www-slow.log
chdir = /
php_admin_value[error_log] = /opt/remi/${php2_new}/root/var/log/php-fpm/www-error.log
php_admin_flag[log_errors] = on
php_value[session.save_handler] = files
php_value[session.save_path]    = /opt/remi/${php2_new}/root/var/lib/php/session
php_value[soap.wsdl_cache_dir]  = /opt/remi/${php2_new}/root/var/lib/php/wsdlcache
php_admin_value[disable_functions] = exec,system,passthru,shell_exec,dl,show_source,posix_kill,posix_mkfifo,posix_getpwuid,posix_setpgid,posix_setsid,posix_setuid,posix_setgid,posix_seteuid,posix_setegid,posix_uname
;php_admin_value[disable_functions] = exec,system,passthru,shell_exec,proc_close,proc_open,dl,popen,show_source,posix_kill,posix_mkfifo,posix_getpwuid,posix_setpgid,posix_setsid,posix_setuid,posix_setgid,posix_seteuid,posix_setegid,posix_uname
;php_admin_value[open_basedir] = ${DEFAULT_DIR_WEB}/:/tmp/:/var/tmp/:/dev/urandom:/usr/share/php/:/dev/shm:/var/lib/php/sessions/
security.limit_extensions = .php
EOwww_2_conf

    if [[ ! -d "/opt/remi/${php2_new}/root/var/lib/php/session" ]]; then
        mkdir -p /opt/remi/"${php2_new}"/root/var/lib/php/session
    fi
    if [[ ! -d "/opt/remi/${php2_new}/root/var/lib/php/wsdlcache" ]]; then
        mkdir -p /opt/remi/"${php2_new}"/root/var/lib/php/wsdlcache
    fi
    if [[ ! -d "/opt/remi/${php2_new}/root/var/log/php-fpm" ]]; then
        mkdir -p /opt/remi/"${php2_new}"/root/var/log/php-fpm
    fi
    chown -R nginx:nginx /opt/remi/"${php2_new}"/root/var/lib/php/session
    chown -R nginx:nginx /opt/remi/"${php2_new}"/root/var/lib/php/wsdlcache
    chown -R nginx:nginx /opt/remi/"${php2_new}"/root/var/log/php-fpm
    chmod 711 /opt/remi/"${php2_new}"/root/var/lib/php/session
    chmod 711 /opt/remi/"${php2_new}"/root/var/lib/php/wsdlcache
}

hostvn_custom_ini_2(){
	if [[ -f "${php2_ini_path}/00-hostvn-custom.ini" ]]; then
		rm -rf "${php2_ini_path}"/00-hostvn-custom.ini
	fi
    cat > "${php2_ini_path}/00-hostvn-custom.ini" <<EOhostvn_custom_ini
date.timezone = Asia/Ho_Chi_Minh
max_execution_time = 90
max_input_time = 90
short_open_tag = On
realpath_cache_size = ${PHP_REAL_PATH_LIMIT}
realpath_cache_ttl = ${PHP_REAL_PATH_TTL}
memory_limit = ${MAX_MEMORY}M
upload_max_filesize = ${MAX_MEMORY}M
post_max_size = ${MAX_MEMORY}M
expose_php = Off
display_errors = Off
mail.add_x_header = Off
max_input_nesting_level = 128
max_input_vars = ${MAX_INPUT_VARS}
mysqlnd.net_cmd_buffer_size = 16384
mysqlnd.collect_memory_statistics = Off
mysqlnd.mempool_default_size = 16000
always_populate_raw_post_data=-1
;disable_functions=exec,system,passthru,shell_exec,proc_close,proc_open,dl,popen,show_source,posix_kill,posix_mkfifo,posix_getpwuid,posix_setpgid,posix_setsid,posix_setuid,posix_setgid,posix_seteuid,posix_setegid,posix_uname
EOhostvn_custom_ini
}

php_opcache_2(){
    if [[ -f "${php2_ini_path}/10-opcache.ini" ]]; then
        rm -rf "${php2_ini_path}"/10-opcache.ini
    fi
    cat > "${php2_ini_path}/10-opcache.ini" << EOphp_opcache
zend_extension=opcache.so
opcache.enable=1
opcache.memory_consumption=${OPCACHE_MEM}
opcache.interned_strings_buffer=8
opcache.max_wasted_percentage=5
opcache.max_accelerated_files=65407
opcache.revalidate_freq=180
opcache.fast_shutdown=0
opcache.enable_cli=0
opcache.save_comments=1
opcache.enable_file_override=1
opcache.validate_timestamps=1
opcache.blacklist_filename=${php2_ini_path}/opcache-default.blacklist
EOphp_opcache

    cat > "${php2_ini_path}/opcache-default.blacklist" << EOopcache_blacklist
/home/*/public_html/wp-content/plugins/backwpup/*
/home/*/public_html/wp-content/plugins/duplicator/*
/home/*/public_html/wp-content/plugins/updraftplus/*
EOopcache_blacklist
}

write_info(){
    sed -i '/php2_version=/d' "${FILE_INFO}"
    echo "php2_version=${php2_new}" >> "${FILE_INFO}"
}

_run(){
    if [[ "${php2_release}" == "yes" ]]; then
        set_var
        select_php_ver
        check_duplicate_php

        if [[ -z "${ALERT}" ]]; then
            memory_calculation
            remove_old_php
            install_php_2
            install_igbinary_2
            install_php_memcached_2
            install_php_redis_2
            php2_global_config
            hostvn_custom_ini_2
            php_opcache_2
            systemctl restart "${php2_new}"-php-fpm
            systemctl enable "${php2_new}"-php-fpm
            write_info

            clear
            printf "${GREEN}Thay doi phien ban PHP thanh cong.${NC}\n"
        else
            clear
            printf "${ALERT}\n"
        fi
    else
        printf "${RED}PHP 2 chua duoc cai dat. Vui long cai dat PHP 2 truoc.${NC}\n"
    fi
}

ALERT=""
confirm
if [[ "${prompt_php2}" =~ ^([yY])$ ]]; then
    _run
else
    printf "${GREEN}Ban da huy thay doi phien ban PHP 2.${NC}\n"
fi
menu_php