#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

printf "${GREEN}======================${NC}\n"
printf "${GREEN}Chinh sua thong so php${NC}\n"
printf "${GREEN}======================${NC}\n"

printf "${RED}Luu y: Tat ca cac thong so deu da duoc toi uu theo thong so cua VPS.${NC}\n"
printf "${RED}Can suy nghi ky truoc khi thay doi bat ky thong so nao.${NC}\n"

set_variable(){
	ini_1="/etc/php.d/00-hostvn-custom.ini"
	ini_2="/etc/opt/remi/${php2_version}/php.d/00-hostvn-custom.ini"

	if [[ ${php2_version} == "php56" ]]; then
        ini_2="/opt/remi/${php2_version}/root/etc/php.d/00-hostvn-custom.ini"
    fi
}

select_parameter(){
    echo "Lua chon thong so muon thay đoi"
    PS3='Nhap lua chon cua ban (1-5): '
    options=("post_max_size" "upload_max_filesize" "memory_limit" "max_input_time" "max_execution_time")
    select opt in "${options[@]}"
    do
        case $opt in
            "post_max_size") parameter="post_max_size"; break;;
            "upload_max_filesize") parameter="upload_max_filesize"; break;;
            "memory_limit") parameter="memory_limit"; break;;
            "max_input_time") parameter="max_input_time"; break;;
            "max_execution_time") parameter="max_execution_time"; break;;
            *) printf "${RED}Ban nhap sai, vui long nhap lai.${NC}\n" ;;
        esac
    done
}

input_parameter(){
	read -r -p "Nhap vao thong so moi (Ex: 120): " num
}

remove_ini_bak(){
	if [[ -f "${ini_1}.bak" ]]; then
		rm -rf "${ini_1}".bak
	fi

	if [[ -f "${ini_2}.bak" ]]; then
		rm -rf "${ini_2}".bak
	fi
}

change_parameter(){
	if [[ "${parameter}" == "max_input_time" || "${parameter}" == "max_execution_time" ]]; then
		parameter_new=${num}
	else
		parameter_new=${num}M
	fi

	sed -i.bak "/${parameter}/d" ${ini_1}
	echo "${parameter} = ${parameter_new}" >> "${ini_1}"

	if [[ "${php2_release}" == "yes" ]]; then
		sed -i.bak "/${parameter}/d" "${ini_2}"
		echo "${parameter} = ${parameter_new}" >> "${ini_2}"
	fi
}

restart_php(){
	systemctl restart php-fpm
	if [[ "${php2_release}" == "yes" ]]; then
		systemctl restart "${php2_version}"-php-fpm
	fi
}

_run(){
	set_variable
	select_parameter
	input_parameter

	if valid_number "${num}"; then
	    remove_ini_bak
        change_parameter
        restart_php
        printf "${GREEN}Thay đoi thong so PHP thanh cong.${NC}\n"
    else
        printf "${RED}Gia tri ban nhap khong chinh xac.${NC}\n"
	fi
}

_run
sleep 2
menu_php