#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

printf "%s======================%s\n" "${GREEN}" "${NC}"
printf "%sChinh sua thong so php%s\n" "${GREEN}" "${NC}"
printf "%s======================%s\n" "${GREEN}" "${NC}"

printf "%s\n" "${RED}Luu y: Tat ca cac thong so deu da duoc toi uu theo thong so cua VPS.${NC}"
printf "%s\n" "${RED}Can suy nghi ky truoc khi thay doi bat ky thong so nao.${NC}"

set_variable(){
    ini_1="/etc/php.d/00-hostvn-custom.ini"
    ini_2="/etc/opt/remi/${php2_version}/php.d/00-hostvn-custom.ini"

    if [[ ${php2_version} == "php56" ]]; then
        ini_2="/opt/remi/${php2_version}/root/etc/php.d/00-hostvn-custom.ini"
    fi
}

select_parameter(){
    echo "Lua chon thong so muon thay đoi"
    PS3='Nhap lua chon cua ban (1-5): '
    options=("post_max_size" "upload_max_filesize" "memory_limit" "max_input_time" "max_execution_time" "Cancel")
    select opt in "${options[@]}"
    do
        case $opt in
            "post_max_size") parameter="post_max_size"; break;;
            "upload_max_filesize") parameter="upload_max_filesize"; break;;
            "memory_limit") parameter="memory_limit"; break;;
            "max_input_time") parameter="max_input_time"; break;;
            "max_execution_time") parameter="max_execution_time"; break;;
            "Cancel") parameter="0"; break;;
            *) printf "%s\n" "${RED}Ban nhap sai, vui long nhap lai.${NC}" ;;
        esac
    done
}

input_parameter(){
    while true
    do
        read -r -p "Nhap vao thong so moi (Ex: 120) [0 = Thoat]: " num
        echo
        if [[ "${num}" =~ ^[0-9]+$ ]]; then
            break
        else
            printf "%s\n"  "${RED}Gia tri ban nhap khong dung. Vui long nhap lai.${NC}"
        fi
    done
}

remove_ini_bak(){
    if [[ -f "${ini_1}.bak" ]]; then
        rm -rf "${ini_1}".bak
    fi

    if [[ -f "${ini_2}.bak" ]]; then
        rm -rf "${ini_2}".bak
    fi
}

change_parameter(){
    if [[ "${parameter}" == "max_input_time" || "${parameter}" == "max_execution_time" ]]; then
        parameter_new=${num}
    else
        parameter_new=${num}M
    fi

    sed -i.bak "/${parameter}/d" ${ini_1}
    echo "${parameter} = ${parameter_new}" >> "${ini_1}"

    if [[ "${php2_release}" == "yes" ]]; then
        sed -i.bak "/${parameter}/d" "${ini_2}"
        echo "${parameter} = ${parameter_new}" >> "${ini_2}"
    fi
}

restart_php(){
    systemctl restart php-fpm
    if [[ "${php2_release}" == "yes" ]]; then
        systemctl restart "${php2_version}"-php-fpm
    fi
}

_run(){
    set_variable
    select_parameter
    if [ "${parameter}" == "0" ]; then
        printf "%s\n" "${RED}Huy thay đoi thong so PHP.${NC}"
    else
        input_parameter

        if [ "${num}" == "0" ]; then
            printf "%s\n" "${RED}Huy thay đoi thong so PHP.${NC}"
        else
            remove_ini_bak
            change_parameter
            restart_php
            printf "%s\n" "${GREEN}Thay đoi thong so PHP thanh cong.${NC}"
        fi
    fi
}
parameter=""
num=""
_run
menu_php