#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
# Please don't copy copy under any circumstance for business reason! #
######################################################################

# shellcheck disable=SC2154

show_info(){
	printf "PHP default version     : %s\n" "$(rpm -qa php-fpm | cut -f3 -d'-')"
	if [[ "${php2_release}" == "yes" ]]; then
		printf "PHP 2 version           : %s\n" "${php2_version}"
	fi
	printf "MariaDB version         : %s\n" "$(mysql --version | cut -f6 -d' ' | cut -f1 -d'-')"
	printf "Nginx version           : %s\n"     "$(nginx -v 2>&1 | grep -o '[0-9.]*$'; echo)"
	echo ""
}

show_info
menu_vps