#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    script_v=$(curl -s "${UPDATE_LINK}"/version | grep "script_version=" | cut -f2 -d'=')
    current_v=$(grep -w "script_version" "${FILE_INFO}" | cut -f2 -d'=');
}

check_update(){
    if [[ "${script_v}" == "${current_v}" ]]; then
        ALERT=$(printf "%s\n" "${RED}Ban dang su dung phien ban moi nhat.${NC}")
    fi
}

confirm_update(){
    echo "Da phat hien phien ban moi."
    read -r -p "Ban co muon cap nhat ${AUTHOR} Script khong ? (y/n) " promt_update
}

update(){
    cd_dir "${BASH_DIR}"
    wget -q "${UPDATE_LINK}"/update.txt -O "${BASH_DIR}"/update &> /dev/null
    dos2unix update &> /dev/null
    sh update
    rm -rf update
    clear
    printf "%s\n" "${GREEN}Update ${AUTHOR} Script thanh cong.${NC}"
}

_run(){
    ALERT=""
    set_var
    check_update

    if [ -z "${ALERT}" ]; then
        confirm_update
        if [[ "${promt_update}" =~ ^([yY])$ ]]; then
            update
        else
            clear
            printf "%s\n" "${GREEN}Ban da huy update ${AUTHOR} Script${NC}"
        fi

    else
        clear
        printf "%s\n" "${ALERT}"
    fi
}

_run
menu_vps