#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
# Please don't copy copy under any circumstance for business reason! #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
	script_v=$(curl -s "${UPDATE_LINK}"/version | grep "script_version=" | cut -f2 -d'=')
	current_v=$(grep "script_version" "${FILE_INFO}" | cut -f2 -d'=');
}

check_update(){
	if [[ "${script_v}" == "${current_v}" ]]; then
		ALERT=$(printf "${RED}Ban dang su dung phien ban moi nhat.${NC}\n")
	fi
}

confirm_update(){
	echo "Da phat hien phien ban moi."
	read -r -p "Ban co muon cap nhat ${AUTHOR} Script khong ? (y/n) " promt_update
}

update(){
	cd_dir "${BASH_DIR}"
	wget -q "${UPDATE_LINK}"/update.txt -O "${BASH_DIR}"/update &> /dev/null
	dos2unix update &> /dev/null
	sh update
	rm -rf update
	clear
	printf "${GREEN}Update ${AUTHOR} Script thanh cong.${NC}\n"
}

_run(){
	set_var
	check_update

	if [ -z "${ALERT}" ]; then
		confirm_update
		if [[ "${promt_update}" =~ ^([yY])$ ]]; then
			update
		else
			clear
			printf "${GREEN}Ban da huy update ${AUTHOR} Script${NC}\n"
		fi

	else
		clear
		printf "${ALERT}\n"
	fi
}

_run
menu_vps