#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_variable(){
    #https://stackoverflow.com/a/6546314
    MemTotal=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
    MemAvailable=$(awk '/MemAvailable/ { print $2 }' /proc/meminfo)
    SwapTotal=$(awk '/SwapTotal/ {print $2}' /proc/meminfo)
    SwapFree=$(awk '/SwapFree/ {print $2}' /proc/meminfo)
}

show_info(){
    printf "Uptime          : %s\n" "$(uptime | xargs)"
    printf "CPU loading     : %s\n" "$(top -b -n1 | grep "Cpu(s)" | awk '{print $2 + $4}')%"
    printf "Ram             : %s\n" "$(bytes_for_humans "${MemTotal}") (Con trong: $(bytes_for_humans "${MemAvailable}"))"
    printf "Swap            : %s\n" "$(bytes_for_humans "${SwapTotal}") (Con trong: $(bytes_for_humans "${SwapFree}") )"
    printf "Disk da su dung : %s\n" "$(df -lh | awk '{if ($6 == "/") { print $5 }}' | head -1 | cut -d'%' -f1)%"
    echo ""
}

set_variable
show_info
sleep 2
menu_vps