#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

set_var(){
    nginx_status=$(pgrep nginx >/dev/null && printf "%s\n" "${GREEN}Hoat dong${NC}" || printf "%s\n" "${GREEN}Khong hoat dong${NC}")
    php_status=$(pgrep php-fpm >/dev/null && printf "%s\n" "${GREEN}Hoat dong${NC}" || printf "%s\n" "${GREEN}Khong hoat dong${NC}")
    mysql_status=$(pgrep mariadb >/dev/null && printf "%s\n" "${GREEN}Hoat dong${NC}" || printf "%s\n" "${GREEN}Khong hoat dong${NC}")
    ssh_status=$(pgrep ssh >/dev/null && printf "%s\n" "${GREEN}Hoat dong${NC}" || printf "%s\n" "${GREEN}Khong hoat dong${NC}")
    lfd_status=$(pgrep lfd >/dev/null && printf "%s\n" "${GREEN}Hoat dong${NC}" || printf "%s\n" "${GREEN}Khong hoat dong${NC}")
    pure_status=$(pgrep pure-ftpd >/dev/null && printf "%s\n" "${GREEN}Hoat dong${NC}" || printf "%s\n" "${GREEN}Khong hoat dong${NC}")
    memcached_status=$(pgrep memcached >/dev/null && printf "%s\n" "${GREEN}Hoat dong${NC}" || printf "%s\n" "${GREEN}Khong hoat dong${NC}")
    redis_status=$(pgrep redis >/dev/null && printf "%s\n" "${GREEN}Hoat dong${NC}" || printf "%s\n" "${GREEN}Khong hoat dong${NC}")
}

show_info(){
    printf "Nginx        : %s\n" "${nginx_status}"
    printf "Php-FPM      : %s\n" "${php_status}"
    printf "Mysql        : %s\n" "${mysql_status}"
    printf "SSH          : %s\n" "${ssh_status}"
    printf "LFD          : %s\n" "${lfd_status}"
    printf "Pure-ftpd    : %s\n" "${pure_status}"
    printf "Memcached    : %s\n" "${memcached_status}"
    printf "Redis        : %s\n" "${redis_status}"
}

_run(){
    set_var
    show_info
}

_run
sleep 2
menu_vps