#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

set_var(){
	nginx_status=$(pgrep -f nginx)
	php_status=$(pgrep -f php-fpm)
	mysql_status=$(pgrep -f mariadb)
	ssh_status=$(pgrep -f ssh)
	lfd_status=$(pgrep -f lfd)
	pure_status=$(pgrep -f pure-ftpd)
	memcached_status=$(pgrep -f memcached)
	redis_status=$(pgrep -f redis)
}

set_color(){
	if [[ -z "${nginx_status}" ]]; then
		nginx_status=$(printf "${RED}Khong hoat dong${NC}")
	else
		nginx_status=$(printf "${GREEN}Hoat dong${NC}")
	fi

	if [[ -z "${php_status}" ]]; then
		php_status=$(printf "${RED}Khong hoat dong${NC}")
	else
		php_status=$(printf "${GREEN}Hoat dong${NC}")
	fi

	if [[  -z "${mysql_status}" ]]; then
		mysql_status=$(printf "${RED}Khong hoat dong${NC}")
	else
		mysql_status=$(printf "${GREEN}Hoat dong${NC}")
	fi

	if [[  -z "${ssh_status}" ]]; then
		ssh_status=$(printf "${RED}Khong hoat dong${NC}")
	else
		ssh_status=$(printf "${GREEN}Hoat dong${NC}")
	fi

	if [[  -z "${lfd_status}" ]]; then
		lfd_status=$(printf "${RED}Khong hoat dong${NC}")
	else
		lfd_status=$(printf "${GREEN}Hoat dong${NC}")
	fi

	if [[  -z "${pure_status}" ]]; then
		pure_status=$(printf "${RED}Khong hoat dong${NC}")
	else
		pure_status=$(printf "${GREEN}Hoat dong${NC}")
	fi

	if [[ -z "${memcached_status}" ]]; then
		memcached_status=$(printf "${RED}Khong hoat dong${NC}")
	else
		memcached_status=$(printf "${GREEN}Hoat dong${NC}")
	fi

	if [[ -z "${redis_status}" ]]; then
		redis_status=$(printf "${RED}Khong hoat dong${NC}")
	else
		redis_status=$(printf "${GREEN}Hoat dong${NC}")
	fi
}

show_info(){
	printf "Nginx        : %s\n" "${nginx_status}"
	printf "Php-FPM      : %s\n" "${php_status}"
	printf "Mysql        : %s\n" "${mysql_status}"
	printf "SSH          : %s\n" "${ssh_status}"
	printf "LFD 		 : %s\n" "${lfd_status}"
	printf "Pure-ftpd    : %s\n" "${pure_status}"
	printf "Memcached    : %s\n" "${memcached_status}"
	printf "Redis        : %s\n" "${redis_status}"
}

_run(){
	set_var
	set_color
	show_info
}

_run
sleep 2
menu_vps