#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC2034

valid_number(){
    REGEX_NUMBER='^[0-9]+$'
    if [[ ${1} =~ ${REGEX_NUMBER} ]]; then
        return 0
    else
        return 1
    fi
}

valid_date(){
    if [[ ${1} =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
        return 0
    else
        return 1
    fi
}

check_service(){
    nginx_status="$(pgrep -f nginx)"
    phpfpm_status="$(pgrep -f php-fpm)"
    mariadb_status="$(pgrep -f mariadb)"

    if [[  -z "${nginx_status}" || -z "${phpfpm_status}" || -z "${mariadb_status}" ]]; then
        ALERT=$(
            printf "${RED}${ERROR_OCCURRED}${NC}\n"
            printf "${RED}${CHECK_SERVICES}{NC}\n"
            echo "-------------------------------------------------"
            printf "Nginx: %s\n" "${nginx_status}";
            printf "PHP-FPM: %s\n" "${phpfpm_status}";
            printf "MariaDB: %s\n" "${mariadb_status}";
            printf "Pure-ftp: %s\n" "${pureftpd_status}";
            echo "-------------------------------------------------"
        )
    fi
}

validate_domain(){
    if [[ ${1} =~ [A-Za-z0-9-]+(\.[A-Za-z0-9-]+)*(\.[A-Za-z]{2,}) ]]; then
        return 0
    else
        return 1
    fi
}

check_domain_exists(){
    if [[ -f "${USER_DIR}/.${1}.conf" || -f "${VHOST_DIR}/${1}.conf" ]]; then
        ALERT=$(
                    printf "${RED}${DOMAIN_EXISTS1}${NC}\n"
                    printf "${RED}${DOMAIN_EXISTS2}${NC}\n"
                )
    fi
}

if_domain_exists(){
    if [[ -f "${USER_DIR}/.${1}.conf" || -f "${VHOST_DIR}/${1}.conf" ]]; then
        return 0
    else
        return 1
    fi
}

validate_user(){
    if ! [[ ${1} =~ ^[_a-zA-Z][_a-zA-Z0-9]*$ ]]; then
        ALERT=$(printf "${RED}${WRONG_USER}${NC}\n")
    fi
}

if_user_exists(){
    RESULT_USER=$(grep -c "^${1}:" /etc/passwd)
    if [ "${RESULT_USER}" != 0 ]; then
        return 0
    else
        return 1
    fi
}

if_pureftpd_user_exists(){
    RESULT_FTP_USER=$(grep -c "${1}" "/etc/pure-ftpd/pureftpd.passwd")
    if [[ "${RESULT_FTP_USER}" != 0 ]]; then
        return 0
    else
        return 1
    fi
}

check_database(){
    RESULT_DB=$(mysqlshow "${1}" | grep -v Wildcard | grep -o "${1}")
    if [ "$RESULT_DB" == "${1}" ]; then
        ALERT=$(
                    printf "${RED}${DATABASE_EXISTS}${NC}\n"
                    printf "${RED}${DOMAIN_EXISTS2}${NC}\n"
                )
    fi
}

if_db_exists(){
    RESULT_DB=$(mysqlshow "${1}" | grep -v Wildcard | grep -o "${1}")
    if [ "$RESULT_DB" == "${1}" ]; then
        return 0
    else
        return 1
    fi
}

if_db_not_empty(){
    COUNT_TABLE=$(mysql -e "SELECT CASE COUNT(*) WHEN '0' THEN 'empty' ELSE 'not empty' END AS contents FROM information_schema.tables
                                WHERE table_type = 'BASE TABLE' AND table_schema = '${1}}';" | grep "empty")
    if [ "${COUNT_TABLE}" == "empty" ]; then
        return 0
    else
        return 1
    fi
}

check_mysql_user(){
    RESULT_MYSQL_USER="$(mysql -sse "SELECT EXISTS(SELECT 1 FROM mysql.user WHERE user = '${1}')")"
    if [ "${RESULT_MYSQL_USER}" = 1 ]; then
        ALERT=$(
                    printf "${RED}${MYSQL_USER_EXISTS}${NC}\n"
                    printf "${RED}${DOMAIN_EXISTS2}${NC}\n"
                )
    fi
}

if_mysql_user_exists(){
    RESULT_MYSQL_USER="$(mysql -sse "SELECT EXISTS(SELECT 1 FROM mysql.user WHERE user = '${1}')")"
    if [ "${RESULT_MYSQL_USER}" = 1 ]; then
        return 0
    else
        return 1
    fi
}

check_nginx_status(){
    nginx="$(pgrep -f nginx)"

    if [ -z "${nginx}" ]; then
        ALERT=$(printf "${RED}${NGINX_NO_WORK}${NC}\n")
    fi
}

check_a_record(){
    a_record=$(dig -4 +nocomments @8.8.8.8 +short A "${1}")

    if [[ "${a_record}" != "${IPADDRESS}" ]]; then
        ALERT=$(
            printf "${RED}${DNS_FAIL1}${NC}\n"
            printf "${RED}${DNS_FAIL2}${NC}\n"
        )
    fi
}

check_www_record(){
    www_record=$(dig -4 +nocomments @8.8.8.8 +short A www."${1}")

    if [[ "${www_record}" != "${IPADDRESS}" ]]; then
        return 1
    else
        return 0
    fi
}

check_le_exists(){
    if [ ! -d "/etc/letsencrypt/live/${1}" ]; then
        ALERT=$(printf "${RED}${LE_NO_EXISTS}${NC}\n")
    fi
}

check_is_wordpress(){
    if [ ! -d "/home/${1}/${2}/public_html/wp-content" ]; then
        ALERT=$(printf "${RED}${NO_WP}${NC}\n")
    fi
}

if_is_wordpress(){
    if [ -d "/home/${1}/${2}/public_html/wp-content" ]; then
        ALERT=$(
            printf "${RED}${IS_WP1}${NC}\n"
            printf "${RED}${IS_WP2}${NC}\n"
        )
    fi
}

check_backup_exists(){
    if [ ! -d "/home/backup/${1}/${2}" ]; then
        ALERT=$(printf "${RED}${NO_BACKUP}${NC}\n")
    fi
}

check_backup_empty(){
    #https://www.codexpedia.com/shell/check-if-a-directory-is-empty-or-not-in-shell-script/
    if [ "$(ls -A /home/backup/"${1}"/"${2}")" ]; then
        return 0
    else
        return 1
    fi
}

check_docroot_empty(){
    #https://www.codexpedia.com/shell/check-if-a-directory-is-empty-or-not-in-shell-script/
    if [ "$(ls -A /home/"${1}"/"${2}"/public_html)" ]; then
        return 0
    else
        return 1
    fi
}

check_wpconfig(){
    if [[ ! -f "/home/${1}/${2}/public_html/wp-config.php" ]]; then
        ALERT=$(printf "${RED}${WPCONFIG_NOT_EXISTS}${NC}")
    fi
}

service_exists() {
    local n=$1
    if [[ $(systemctl list-units --all -t service --full --no-legend "$n.service" | cut -f1 -d' ') == $n.service ]]; then
        return 0
    else
        return 1
    fi
}