#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

select_cron(){
    echo "Lua chon Cronjob muon xoa ?"
    PS3='Nhap lua chon cua ban (1-4): '
    options=("Cronjob Auto Renew Let's Encrypt" "Cronjob auto backup local" "Cronjob auto backup Google Drive" "Cancel" )
    select opt in "${options[@]}"
    do
        case $opt in
            "Cronjob Auto Renew Let's Encrypt") cron="certbot-auto renew"; break;;
            "Cronjob auto backup local") cron="backup_local"; break;;
            "Cronjob auto backup Google Drive") cron="backup_ggdrive"; break;;
            "Cancel") cron="0"; break;;
            *) printf "%s\n" "${RED}Ban nhap sai, vui long nhap lai.${NC}";;
        esac
    done
}

destroy_cronjob(){
    crontab -u root -l | grep -v "${cron}" | crontab -u root -
}

_run(){
    select_cron

    if [ "${cron}" == "0" ]; then
        printf "%s\n" "${RED}Huy xoa cronjob.${NC}"
    else
        destroy_cronjob
        clear
        printf "%s\n" "${GREEN}Xoa Cronjob thanh cong.${NC}"
        echo ""
    fi
}

cron=""
_run
menu_cronjob