#!/bin/bash

show_info(){
	printf "User phpMyAdmin              : admin\n"
	printf "Mat khau phpMyAdmin          : %s\n"  "${mysql_pwd}"
	printf "Link phpMyAdmin              : %s\n" "http://${IPADDRESS}:${admin_port}/phpmyadmin"
}

show_info
sleep 3
menu_account