#!/bin/bash

#################################################
# Auto Install & Optimize LEMP Stack on CentOS 7#
# Version: 1.0                                  #
# Author: Sanvv - HOSTVN Technical              #
#                                               #
# Please don't remove copyright. Thank!         #
#################################################

# shellcheck disable=SC2154

show_info(){
	printf "User phpMyAdmin              : admin\n"
	printf "Mat khau phpMyAdmin          : %s\n"  "${mysql_pwd}"
	printf "Link phpMyAdmin              : %s\n" "http://${IPADDRESS}:${admin_port}/phpmyadmin"
}

show_info
sleep 3
menu_account