#!/bin/bash

#################################################
# Auto Install & Optimize LEMP Stack on CentOS 7#
# Version: 1.0                                  #
# Author: Sanvv - HOSTVN Technical              #
#                                               #
# Please don't remove copyright. Thank!         #
#################################################

# shellcheck disable=SC2154

show_info(){
	printf "SSH PORT                     : %s\n" "${ssh_port}"
}

show_info
sleep 3
menu_account