#!/bin/bash

#################################################
# Auto Install & Optimize LEMP Stack on CentOS 7#
# Version: 1.0                                  #
# Author: Sanvv - HOSTVN Technical              #
#                                               #
# Please don't remove copyright. Thank!         #
#################################################

show_info(){
	printf "Admin user                   : admin\n"
	printf "Admin PORT                   : %s\n"  "${admin_port}"
	printf "Mat khau Admin tool          : %s\n"  "${admin_pwd}"
	printf "Opcache Dashboard            : %s\n" "http://${IPADDRESS}:${admin_port}/opcache"
	printf "php Memcached Admin          : %s\n" "http://${IPADDRESS}:${admin_port}/memcached"
	printf "php Reids Admin              : %s\n" "http://${IPADDRESS}:${admin_port}/redis"
	printf "Server Info                  : %s\n" "http://${IPADDRESS}:${admin_port}/serverinfo"
	printf "Link CSF GUI                 : %s\n" "https://${IPADDRESS}:${csf_port}"
}

show_info
sleep 3
menu_account