#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
	username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
	db_name=$(grep "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
	db_user=$(grep "db_user" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
	db_password=$(grep "db_password" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
	user_pass=$(grep "user_pass" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

show_info(){
	printf "1.  Domain                     : %s\n" "${domain}"
    printf "2.  DB_Name                    : %s\n" "${db_name}"
    printf "3.  DB_User                    : %s\n" "${db_user}"
    printf "4.  DB_Password                : %s\n" "${db_password}"
    printf "5.  Username (FTP)             : %s\n" "${username}"
    printf "6.  Password (FTP)             : %s\n" "$user_pass"
    printf "7.  FTP Host                   : %s\n" "${IPADDRESS}"
    printf "8.  FTP Port                   : 21\n"
    printf "9.  Public_html                : %s\n" "/home/${username}/${domain}/public_html"
}

run(){
	select_domain
	#validate_domain ${domain}

	if [[ -z "${ALERT}" ]]; then
		clear
		set_var
		show_info
	else
		printf "${ALERT}\n"
	fi
}

run
sleep 3
menu_account