#!/bin/bash

debug_(){
    LOG_FILE=/var/log/hostvn/$(date +%F)_create_ssl.log
    exec 5> "${LOG_FILE}"
    BASH_XTRACEFD="5"
    PS4='$LINENO: '
    set -x
}

debug_

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function
# shellcheck disable=SC1091
source /var/hostvn/menu/validate/rule

echo "-------------------"
echo "Cai dat SSL tra phi"
echo "-------------------"
echo

set_variable(){
    server_ip=$(ip route get 1 | awk '{print $NF;exit}')
    username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    php_mode=$(grep "php_mode" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    plugin_cache="$(grep "plugin_cache" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')"
    rewrite="include /etc/nginx/rewrite/${SOURCE}.conf;"
    cache="include /etc/nginx/extra/staticfiles.conf;"
    wp_secure=""
    brute=""
}

check_plugins_cache(){
    if [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/w3-total-cache" ]]; then
        cache="include /etc/nginx/wordpress/w3c.conf;"
        wp_secure="/etc/nginx/wordpress/wordpress_secure.conf"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/wp-fastest-cache" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/wpfc.conf;"
        wp_secure="/etc/nginx/wordpress/wordpress_secure.conf"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/wp-rocket" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/wprocket.conf;"
        wp_secure="/etc/nginx/wordpress/wordpress_secure.conf"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/wp-super-cache" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/wpsc.conf;"
        wp_secure="/etc/nginx/wordpress/wordpress_secure.conf"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/cache-enabler" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/enabler.conf;"
        wp_secure="/etc/nginx/wordpress/wordpress_secure.conf"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/swift-performance-lite" && "${plugin_cache}" == "swift1" ]]; then
        cache="include /etc/nginx/extra/staticfiles.conf;"
        wp_secure="/etc/nginx/wordpress/wordpress_secure.conf"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/swift-performance-lite" && "${plugin_cache}" == "swift2" ]]; then
        cache="include /etc/nginx/wordpress/swift2.conf;"
        wp_secure="/etc/nginx/wordpress/wordpress_secure.conf"
    else
        plugin_cache="other"
        wp_secure="/etc/nginx/wordpress/wordpress_secure.conf"
    fi
}

backup_vhost(){
    if [[ -f "/etc/nginx/backup_vhost/${domain}.conf.orig" ]]; then
        rm -rf /etc/nginx/backup_vhost/"${domain}".conf.orig
    fi

    mv "/etc/nginx/conf.d/$domain.conf" "/etc/nginx/backup_vhost/${domain}.conf.orig"
}

remove_letencrypt(){
	if [[ -d "/etc/letsencrypt/live/${domain}" ]]; then
		rm -rf /etc/letsencrypt/live/${domain}
	fi
}

create_crt(){
    echo "De lưu file hay bam CTRL + X va nhan ENTER sau đo bam tiep CTRL + O"
    echo "Dang mo trinh soan thao ...."
    sleep 3
    if [[ ! -d "/etc/nginx/ssl/${domain}" ]]; then
        mkdir -p /etc/nginx/ssl/"${domain}"
    fi
    nano /etc/nginx/ssl/"${domain}"/fullchain.pem
}

create_private_key(){
	echo "De lưu file hay bam CTRL + X va nhan ENTER sau đo bam tiep CTRL + O"
    echo "Dang mo trinh soan thao ...."
    sleep 3
    if [[ ! -d "/etc/nginx/ssl/${domain}" ]]; then
        mkdir -p /etc/nginx/ssl/"${domain}"
    fi
    nano /etc/nginx/ssl/"${domain}"/privkey.pem
}

create_ssl_vhost(){
    backup_vhost
    set_rewrite
    fastcgi

    if [[ "${SOURCE}" == "wordpress" ]]; then
        check_plugins_cache
        brute_force_wp
    fi

    cat >> "${VHOST_DIR}/${domain}.conf" << END
server {
    listen 80;
    #listen [::]:80;
    server_name ${domain} www.${domain};

    root /home/${username}/${domain}/public_html/;
    if (\$http_x_forwarded_proto != 'https') {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name ${domain} www.${domain};

    access_log off;
    #access_log /home/${username}/${domain}/logs/access.log;
    log_not_found off;
    #error_log off;
    error_log /home/${username}/${domain}/logs/error.log;

    root /home/${username}/${domain}/public_html/;
    index index.php index.html index.htm;

    ${rewrite}
    ${cache}

    ssl_certificate         /etc/nginx/ssl/"${domain}"/fullchain.pem;
    ssl_certificate_key     /etc/nginx/ssl/"${domain}"/privkey.pem;

    location ~ \.php\$
    {
        try_files \$uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)\$;
        fastcgi_index index.php;
        include /etc/nginx/fastcgi_params;
        include /etc/nginx/extra/nginx_limits.conf;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        if (-f \$request_filename)
        {
            ${fastcgi_pass}
        }
    }

    ${brute}
    ${wp_secure}
    include /etc/nginx/extra/security.conf;
}
END
}

restart_nginx(){
    systemctl restart nginx.service
}

run(){
    check_nginx_status
    select_domain
    check_domain

    if [[ -z "${ALERT}" ]]; then
        select_source

        if [[ "${SOURCE}" == "wordpress" ]]; then
            plugin_cache
        fi

        set_variable
        remove_letencrypt
        create_crt
        create_private_key
        create_ssl_vhost
        restart_nginx
        echo ""
        printf "${GREEN}Cau hinh SSL thanh cong.${NC}\n"
    else
        printf "${ALERT}"
    fi
}

run
sleep 2
menu_ssl