#!/bin/bash

#################################################
# Auto Install & Optimize LEMP Stack on CentOS 7#
# Version: 1.0                                  #
# Author: Sanvv - HOSTVN Technical              #
#                                               #
# Please don't remove copyright. Thank!         #
#################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

printf "${GREEN}-------------------${NC}\n"
printf "${GREEN}Cai dat SSL tra phi${NC}\n"
printf "${GREEN}-------------------${NC}\n"
echo

set_variable(){
    username=$(grep "username" "${USER_DIR}/.${domain:?}.conf" | cut -f2 -d'=')
    plugin_cache="$(grep "plugin_cache" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')"
    rewrite="include /etc/nginx/rewrite/${SOURCE}.conf;"
    cache="include /etc/nginx/extra/staticfiles.conf;"
    include_seo=""
    wp_secure=""
    brute=""
}

check_plugins_cache(){
    if [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/w3-total-cache" ]]; then
        cache="include /etc/nginx/wordpress/w3c.conf;"
        wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/wp-fastest-cache" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/wpfc.conf;"
        wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/wp-rocket" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/wprocket.conf;"
        wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/wp-super-cache" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/wpsc.conf;"
        wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/cache-enabler" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/enabler.conf;"
        wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/swift-performance-lite" && "${plugin_cache}" == "swift1" ]]; then
        cache="include /etc/nginx/extra/staticfiles.conf;"
        wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/swift-performance-lite" && "${plugin_cache}" == "swift2" ]]; then
        cache="include /etc/nginx/wordpress/swift2.conf;"
        wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
    else
        plugin_cache="other"
        wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
    fi
}

backup_vhost(){
    if [[ -f "/etc/nginx/backup_vhost/${domain}.conf.orig" ]]; then
        rm -rf /etc/nginx/backup_vhost/"${domain}".conf.orig
    fi

    mv "/etc/nginx/conf.d/$domain.conf" "/etc/nginx/backup_vhost/${domain}.conf.orig"
}

remove_letencrypt(){
	certbot-auto revoke --cert-path /etc/letsencrypt/live/"${domain}"/cert.pem
    certbot-auto delete --cert-name "${domain}"
}

create_crt(){
    echo "De lưu file hay bam CTRL + X va nhan ENTER sau đo bam tiep CTRL + O"
    echo "Dang mo trinh soan thao ...."
    sleep 3
    if [[ ! -d "/etc/nginx/ssl/${domain}" ]]; then
        mkdir -p /etc/nginx/ssl/"${domain}"
    fi
    nano /etc/nginx/ssl/"${domain}"/fullchain.pem
}

create_private_key(){
	echo "De lưu file hay bam CTRL + X va nhan ENTER sau đo bam tiep CTRL + O"
    echo "Dang mo trinh soan thao ...."
    sleep 3
    if [[ ! -d "/etc/nginx/ssl/${domain}" ]]; then
        mkdir -p /etc/nginx/ssl/"${domain}"
    fi
    nano /etc/nginx/ssl/"${domain}"/privkey.pem
}

set_docroot(){
    if [[ "${SOURCE}" == "laravel" ]]; then
        root="root /home/${username}/${domain}/public_html/public;"
    else
        root="root /home/${username}/${domain}/public_html;"
    fi
}

create_ssl_vhost(){
    backup_vhost
    set_rewrite
    fastcgi
    set_doc_root

    if [[ "${SOURCE}" == "wordpress" ]]; then
        check_plugins_cache
        brute_force_wp
        if [[ "${plugins_seo:?}" == "yoast_seo" ]]; then
            include_seo="include /etc/nginx/wordpress/yoast_seo.conf;"
            sed -i '/plugins_seo=/d' "${USER_DIR}"/."${domain}".conf
            echo "plugins_seo=yoast_seo" >> "${USER_DIR}"/."${domain}".conf
        elif [[ "${plugins_seo}" == "rank_math_seo" ]]; then
            include_seo="include /etc/nginx/wordpress/rank_math_seo.conf;"
            sed -i '/plugins_seo=/d' "${USER_DIR}"/."${domain}".conf
            echo "plugins_seo=rank_math_seo" >> "${USER_DIR}"/."${domain}".conf
        else
            sed -i '/plugins_seo=/d' "${USER_DIR}"/."${domain}".conf
            echo "plugins_seo=" >> "${USER_DIR}"/."${domain}".conf
        fi
    fi

    cat >> "${VHOST_DIR}/${domain}.conf" << END
server {
    listen 80;
    #listen [::]:80;
    server_name ${domain} www.${domain};

    ${root};
    if (\$http_x_forwarded_proto != 'https') {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    server_name ${domain} www.${domain};

    access_log off;
    #access_log /home/${username}/${domain}/logs/access.log;
    log_not_found off;
    #error_log off;
    error_log /home/${username}/${domain}/logs/error.log;

    ${root};
    index index.php index.html index.htm;

    ${rewrite}
    ${cache}

    ssl_certificate         /etc/nginx/ssl/"${domain}"/fullchain.pem;
    ssl_certificate_key     /etc/nginx/ssl/"${domain}"/privkey.pem;

    location ~ \.php\$
    {
        try_files \$uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)\$;
        fastcgi_index index.php;
        include /etc/nginx/fastcgi_params;
        include /etc/nginx/extra/nginx_limits.conf;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        if (-f \$request_filename)
        {
            ${fastcgi_pass:?}
        }
    }

    ${brute}
    ${wp_secure}
    ${include_seo}
    include /etc/nginx/extra/security.conf;
}
END
}

restart_nginx(){
    systemctl restart nginx.service
}

run(){
    check_nginx_status
    select_domain

    if [ -z "${ALERT}" ]; then
        select_source
        set_variable

        if [ "${SOURCE}" == "wordpress" ]; then
            clear
            select_plugin_seo
        fi

        remove_letencrypt
        create_crt
        create_private_key
        create_ssl_vhost
        restart_nginx
        clear
        printf "${GREEN}Cau hinh SSL thanh cong.${NC}\n"
    else
        clear
        printf "${ALERT}\n"
    fi
}

run
sleep 2
menu_ssl