#!/bin/bash

debug_(){
    LOG_FILE=/var/log/hostvn/$(date +%d-%m-%Y)_remove_ssl.log
    exec 5> "${LOG_FILE}"
    BASH_XTRACEFD="5"
    PS4='$LINENO: '
    set -x
}

debug_

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

printf "${GREEN}-----------------${NC}\n"
printf "${GREEN}Go bo SSL tra phi${NC}\n"
printf "${GREEN}-----------------${NC}\n"
echo

set_variable(){
    server_ip=$(ip route get 1 | awk '{print $NF;exit}')
    username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    plugin_cache="$(grep "plugin_cache" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')"
    rewrite="include /etc/nginx/rewrite/${SOURCE}.conf;"
    cache="include /etc/nginx/extra/staticfiles.conf;"
    include_seo=""
    wp_secure=""
    brute=""
}

check_plugins_cache(){
    if [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/w3-total-cache" ]]; then
        cache="include /etc/nginx/wordpress/w3c.conf;"
        wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/wp-fastest-cache" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/wpfc.conf;"
        wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/wp-rocket" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/wprocket.conf;"
        wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/wp-super-cache" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/wpsc.conf;"
        wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/cache-enabler" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/enabler.conf;"
        wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/swift-performance-lite" && "${plugin_cache}" == "swift1" ]]; then
        cache="include /etc/nginx/extra/staticfiles.conf;"
        wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/swift-performance-lite" && "${plugin_cache}" == "swift2" ]]; then
        cache="include /etc/nginx/wordpress/swift2.conf;"
        wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
    else
        plugin_cache="other"
        wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
    fi
}

backup_vhost(){
    if [[ -f "/etc/nginx/backup_vhost/${domain}.conf.orig" ]]; then
        rm -rf /etc/nginx/backup_vhost/"${domain}".conf.orig
    fi

    mv "/etc/nginx/conf.d/$domain.conf" "/etc/nginx/backup_vhost/${domain}.conf.orig"
}

set_docroot(){
    if [[ "${SOURCE}" == "laravel" ]]; then
        root="root /home/${username}/${domain}/public_html/public;"
    else
        root="root /home/${username}/${domain}/public_html;"
    fi
}

create_vhost(){
    backup_vhost
    set_rewrite
    fastcgi
    set_docroot

    if [ "${SOURCE}" == "wordpress" ]; then
        check_plugins_cache
        brute_force_wp

        if [[ "${plugins_seo}" == "yoast_seo" ]]; then
            include_seo="include /etc/nginx/wordpress/yoast_seo.conf;"
            sed -i '/plugins_seo=/d' ${USER_DIR}/.${domain}.conf
            echo "plugins_seo=yoast_seo" >> ${USER_DIR}/.${domain}.conf
        elif [[ "${plugins_seo}" == "rank_math_seo" ]]; then
            include_seo="include /etc/nginx/wordpress/rank_math_seo.conf;"
            sed -i '/plugins_seo=/d' ${USER_DIR}/.${domain}.conf
            echo "plugins_seo=rank_math_seo" >> ${USER_DIR}/.${domain}.conf
        else
            sed -i '/plugins_seo=/d' ${USER_DIR}/.${domain}.conf
            echo "plugins_seo=" >> ${USER_DIR}/.${domain}.conf
        fi
    fi

    cat >> "${VHOST_DIR}/${domain}.conf" << END
server {
    listen 80;
    server_name ${domain} www.${domain};

    #access_log off;
    #access_log /home/${username}/${domain}/logs/access.log;
    #error_log off;
    error_log /home/${username}/${domain}/logs/error.log;
    ${root}
    index index.php index.html index.htm;

    ${rewrite}
    ${cache}

    location ~ \.php\$ {
        try_files \$uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)\$;
        fastcgi_index index.php;
        include /etc/nginx/fastcgi_params;
        include /etc/nginx/extra/nginx_limits.conf;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        if (-f \$request_filename)
        {
            ${fastcgi_pass}
        }
    }

    ${brute}
    ${wp_secure}
    ${include_seo}
    include /etc/nginx/extra/security.conf;
}
END
}

restart_nginx(){
    systemctl restart nginx.service
}

run(){
    check_nginx_status
    select_domain
    #validate_domain ${domain}

    if [ -z "${ALERT}" ]; then
        select_source
        set_variable

        if [ "${SOURCE}" == "wordpress" ]; then
            select_plugin_seo
        fi

        create_vhost
        restart_nginx
        clear
        printf "${GREEN}Go bo SSL thanh cong.${NC}\n"
    else
        clear
        printf "${ALERT}\n"
    fi
}

run
sleep 2
menu_ssl