#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC2034
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

printf "%s=================%s\n" "${GREEN}" "${NC}"
printf "%sGo bo SSL tra phi%s\n" "${GREEN}" "${NC}"
printf "%s=================%s\n" "${GREEN}" "${NC}"
echo

edit_vhost(){
    cat >> "${VHOST_DIR}/${domain}.conf" << END
upstream php-${user} {
    server ${fastcgi_pass}
}

server {
    listen 80;
    server_name ${domain} www.${domain};

    #access_log off;
    #access_log /home/${user}/${domain}/logs/access.log;
    #error_log off;
    error_log /home/${user}/${domain}/logs/error.log;
    ${root}
    index index.php index.html index.htm;

    ${rewrite}

    location ~ \.php\$ {
        try_files \$uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)\$;
        fastcgi_index index.php;
        include /etc/nginx/fastcgi_params;
        include /etc/nginx/extra/nginx_limits.conf;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        if (-f \$request_filename)
        {
            fastcgi_pass php-${user};
        }
    }
    ${brute}
    include /etc/nginx/extra/staticfiles.conf;
    include /etc/nginx/extra/security.conf;
    ${wp_secure}
    ${xmlrpc}
}
END
}

edit_vhost_nodejs(){
    cat >> "${VHOST_DIR}/${domain}.conf" << END
server {
    listen 80;
    #listen [::]:80;
    server_name ${domain} www.${domain};

    #access_log off;
    #access_log /home/${user}/${domain}/logs/access.log;
    #error_log off;
    error_log /home/${user}/${domain}/logs/error.log;
    root /home/${user}/${domain}/public_html;
    #index index.php index.html index.htm;

    location / {
        proxy_pass http://127.0.0.1:${proxy_port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    include /etc/nginx/extra/staticfiles.conf;
    include /etc/nginx/extra/security.conf;
}
END
}

_run(){
    check_nginx_status

    if [ -z "${ALERT}" ]; then
        user=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
        php_mode="$(grep "php_mode" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')"
        select_source

        doc_root "${SOURCE}" "${user}" "${domain}"
        if [[ "${SOURCE}" == "wordpress" ]]; then
            wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
            xmlrpc="include /etc/nginx/wordpress/disable_xmlrpc.conf;"
            brute_force_wp "${user}"
        fi
        rm -rf /etc/nginx/conf.d/"${domain}".conf

        set_rewrite
        fastcgi

        if [ "${SOURCE}" == "nodejs" ]; then
            while true
            do
                read -r -p "Nhap Port Nodejs: " proxy_port
                if valid_number "${proxy_port}"; then
                    break
                else
                    clear
                    printf "%s\n" "${RED}Port khong chinh xac, vui long nhap lai.${NC}"
                fi
            done

            edit_vhost_nodejs
        else
            edit_vhost
        fi

        if nginx -t; then
            systemctl reload nginx
            clear
            printf "%sGo bo SSL thanh cong.%s\n" "${GREEN}" "${NC}"
            if [[ "${SOURCE}" == "wordpress" ]]; then
                printf "%s\n" "${GREEN}Luu y: Ban can cau hinh lai Plugins cache va Plugins Seo tai menu 7-7${NC}"
            fi
            echo ""
        else
            printf "%s\n" "${RED}Cau hinh Nginx khong chinh xac. Vui long kiem tra lai${NC}"
        fi

    else
        clear
        printf "%s\n" "${ALERT}"
    fi
}

ALERT=""
domain=""
select_domain

if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
else
    if [ -z "${ALERT}" ]; then
        _run
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
fi

menu_sslpaid