#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

set_var(){
    user=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
    rewrite="include /etc/nginx/rewrite/wordpress.conf;"
    plugin_cache="other"
}

browser_cache(){
    if [[ "${plugins_cache}" == "w3c" ]]; then
        plugin_cache="w3c"
        set_cache="include /etc/nginx/wordpress/w3c.conf;"
    elif [[ "${plugins_cache}" == "wpfc" ]]; then
        plugin_cache="wpfc"
        set_cache="include /etc/nginx/wordpress/wpfc.conf;"
        rewrite=""
    elif [[ "${plugins_cache}" == "wprocket" ]]; then
        plugin_cache="wprocket"
        set_cache="include /etc/nginx/rocket-nginx/default.conf;"
    elif [[ "${plugins_cache}" == "wpsc" ]]; then
        plugin_cache="wpsc"
        set_cache="include /etc/nginx/wordpress/wpsc.conf;"
        rewrite=""
    elif [[ "${plugins_cache}" == "enabler" ]]; then
        plugin_cache="enabler"
        set_cache="include /etc/nginx/wordpress/enabler.conf;"
        rewrite=""
    elif [[ "${plugins_cache}" == "swift1" ]]; then
        plugin_cache="swift1"
        set_cache="include /etc/nginx/extra/staticfiles.conf;"
    elif [[ "${plugins_cache}" == "swift2" ]]; then
        plugin_cache="swift2"
        set_cache="include /etc/nginx/wordpress/swift2.conf;"
    else
        plugin_cache="other"
        set_cache="include /etc/nginx/extra/staticfiles.conf;"
    fi
}

check_brute(){
    check_brute=$(grep -w "limit_req" "${VHOST_DIR}/${domain}.conf");
    if [ -z "${check_brute}" ]; then
        brute="location = /wp-login.php {
            limit_req zone=two burst=1 nodelay;
            include /etc/nginx/fastcgi_params;
            fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
            fastcgi_pass php-${user};
        }"
        sed -i "/index.html/a ${brute}" "${VHOST_DIR}"/"${domain}".conf
    fi
}

action(){
    if [[ "${plugin_cache}" != "other" ]]; then
        sed -i "/index.html/a ${set_cache}" "${VHOST_DIR}"/"${domain}".conf
    fi

    if [[ "${plugin_cache}" != "other" && "${plugin_cache}" != "wprocket" ]]; then
        sed -i '/staticfiles.conf/d' "${VHOST_DIR}"/"${domain}".conf
    fi

    if [ -z "${rewrite}" ]; then
        sed -i '/wordpress.conf/d' "${VHOST_DIR}"/"${domain}".conf
        sed -i '/default.conf/d' "${VHOST_DIR}"/"${domain}".conf
    else
        rewrite=$(grep -rnw "${VHOST_DIR}"/"${domain}".conf -e "wordpress.conf")
        if [ -z "${rewrite}" ]; then
            sed -i "/index.html/a include /etc/nginx/rewrite/wordpress.conf;" "${VHOST_DIR}"/"${domain}".conf
        fi
    fi

    if [[ "${plugin_cache}" == "wprocket" ]]; then
        if [ ! -f "${WORDPRESS_CRON_DIR}/${domain}" ]; then
            touch "${WORDPRESS_CRON_DIR}"/"${domain}"
        fi
        string=$(grep -rnw "/home/${user}/${domain}/public_html/wp-config.php" -e "DISABLE_WP_CRON")
        if [ -z "${string}" ]; then
            sed -i "/WP_DEBUG/a define('DISABLE_WP_CRON', true);" /home/"${user}"/"${domain}"/public_html/wp-config.php
        fi
        cron_exists=$(crontab -l | grep -w 'wpcron.sh')
        if [ -z "${cron_exists}" ]; then
            crontab -l > wpcron
            echo "* * * * * /var/hostvn/menu/cronjob/wpcron.sh >/dev/null 2>&1" >> wpcron
            crontab wpcron
            rm -rf wpcron
        fi
    fi
    check_brute
    sed -i '/plugin_cache=/d' "${USER_DIR}"/."${domain}".conf
    echo "plugin_cache=${plugin_cache}" >> "${USER_DIR}"/."${domain}".conf
}

_run(){
    select_plugin_cache
    set_var
    cache_array=("w3c" "wpfc" "wprocket" "wpsc" "enabler" "swift1" "swift2")

    for entry in "${cache_array[@]}"; do
        check_exists=$(grep -rnw "${VHOST_DIR}/${domain}.conf" -e "${entry}")
        if [[ -n "${check_exists}" ]]; then
            if [ "${entry}" == "${plugin_cache}" ]; then
                ALERT=$(printf "%s\n" "${RED}Ban da cau hinh plugins cache ${entry} roi.${NC}")
            else
                ALERT=$(printf "%s\n" "${RED}Ban hien dang cau hinh plugins cache ${entry}. Vui long xoa cau hinh cu truoc.${NC}")
            fi
            break
        fi
    done

    if [[ ! -d "/home/${user}/${domain}/public_html/wp-content" ]]; then
        ALERT=$(printf "%s\n" "${RED}Website khong su dung WordPress.${NC}")
    fi

    if [[ "${plugin_cache}" == "wprocket" && ! -f "/home/${user}/${domain}/public_html/wp-config.php" ]]; then
        ALERT=$(printf "%s\n" "${RED}File wp-config.php khong ton tai.${NC}")
    fi

    if [[ -z "${ALERT}" ]]; then
        browser_cache
        action
        if [[ "${plugins_cache}" == "wprocket" && ! -d "/etc/nginx/rocket-nginx" ]]; then
            cd_dir /etc/nginx
            git clone https://github.com/satellitewp/rocket-nginx.git
            cd_dir /etc/nginx/rocket-nginx
            cp rocket-nginx.ini.disabled rocket-nginx.ini
            php rocket-parser.php
        fi

        if [[ "${plugins_cache}" == "wprocket" && ! -f "/etc/nginx/rocket-nginx/default.conf" ]]; then
            cd_dir /etc/nginx/rocket-nginx
            php rocket-parser.php
        fi

        if nginx -t; then
            systemctl restart nginx
            systemctl restart php-fpm.service
            if [ "${php2_release}" == "yes" ]; then
                systemctl restart "${php2_version}"-php-fpm
            fi
            clear
            printf "%s\n" "${GREEN}Cau hinh Nginx voi plugin cache ${plugin_cache} thanh cong.${NC}"
        else
            printf "%s\n" "${RED}Cau hinh Nginx khong chinh xac. Vui long kiem tra lai${NC}"
        fi
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
}

ALERT=""
domain=""
plugins_cache=""
set_cache=""
string=""
select_domain
if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
else
    if [ -z "${ALERT}" ]; then
        _run
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
fi
wp_plugin_cache