#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s=========================================%s\n" "${GREEN}" "${NC}"
printf "%s            Chuc nang nang cao           %s\n" "${GREEN}" "${NC}"
printf "%s=========================================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Bat/Tat Yoast Seo config%s\n" "${GREEN}" "${NC}"
    printf "%s2. Bat/Tat Rank Math Seo config%s\n" "${GREEN}" "${NC}"
    printf "%s3. Cau hinh Nginx voi plugin cache%s\n" "${GREEN}" "${NC}"
    printf "%s4. Them cache key tranh trung lap noi dung%s\n" "${GREEN}" "${NC}"
    printf "%s5. Bat/Tat Debug mode%s\n" "${GREEN}" "${NC}"
    printf "%s6. Bat/Tat che do bao tri (Maintenance mode)%s\n" "${GREEN}" "${NC}"
    printf "%s7. Bat/Tat disable xmlrpc%s\n" "${GREEN}" "${NC}"
    printf "%s8. Bat/Tat WP-Cron%s\n" "${GREEN}" "${NC}"
    printf "%s9. Toi uu anh%s\n" "${GREEN}" "${NC}"
    printf "%s ========================================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; wp_yoast_seo ;;
        2) clear; wp_rank_math_seo ;;
        3) clear; wp_plugin_cache ;;
        4) clear; wp_cache_key ;;
        5) clear; wp_debug ;;
        6) clear; wp_maintenance ;;
        7) clear; wp_xmlrpc ;;
        8) clear; wp_cron ;;
        9) clear; wp_optimize_img ;;
        0) clear; menu_wp ;;
        *) clear; printf "%s\n"  "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done