#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
	username=${domain//[-._]/}
}

browser_cache(){
	rewrite="include /etc/nginx/rewrite/wordpress.conf;"
	plugin_cache="other"
    if [[ "${plugins_cache}" == "w3c" ]]; then
        plugin_cache="w3c"
        set_cache="include /etc/nginx/wordpress/w3c.conf;"
    elif [[ "${plugins_cache}" == "wpfc" ]]; then
        plugin_cache="wpfc"
        set_cache="include /etc/nginx/wordpress/wpfc.conf;"
        rewrite=""
    elif [[ "${plugins_cache}" == "wprocket" ]]; then
        plugin_cache="wprocket"
        set_cache="include /etc/nginx/rocket-nginx/default.conf;"
    elif [[ "${plugins_cache}" == "wpsc" ]]; then
        plugin_cache="wpsc"
        set_cache="include /etc/nginx/wordpress/wpsc.conf;"
        rewrite=""
    elif [[ "${plugins_cache}" == "enabler" ]]; then
        plugin_cache="enabler"
        set_cache="include /etc/nginx/wordpress/enabler.conf;"
        rewrite=""
    elif [[ "${plugins_cache}" == "swift1" ]]; then
        plugin_cache="swift1"
        set_cache="include /etc/nginx/extra/staticfiles.conf;"
    elif [[ "${plugins_cache}" == "swift2" ]]; then
        plugin_cache="swift2"
        set_cache="include /etc/nginx/wordpress/swift2.conf;"
    else
        plugin_cache="other"
        set_cache="include /etc/nginx/extra/staticfiles.conf;"
    fi
}

action(){
    browser_cache
    if [[ "${plugin_cache}" != "other" ]]; then
        sed -i "s|include /etc/nginx/extra/staticfiles.conf;|${set_cache}|g" "${VHOST_DIR}"/"${domain}".conf
    fi
    if [[ -z "${rewrite}" ]]; then
        sed -i '/wordpress.conf/d' "${VHOST_DIR}"/"${domain}".conf
    fi
}

_run(){
    select_plugin_cache
    set_var
    cache_array=("w3c" "wpfc" "wprocket" "wpsc" "enabler" "swift1" "swift2")

    for entry in "${cache_array[@]}"; do
        check_exists=$(grep -rnw "${VHOST_DIR}/${domain}.conf" -e "${entry}")
        if [[ -n "${check_exists}" ]]; then
            if [ "${entry}" == "${plugin_cache}" ]; then
                ALERT=$(printf "${RED}Ban da cau hinh plugins cache ${entry} roi.${NC}\n")
            else
                ALERT=$(printf "${RED}Ban hien dang cau hinh plugins cache ${entry}. Vui long xoa cau hinh cu truoc.${NC}\n")
            fi
            break
        fi
    done

    if [[ ! -d "/home/${username}/${domain}/public_html/wp-content" ]]; then
        ALERT=$(printf "${RED}Website khong su dung WordPress.${NC}\n")
    fi

    if [[ -z "${ALERT}" ]]; then
        action
        if [[ "${plugins_cache}" == "wprocket" && ! -d "/etc/nginx/rocket-nginx" ]]; then
            cd_dir /etc/nginx
            git clone https://github.com/satellitewp/rocket-nginx.git
            cd_dir /etc/nginx/rocket-nginx
            cp rocket-nginx.ini.disabled rocket-nginx.ini
            php rocket-parser.php
        fi

        if [[ "${plugins_cache}" == "wprocket" && ! -f "/etc/nginx/rocket-nginx/default.conf" ]]; then
            cd_dir /etc/nginx/rocket-nginx
            php rocket-parser.php
        fi

        restart_service
        clear
        printf "${GREEN}Cau hinh Nginx voi plugin cache thanh cong.${NC}\n"
    else
        clear
        printf "${ALERT}\n"
    fi
}

ALERT=""
select_domain
if [ -z "${ALERT}" ]; then
    _run
else
    clear
    printf "${ALERT}\n"
fi
wp_menu_advanced