#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
# Please don't copy copy under any circumstance for business reason! #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

_run(){
	select_domain
    if [[ -z "${ALERT}" ]]; then
        username=${domain//[-._]/}
        cd_dir /home/"${username}"/"${domain}"/public_html
        sed -i '/WP_CACHE_KEY_SALT/d' /home/"${username}"/"${domain}"/public_html/wp-config.php
        prefix=$(< /dev/urandom tr -dc '[:lower:]' | head -c"${1:-4}";echo;)
        wp config set WP_CACHE_KEY_SALT "${username}"_"${prefix}" --allow-root
        restart_service
        clear
        printf "${GREEN}Tao WP_CACHE_KEY_SALT thanh cong.${NC}\n"
    else
      clear
      printf "${ALERT}\n"
    fi
}

_run "$@"
menu_wp