#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_run(){
    username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
    if [ -f "/home/${username}/${domain}/public_html/wp-config.php" ]; then
        cd_dir /home/"${username}"/"${domain}"/public_html
        sed -i '/WP_CACHE_KEY_SALT/d' /home/"${username}"/"${domain}"/public_html/wp-config.php
        prefix=$(< /dev/urandom tr -dc '[:lower:]' | head -c"${1:-6}";echo;)
        wp config set WP_CACHE_KEY_SALT "${username}"_"${prefix}" --allow-root
        chow -R "${username}":"${username}" /home/"${username}"/"${domain}"/public_html
        if nginx -t; then
            systemctl restart nginx
            systemctl restart php-fpm.service
            if [ "${php2_release}" == "yes" ]; then
                systemctl restart "${php2_version}"-php-fpm
            fi
            clear
            printf "%s\n" "${GREEN}Tao WP_CACHE_KEY_SALT thanh cong.${NC}"
        else
            printf "%s\n" "${RED}Cau hinh Nginx khong chinh xac. Vui long kiem tra lai${NC}"
        fi
    else
        clear
        printf "%s\n" "${RED}File wp-config.php khong ton tai.${NC}"
    fi
}

domain=""
select_domain
if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
else
    if [ -z "${ALERT}" ]; then
        _run "$@"
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
fi
wp_menu_advanced