#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
	username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');

	if [[ -z "${username}" ]]; then
		read -r -p "Nhap vao FTP user: " username
	fi

	db_name=$(grep "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');

	if [[ -z "${db_name}" ]]; then
		read -r -p "Nhap vao database name: " db_name
	fi
}

backup_confirm(){
	read -r -p "Ban co muon backup du lieu truoc khi cap nhat khong? (y/n) " promt_backup
}

input(){
	read -r -p "Nhap admin username: " admin_username
    read -r -p "Nhap mat khau admin wp-admin moi: " new_admin_pwd
}

backup(){
    cd_dir /home/"${username}"/"${domain}"/public_html
    if [[ -f "/home/backup/${DATE}/${domain}/${db_name}.sql" ]]; then
        rm -rf /home/backup/"${DATE}"/"${domain}"/"${db_name}".sql
    fi
    if [[ ! -d "/home/backup/${DATE}/${domain}" ]]; then
        mkdir -p /home/backup/"${DATE}"/"${domain}"
    fi
    wp db export --allow-root /home/backup/"${DATE}"/"${domain}"/"${db_name}".sql
}

change_pass_admin(){
	cd_dir /home/"${username}"/"${domain}"/public_html
	wp user update "${admin_username}" --user_pass="${new_admin_pwd}"
}

_run(){
	backup_confirm
	check_wpconfig "${username}" "${domain}"

	if ! yes_no_confirm "${promt_backup}"
    then
        ALERT=$(
            printf "${RED}Ban da chon khong backup. Dieu nay khong an toan.${NC}\n"
            printf "${RED}He thong se huy thay doi mat khau admin (wp-admin).${NC}\n"
        )
    fi

	if [ -z "${ALERT}" ]; then
		input
		backup
		change_pass_admin
		restart_service
		clear
		printf "${GREEN}Doi mat khau admin (wp-admin) thanh cong.${NC}\n"
	else
		clear
		printf "${ALERT}"
	fi
}

select_domain
if [ -z "${ALERT}" ]; then
    _run
else
    clear
    printf "${ALERT}\n"
fi
menu_wp