#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
    db_name=$(grep -w "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
    new_admin_pwd=$(gen_pass)
}

backup_confirm(){
    while true
    do
        read -r -p "Ban co muon backup du lieu truoc khi doi mat khau admin khong? (y/n) " promt_backup
        echo
        if [[ "${promt_backup}" =~ ^([yY])$ || "${promt_backup}" =~ ^([nN])$ ]]; then
            break
        else
            clear
            printf "%s\n" "${RED}Gia tri ban nhap khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done
}

input(){
    while true
    do
        read -r -p "Nhap ID cua tai khoan admin muon doi mat khau [0 = Thoat]: " admin_id
        echo
        if valid_number "${admin_id}"; then
            break
        else
            printf "%s\n" "${RED}Gia tri ban nhap khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done
}

backup(){
    cd_dir /home/"${username}"/"${domain}"/public_html
    if [[ -f "/home/backup/${CURRENT_DATE}/${domain}/${db_name}.sql" ]]; then
        rm -rf /home/backup/"${CURRENT_DATE}"/"${domain}"/"${db_name}".sql
    fi
    if [[ -f "/home/backup/${CURRENT_DATE}/${domain}/${db_name}.sql.gz" ]]; then
        rm -rf /home/backup/"${CURRENT_DATE}"/"${domain}"/"${db_name}".sql.gz
    fi
    if [[ ! -d "/home/backup/${CURRENT_DATE}/${domain}" ]]; then
        mkdir -p /home/backup/"${CURRENT_DATE}"/"${domain}"
    fi

    cd_dir /home/backup/"${CURRENT_DATE}"/"${domain}"
    mysqldump -uadmin -p"${mysql_pwd}" "${db_name}" | gzip > "${db_name}".sql.gz
}

_run(){
    cd_dir /home/"${username}"/"${domain}"/public_html
    check_wpconfig "${username}" "${domain}"

    if [ -z "${ALERT}" ]; then
        clear
        echo "Lay danh sach User co quyen Admin tren website: "
        wp user list --role=administrator --fields=ID,user_login --allow-root
        input
        if [ "${admin_id}" == "0" ]; then
            clear
            printf "%s\n" "${RED}Ban da chon huy thao tac.${NC}"
        else
            wp user update "${admin_id}" --user_pass="${new_admin_pwd}" --allow-root
            if nginx -t; then
                systemctl restart nginx
                systemctl restart php-fpm.service
                if [ "${php2_release}" == "yes" ]; then
                    systemctl restart "${php2_version}"-php-fpm
                fi
                clear
                printf "%s\n" "${GREEN}Doi mat khau admin (wp-admin) thanh cong.${NC}"
                printf "%s\n" "${GREEN}Mat khau moi la:${NC} ${RED}${new_admin_pwd}${NC}"
            else
                printf "%s\n" "${RED}Cau hinh Nginx khong chinh xac. Vui long kiem tra lai${NC}"
            fi
        fi
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
}

ALERT=""
promt_backup=""
domain=""
admin_id=""
select_domain
if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac.${NC}"
else
    set_var
    backup_confirm
    if [[ "${promt_backup}" =~ ^([yY])$ ]]; then
        backup
    fi
    _run "$@"
fi
menu_wp