#!/bin/bash

#################################################
# Auto Install & Optimize LEMP Stack on CentOS 7#
# Version: 1.0                                  #
# Author: Sanvv - HOSTVN Technical              #
#                                               #
# Please don't remove copyright. Thank!         #
#################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
	username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');

	if [[ -z "${username}" ]]; then
		read -r -p "Nhap vao FTP username: " username
	fi

	db_name=$(grep "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');

	if [[ -z "${db_name}" ]]; then
		read -r -p "Nhap vao database name: " db_name
	fi

	php_mode=$(grep "php_mode" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
	rewrite="include /etc/nginx/rewrite/wordpress.conf;"
	plugin_cache="$(grep "plugin_cache" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')"
}

input(){
	read -r -p "Nhap vao ten mien moi: " newdomain
}

backup_confirm(){
    read -r -p "Ban co muon backup du lieu truoc khi toi uu khong? (y/n) " promt_backup
}

backup(){
    cd_dir /home/"${username}"/"${domain}"/public_html
    if [[ -f "/home/backup/${DATE}/${domain}/${db_name}.sql" ]]; then
        rm -rf /home/backup/"${DATE}"/"${domain}"/"${db_name}".sql
    fi

    if [[ ! -d "/home/backup/${DATE}/${domain}" ]]; then
        mkdir -p /home/backup/"${DATE}"/"${domain}"
    fi
    wp db export --allow-root /home/backup/"${DATE}"/"${domain}"/"${db_name}".sql
}

check_plugins_cache(){
    if [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/w3-total-cache" ]]; then
        cache="include /etc/nginx/wordpress/w3c.conf;"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/wp-fastest-cache" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/wpfc.conf;"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/wp-rocket" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/wprocket.conf;"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/wp-super-cache" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/wpsc.conf;"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/cache-enabler" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/enabler.conf;"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/swift-performance-lite" && "${plugin_cache}" == "swift1" ]]; then
        cache="include /etc/nginx/extra/staticfiles.conf;"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/swift-performance-lite" && "${plugin_cache}" == "swift2" ]]; then
        cache="include /etc/nginx/wordpress/swift2.conf;"
    else
        cache="include /etc/nginx/extra/staticfiles.conf;"
    fi
}

change_path(){
	mv /home/"${username}"/"${domain}" /home/"${username}"/"${newdomain}"
}

backup_vhost(){
    if [[ -f "/etc/nginx/backup_vhost/${domain}.conf.orig" ]]; then
        rm -rf /etc/nginx/backup_vhost/"${domain}".conf.orig
    fi

    mv "/etc/nginx/conf.d/$domain.conf" "/etc/nginx/backup_vhost/${domain}.conf.orig"
}

change_vhost(){
	backup_vhost
	check_plugins_cache
    clear
    select_plugin_seo
	fastcgi

    if [[ "${plugins_seo}" == "yoast_seo" ]]; then
        include_seo="include /etc/nginx/wordpress/yoast_seo.conf;"
    elif [[ "${plugins_seo}" == "rank_math_seo" ]]; then
        include_seo="include /etc/nginx/wordpress/rank_math_seo.conf;"
    else
        include_seo=""
    fi

	cat >> "${VHOST_DIR}/${newdomain}.conf" << END
server {
    listen 80;
    server_name ${newdomain} www.${newdomain};

    #access_log off;
    #access_log /home/${username}/${newdomain}/logs/access.log;
    #error_log off;
    error_log /home/${username}/${newdomain}/logs/error.log;
    root /home/${username}/${newdomain}/public_html;
    index index.php index.html index.htm;

    ${rewrite}
    ${cache}

    location ~ \.php\$ {
        try_files \$uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)\$;
        fastcgi_index index.php;
        include /etc/nginx/fastcgi_params;
        include /etc/nginx/extra/nginx_limits.conf;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        if (-f \$request_filename)
        {
            ${fastcgi_pass}
        }
    }

    location = /wp-login.php {
        limit_req zone=two burst=1 nodelay;
        include /etc/nginx/fastcgi_params;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        ${fastcgi_pass}
    }

    ${include_seo}
    include /etc/nginx/wordpress/wordpress_secure.conf;
    include /etc/nginx/extra/security.conf;
}
END
}

change_phpconfig(){
	php_conf_path="/etc/php-fpm.d"
	if [[ "${php2_release}" == "yes" && "${php_mode}" == "2" ]]; then
        php_conf_path="/etc/opt/remi/${php2_version}/php-fpm.d"
        if [[ "${php2_version}" == "php56" ]]; then
            php_conf_path="/opt/remi/${php2_version}/root/etc/php-fpm.d"
        fi
    fi

    mv "${php_conf_path}"/"${domain}".conf "${php_conf_path}"/"${newdomain}".conf
    sed -i "s/${domain}/${newdomain}/g" "${php_conf_path}"/"${newdomain}".conf
}

change_in_db(){
    cd_dir /home/"${username}"/"${domain}"/public_html
    wp search-replace --allow-root "https://${domain}" "http://${newdomain}"
    wp search-replace --allow-root "http://${domain}" "http://${newdomain}"
}

change_user_config(){
    mv "${USER_DIR}"/."${domain}".conf "${USER_DIR}"/."${newdomain}".conf
}

run(){
	select_domain

	set_var
	check_is_wordpress "${username}" "${domain}"
  check_wpconfig "${username}" "${domain}"
	input
	validate_domain "${newdomain}"
    backup_confirm

    if [[ "$domain" == "$newdomain" ]]; then
        ALERT=$(printf "${RED}Ten mien moi cua ban giong ten mien cu. Huy thay doi ten mien.${NC}\n")
    fi

    if ! yes_no_confirm "${promt_backup}"
    then
        ALERT=$(
            printf "${RED}Ban da chon khong backup.${NC}\n"
            printf "${RED}Dieu nay khong an toan.\n He thong se huy thay doi ten mien.${NC}\n"
        )
    fi

	if [ -z "${ALERT}" ]; then
    backup
		change_path
		change_vhost
		change_phpconfig
		change_in_db
        change_user_config
        clear
		printf "${GREEN}Doi ten mien thanh cong.${NC}\n"
	else
        clear
		printf "${ALERT}\n"
	fi
}

run
menu_wp