#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

_run(){
    ALERT=""
    select_domain
    if [[ -z "${ALERT}" ]]; then
        username=${domain//[-._]/}
        cd_dir /home/"${username}"/"${domain}"/public_html
        debug=$(wp config get WP_DEBUG --allow-root)
        if [[ "${debug}" == 1 ]]; then
            wp config set WP_DEBUG false --raw --allow-root
            restart_service
            clear
            printf "${GREEN}Tat Debug mode thanh cong.${NC}\n"
            echo ""
        else
            wp config set WP_DEBUG true --raw --allow-root
            restart_service
            clear
            printf "${GREEN}Bat Debug mode thanh cong.${NC}\n"
            echo ""
        fi
    else
        printf "${ALERT}\n"
    fi
}

_run
menu_wp