#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_run(){
    username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
    cd_dir /home/"${username}"/"${domain}"/public_html
    debug=$(wp config get WP_DEBUG --allow-root)
    if [[ "${debug}" == 1 ]]; then
        wp config set WP_DEBUG false --raw --allow-root
        if nginx -t; then
            systemctl restart nginx
            systemctl restart php-fpm.service
            if [ "${php2_release}" == "yes" ]; then
                systemctl restart "${php2_version}"-php-fpm
            fi
            clear
            printf "%s\n" "${GREEN}Tat Debug mode thanh cong.${NC}"
            echo ""
        else
            printf "%s\n" "${RED}Cau hinh Nginx khong chinh xac. Vui long kiem tra lai${NC}"
        fi
    else
        wp config set WP_DEBUG true --raw --allow-root
        if nginx -t; then
            systemctl restart nginx
            systemctl restart php-fpm.service
            if [ "${php2_release}" == "yes" ]; then
                systemctl restart "${php2_version}"-php-fpm
            fi
            clear
            printf "%s\n" "${GREEN}Bat Debug mode thanh cong.${NC}"
            echo ""
        else
            printf "%s\n" "${RED}Cau hinh Nginx khong chinh xac. Vui long kiem tra lai${NC}"
        fi
    fi
}

domain=""
select_domain
if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
else
    if [ -z "${ALERT}" ]; then
        _run
    else
    	clear
        printf "%s\n" "${ALERT}"
    fi
fi
menu_wp