#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_run(){
  username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')

  if [ ! -d "/home/${username}/${domain}/htpasswd" ]; then
      mkdir -p /home/"${username}"/"${domain}"/htpasswd
  fi

  read -r -p "Nhap vao user: " htpasswd_user
  read -r -p "Nhap vao mat khau: " htpasswd_passwd

  htpasswd -b -c /home/"${username}"/"${domain}"/htpasswd/.htpasswd "${htpasswd_user}" "${htpasswd_passwd}"

  if [ -f "/home/${username}/${domain}/htpasswd/htpasswd.conf" ]; then
      rm -rf /home/"${username}"/"${domain}"/htpasswd/htpasswd.conf
  fi
  chown -R "${username}":"${username}" /home/"${username}"/"${domain}"/htpasswd/.htpasswd
  cat >> "/home/${username}/${domain}/htpasswd/htpasswd.conf" << END
location /wp-admin {
  auth_basic "Restricted";
  auth_basic_user_file /home/${username}/${domain}/htpasswd/.htpasswd;
}
END

  sed -i "/index.html/a include /home/${username}/${domain}/htpasswd/htpasswd.conf;" "${VHOST_DIR}"/"${domain}".conf
  service nginx reload
  clear
  printf "Tao mat khau hai lop thanh cong.\n"
}

ALERT=""
domain=""

select_domain

if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
else
    if [ -z "${ALERT}" ]; then
        _run
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
fi

menu_wp
