#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

_run(){
    ALERT=""
    select_domain
    if [[ -z "${ALERT}" ]]; then
        username=${domain//[-._]/}
        cd_dir /home/"${username}"/"${domain}"/public_html
        wp maintenance-mode is-active --allow-root

        if [[ $? == 1 ]]; then
            wp maintenance-mode activate --allow-root
            printf "${GREEN}Bat che do bao tri thanh cong.${NC}\n"
            echo ""
        else
            wp maintenance-mode deactivate --allow-root
            clear
            restart_service
            printf "${GREEN}Tat che do bao tri thanh cong.${NC}\n"
            echo ""
        fi
    else
        printf "${ALERT}\n"
    fi
}

_run
wp_menu_advanced