#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "${GREEN}=========================================${NC}\n"
printf "${GREEN}             Quan ly Database            ${NC}\n"
printf "${GREEN}=========================================${NC}\n"
echo

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Toi uu database${NC}\n"
    printf "${GREEN}2. Repair database${NC}\n"
    printf "${GREEN} ----------------------------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; wp_optimize_db ;;
        2) clear; wp_repair_db ;;
        0) clear; menu_wp ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done