#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s=========================================%s\n" "${GREEN}" "${NC}"
printf "%s             Quan ly Plugins             %s\n" "${GREEN}" "${NC}"
printf "%s=========================================%s\n" "${GREEN}" "${NC}"
echo

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Cap nhat plugins (Tru plugins tra phi)%s\n" "${GREEN}" "${NC}"
    printf "%s2. Huy kich hoat toan bo plugins %s\n" "${GREEN}" "${NC}"
    printf "%s ========================================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; wp_update_plugins ;;
        2) clear; deactive_all_plugins ;;
        0) clear; menu_wp ;;
        *) clear; printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done