#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "${GREEN}=========================================${NC}\n"
printf "${GREEN}             Sao luu/Khoi phuc           ${NC}\n"
printf "${GREEN}=========================================${NC}\n"
echo

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Sao luu du lieu (Local)${NC}\n"
    printf "${GREEN}2. Khoi phuc du lieu (Local)${NC}\n"
    printf "${GREEN}3. Sao luu len Google Drive${NC}\n"
    printf "${GREEN}4. Thiet lap backup tu dong${NC}\n"
    printf "${GREEN} ----------------------------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; wp_backup ;;
        2) clear; wp_restore ;;
        3) clear; menu_ggdrive ;;
        4) clear; menu_cronjob ;;
        0) clear; menu_wp ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done