#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_run(){
  username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
  mv /home/"${username}"/"${domain}"/public_html/wp-config.php /home/"${username}"/"${domain}"/wp-config.php
  clear
  printf "Di chuyen wp-config thanh cong.\n"
}

ALERT=""
domain=""

select_domain

if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
else
    if [ -z "${ALERT}" ]; then
        _run
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
fi

menu_wp
