#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
# Please don't copy copy under any circumstance for business reason! #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
	username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
	db_name=$(grep "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

backup_confirm(){
	read -r -p "Ban co muon backup du lieu truoc khi toi uu khong? (y/n) " promt_backup
}

backup(){
	cd_dir /home/"${username}"/"${domain}"/public_html
	if [[ -f "/home/backup/${DATE}/${domain}/${db_name}.sql" ]]; then
		rm -rf /home/backup/"${DATE}"/"${domain}"/"${db_name}".sql
	fi
	if [[ ! -d "/home/backup/${DATE}/${domain}" ]]; then
        mkdir -p /home/backup/"${DATE}"/"${domain}"
    fi
	wp db export --allow-root /home/backup/"${DATE}"/"${domain}"/"${db_name}".sql
}

optimize_db(){
	cd_dir /home/"${username}"/"${domain}"/public_html
	wp db optimize --allow-root
}

_run(){
	select_domain

	set_var
	check_is_wordpress "${username}" "${domain}"

	backup_confirm
	if ! yes_no_confirm "${promt_backup}"
    then
        ALERT=$(
            printf "${RED}Ban da chon khong backup.${NC}\n"
            printf "${RED}Dieu nay khong an toan.\n He thong se huy toi uu Database.${NC}\n"
        )
    fi

	if [ -z "${ALERT}" ]; then
		make_backup_dir "${domain}"
		backup
		optimize_db
		restart_service
		clear
	    printf "${GREEN}Toi uu database thanh cong.${NC}\n"
	else
		clear
		printf "${ALERT}\n"
	fi
}

_run
echo ""
sleep 2
menu_wp