#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

backup_confirm(){
    while true
    do
        read -r -p "Ban co muon backup du lieu truoc khi toi uu khong? (y/n) " promt_backup
        echo
        if [[ "${promt_backup}" =~ ^([yY])$ || "${promt_backup}" =~ ^([nN])$ ]]; then
            break
        else
            printf "%s\n" "${RED}Gia tri ban nhap khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done
}

backup(){
    if [[ ! -d "/home/backup/${CURRENT_DATE}/${domain}" ]]; then
        mkdir -p /home/backup/"${CURRENT_DATE}"/"${domain}"
    fi
    cd_dir /home/"${username}"/"${domain}"
    if [ -f "/home/backup/${CURRENT_DATE}/${domain}/${domain}.tar.gz" ]; then
        rm -rf /home/backup/"${CURRENT_DATE}"/"${domain}"/"${domain}".tar.gz
    fi
    tar -cpzvf /home/backup/"${CURRENT_DATE}"/"${domain}"/"${domain}".tar.gz public_html --exclude "public_html/wp-content/cache"
}

_run(){
    before=$(du -sh /home/"${username}"/"${domain}"/public_html/wp-content/uploads | cut -f1 -d"M")
    clear
    printf "%s\n" "${GREEN}Dang toi uu anh, vui long doi...${NC}"
    find /home/"${username}"/"${domain}"/public_html/wp-content/uploads -type f -iname "*.png" -exec pngquant --quality=75-80 --ext=.png --force {} \;
    find /home/"${username}"/"${domain}"/public_html/wp-content/uploads -type f \( -iname "*.jpg" -o -iname "*.jpeg" \) -exec jpegoptim -m 75 -f --strip-all {} \;
    after=$(du -sh /home/"${username}"/"${domain}"/public_html/wp-content/uploads | cut -f1 -d"M")
    clear
    printf "%s\n" "${GREEN}Toi uu hinh anh thanh cong${NC}"
    printf "%s\n" "${GREEN}Dung luong truoc khi toi uu:${NC} ${RED}${before}M${NC}"
    printf "%s\n" "${GREEN}Dung luong sau khi toi uu:${NC} ${RED}${after}M${NC}"
}

promt_backup=""
domain=""
before=""
after=""
select_domain

if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy hanh dong.${NC}"
else
    if [ -z "${ALERT}" ]; then
        username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
        backup_confirm
        if [[ "${promt_backup}" =~ ^([yY])$ ]];then
            make_backup_dir "${domain}"
            backup
        fi
        _run
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
fi

wp_menu_advanced