#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function
# shellcheck disable=SC1091
source /var/hostvn/menu/validate/rule

set_var(){
	username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
	db_name=$(grep "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

backup_confirm(){
	read -r -p "Ban co muon backup du lieu truoc khi toi uu khong? (y/n) " promt_backup
}

backup(){
	cd_dir /home/"${username}"/"${domain}"/public_html
	if [[ ! -d "/home/${username}/backup/${DATE}" ]]; then
		mkdir -p /home/"${username}"/backup/"${DATE}"
	fi
	wp db export --allow-root /home/"${username}"/backup/"${DATE}"/"${DATE}"_"${db_name}".sql
}

optimize_db(){
	wp db optimize --allow-root
	printf "${GREEN}Toi uu database thanh cong.${NC}\n"
}

run(){
	backup_confirm

	if [[ "${promt_backup}" =~ ^([yY])$ ]]; then
		select_domain
		set_var
		check_is_wordpress ${username} ${domain}
		if [[ -z "${ALERT}" ]]; then
			backup
			optimize_db
		else
			printf "${ALERT}"
		fi
	else
		printf "${RED}Ban da chon khong backup. Dieu nay khong an toan.\n He thong se huy toi uu Database.${NC}\n"
	fi
}

run
echo ""
sleep 2
menu_wp