#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

_run(){
    ALERT=""
    select_domain

    if [[ -z "${ALERT}" ]]; then
        #https://www.howtoforge.com/tutorial/linux-grep-command/
        #https://stackoverflow.com/a/6284370
        plugins_seo_current=$(grep -w "plugins_seo" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
        sed -i '/plugins_seo=/d' "${USER_DIR}"/."${domain}".conf
        if [[ ${plugins_seo_current} == "rank_math_seo" ]]; then
            sed -i '|etc/nginx/wordpress/rank_math_seo.conf;|d' "${VHOST_DIR}"/"${domain}".conf
            echo "plugins_seo=" >> "${USER_DIR}"/."${domain}".conf
            restart_service
            printf "${GREEN}Tat cau hinh Rank Math Seo thanh cong.${NC}\n"
        elif [[ ${plugins_seo_current} == "yoast_seo" ]]; then
            printf "${RED}Ban dang su dung Yoast Seo.${NC}\n"
        elif [[ -z "${plugins_seo_current}" ]]; then
            sed -i '/index.php/a include /etc/nginx/wordpress/rank_math_seo.conf;' "${VHOST_DIR}"/"${domain}".conf
            restart_service
            printf "${GREEN}Bat cau hinh Rank Math Seo thanh cong.${NC}\n"
        fi
    else
        printf "${ALERT}\n"
    fi
}

_run
wp_menu_advanced