#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

_run(){
    check_yoast=$(grep -rnw "${VHOST_DIR}/${domain}.conf" -e "yoast_seo")

    if [ -n "${check_yoast}" ]; then
        while true
        do
            read -r -p "Phat hien cau hinh Yoast Seo. Ban co muon xoa cau hinh Yoast Seo khong ? (y/n) " del_yoast
            echo
            if [[ "${del_yoast}" =~ ^([yY])$ ]]; then
                sed -i '/yoast_seo/d' "${VHOST_DIR}"/"${domain}".conf
                break
            elif [[ "${del_yoast}" =~ ^([nN])$ ]]; then
                ALERT=$(printf "%s\n" "${RED}Ban da chon khong xoa config Yoast Seo. Huy cau hinh Rank Math Seo.${NC}")
                break
            else
                printf "%s\n" "${RED}Gia tri ban nhap khong chinh xac vui long nhap lai.${NC}"
            fi
        done
    fi

    if [[ -z "${ALERT}" ]]; then
        check_mathseo=$(grep -rnw "${VHOST_DIR}/${domain}.conf" -e "rank_math_seo")
        sed -i '/plugins_seo=/d' "${USER_DIR}"/."${domain}".conf
        if [[ -n "${check_mathseo}" ]]; then
            sed -i '/rank_math_seo/d' "${VHOST_DIR}"/"${domain}".conf
            echo "plugins_seo=" >> "${USER_DIR}"/."${domain}".conf
            restart_service
            printf "%s\n" "${GREEN}Tat cau hinh Rank Math Seo thanh cong.${NC}"
        else
            echo "plugins_seo=rank_math_seo" >> "${USER_DIR}"/."${domain}".conf
            sed -i '/index.html/a include /etc/nginx/wordpress/rank_math_seo.conf;' "${VHOST_DIR}"/"${domain}".conf
            restart_service
            printf "%s\n" "${GREEN}Bat cau hinh Rank Math Seo thanh cong.${NC}"
        fi
    else
        printf "%s\n" "${ALERT}"
    fi
}
ALERT=""
del_yoast=""
domain=""
select_domain

if [ -n "${domain}" ]; then
    _run
else
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
fi

wp_menu_advanced