#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_run(){
    select_plugin_cache

    if [ "${plugins_cache}" == "wprocket" ]; then
        sed -i "/rocket-nginx/d" "${VHOST_DIR}"/"${domain}".conf
    else
        sed -i "/${plugins_cache}.conf/d" "${VHOST_DIR}"/"${domain}".conf
    fi
    staticfiles=$(grep -rnw "${VHOST_DIR}/${domain}.conf" -e "staticfiles.conf")
    if [ -z "${staticfiles}" ]; then
        sed -i '/index.html/a include /etc/nginx/extra/staticfiles.conf;' "${VHOST_DIR}"/"${domain}".conf
    fi
    sed -i '/plugin_cache=/d' "${USER_DIR}"/."${domain}".conf
    echo "plugin_cache=" >> "${USER_DIR}"/."${domain}".conf
    if [ -f "${WORDPRESS_CRON_DIR}/${domain}" ]; then
        rm -rf "${WORDPRESS_CRON_DIR}"/"${domain:?}"
    fi
    clear
    printf "%s\n" "${GREEN}Xoa cau hinh plugins cache ${plugin_cache} thanh cong${NC}"
}

ALERT=""
domain=""
plugins_cache=""
select_domain

if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
else
    if [ -z "${ALERT}" ]; then
        _run
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
fi
wp_plugin_cache