#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    user=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    db_name=$(grep -w "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

confirm_restore(){
    while true
    do
        read -r -p "Ban muon khoi phuc du lieu ? (y/n) " promt_restore
        echo
        if [[ "${promt_restore}" =~ ^([yY])$ || "${promt_restore}" =~ ^([nN])$ ]];
        then
            break
        else
            printf "%s\n" "${RED}Gia tri ban nhap khong chinh xac vui long nhap lai.${NC}"
        fi
    done
}

_restore_source(){
  if [ -f "/home/backup/${date}/${domain}/${domain}.tar.gz" ]; then
      if [[ ! -d "/home/${user}/${domain}/public_html" ]]; then
            mkdir -p /home/"${user}"/"${domain}"/public_html
      fi
      rm -rf /home/"${user}"/"${domain}"/public_html/*
      tar xvzf /home/backup/"${date}"/"${domain}"/"${domain}".tar.gz -C /home/"${user}"/"${domain}"/
      chown -R "${user}":"${user}" /home/"${user}"
  fi
}

restore_db(){
    cd_dir /home/"${user}"/"${domain}"/public_html
    db_name=$(wp config get DB_NAME --allow-root)

    cd_dir /home/backup/"${date}"/"${domain}"

    sql_files=()
    for entry in *.{sql,sql.gz}; do
        if [ -f "${entry}" ]; then
            sql_files+=("${entry}")
        fi
    done

    echo "Chon file database muon khoi phuc"
    PS3="Nhap vao lua chon cua ban [0 = Thoat]: "
    select opt in "${sql_files[@]}"
    do
        sql=$opt
        break
    done

    if [[ ${sql} == *"sql.gz"* ]]; then
        gzip < "${sql}" | mysql -uadmin -p"${mysql_pwd}" "${db_name}"
    else
        mysql -uadmin -p"${mysql_pwd}" "${db_name}" < "${sql}"
    fi

#    if [ -f "/home/backup/${date}/${domain}/${db_name}.sql.gz" ]; then
#        wp db import --allow-root /home/backup/"${date}"/"${domain}"/"${db_name}".sql.gz
#    fi
}

_run(){
    set_var
    check_is_wordpress "${user}" "${domain}"
    check_backup_exists "${date}" "${domain}"

    if ! check_backup_empty "${date}" "${domain}"; then
        ALERT="${RED}Ten mien nay khong co backup.${NC}\n"
    fi

    if [ ! -f "/home/backup/${date}/${domain}/${domain}.tar.gz" ]; then
        ALERT="${RED}Ten mien nay khong co backup.${NC}\n"
    fi

    if [ ! -f "/home/backup/${date}/${domain}/${db_name}.sql.gz" ]; then
        ALERT="${RED}Ten mien nay khong co backup.${NC}"
    fi

    if [ -z "${ALERT}" ]; then
        _restore_source
        empty_db
        restore_db
        if nginx -t; then
            systemctl restart nginx
            systemctl restart php-fpm.service
            if [ "${php2_release}" == "yes" ]; then
                systemctl restart "${php2_version}"-php-fpm
            fi
            clear
            printf "%s\n" "${GREEN}Khoi phuc du lieu thanh cong.${NC}"
        else
            printf "%s\n" "${RED}Cau hinh Nginx khong chinh xac. Vui long kiem tra lai${NC}"
        fi
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
}

promt_restore=""
date=""
domain=""
confirm_restore
if [[ "${promt_restore}" =~ ^([yY])$ ]]; then
    ALERT=""
    list_backup
    if [ -z "${date}" ]; then
        clear
        printf "%s\n" "${RED}Ban da chon huy khoi phuc du lieu.${NC}"
    else
        if [ -z "${domain}" ]; then
            clear
            printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
        else
            _run
        fi
    fi
else
    clear
    printf "%s\n" "${RED}Ban da chon huy khoi phuc du lieu.${NC}"
fi
menu_wp
