#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function
# shellcheck disable=SC1091
source /var/hostvn/menu/validate/rule

set_var(){
	username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
	db_name=$(grep "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

backup_confirm(){
	read -r -p "Ban co muon backup du lieu truoc khi cap nhat khong? (y/n) " promt_backup
}

backup(){
	cd_dir /home/"${username}"
	tar -cpzvf /home/"${username}"/backup/"$(date +%F)"_"${domain}".tar.gz "${domain}"
	cd_dir /home/"${username}"/"${domain}"/public_html
	wp db export --allow-root /home/"${username}"/backup/"$(date +%F)"_"${db_name}".sql
}

update_wp(){
	wp core update --allow-root
	chown -R "${username}":"${username}" ./*
	printf "${GREEN}Cap nhat WordPress thanh cong.${NC}\n"
}

run(){
	backup_confirm

	if [[ "${promt_backup}" =~ ^([yY])$ ]]; then
		select_domain
		set_var
		check_is_wordpress ${username} ${domain}
		if [[ -z "${ALERT}" ]]; then
			backup
			update_wp
		else
			printf "${ALERT}"
		fi
	else
		printf "${RED}Ban da chon khong backup. Dieu nay khong an toan.\n He thong se huy cap nhat WordPress.${NC}\n"
	fi
}

run
echo ""
sleep 1
menu_wp