#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/variable_common
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
	username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

backup_alert(){
	read -r -p "Bạn có muốn backup dữ liệu trước khi update không ? (y/n) " backup_confirm
}

backup(){
	backup_alert
	if [[ "${backup_confirm}" == "y" || "${backup_confirm}" == "Y" ]]; then
		db_name="$(grep "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')"
		cd_dir /home/"${username}"
		tar -cpzvf /home/"${username}"/backup/"$(date +%F)"_"${domain}".tar.gz "${domain}"
		cd_dir /home/"${username}"/backup
		wp db export --allow-root /home/"${username}"/backup/"$(date +%F)"_"${db_name}".sql
	else
		echo "Bạn đã chọn không backup. Điều này là không an toàn. Hệ thống sẽ huỷ cập nhật WordPress."
		menu_wp
	fi
}

update_plugins(){
	wp plugin update --all --allow-root
	chown -R "${username}":"${username}" ./*
	echo "Cập nhật plugins thành công."
}

select_domain menu_wp
set_var
backup
update_plugins
echo ""
sleep 1
menu_wp