#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    db_name="$(grep -w "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')"
}

backup_confirm(){
    while true
    do
        read -r -p "Ban co muon backup du lieu truoc khi update plugins khong? (y/n) " promt_backup
        echo
        if [[ "${promt_backup}" =~ ^([yY])$ || "${promt_backup}" =~ ^([nN])$ ]]; then
            break
        else
            printf "%s\n" "${RED}Gia tri ban nhap khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done
}

backup(){
    cd_dir /home/"${username}"/"${domain}"
    if [[ ! -d "home/backup/${CURRENT_DATE}/${domain}" ]]; then
        mkdir -p home/backup/"${CURRENT_DATE}"/"${domain}"
    fi
    if [[ -f "/home/backup/${CURRENT_DATE}/${domain}/${domain}.tar.gz" ]]; then
        rm -rf /home/backup/"${CURRENT_DATE}"/"${domain}"/"${domain}".tar.gz
    fi
    tar -cpzvf /home/backup/"${CURRENT_DATE}"/"${domain}"/"${domain}".tar.gz public_html --exclude "public_html/wp-content/cache"

    cd_dir /home/"${username}"/"${domain}"/public_html
    if [[ -f "/home/backup/${CURRENT_DATE}/${domain}/${db_name}.sql" ]]; then
        rm -rf /home/backup/"${CURRENT_DATE}"/"${domain}"/"${db_name}".sql
    fi
    if [[ -f "/home/backup/${CURRENT_DATE}/${domain}/${db_name}.sql.gz" ]]; then
        rm -rf /home/backup/"${CURRENT_DATE}"/"${domain}"/"${db_name}".sql,gz
    fi

    cd_dir /home/backup/"${CURRENT_DATE}"/"${domain}"
    mysqldump -uadmin -p"${mysql_pwd}" "${db_name}" | gzip > "${db_name}".sql.gz
}

_update_plugins(){
    cd_dir /home/"${username}"/"${domain}"/public_html
    wp plugin update --all --allow-root
    chown -R "${username}":"${username}" ./*
}

_run(){
    set_var
    check_is_wordpress "${username}" "${domain}"

    if [ -z "${ALERT}" ]; then
        backup_confirm
        if [[ "${promt_backup}" =~ ^([yY])$ ]];then
            make_backup_dir "${domain}"
            backup
        fi
        _update_plugins
        if nginx -t; then
            systemctl restart nginx
            systemctl restart php-fpm.service
            if [ "${php2_release}" == "yes" ]; then
                systemctl restart "${php2_version}"-php-fpm
            fi
            clear
            printf "%s\n" "${GREEN}Update plugins thanh cong.${NC}"
        else
            printf "%s\n" "${RED}Cau hinh Nginx khong chinh xac. Vui long kiem tra lai${NC}"
        fi
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
}

ALERT=""
promt_backup=""
domain=""
select_domain
if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac.${NC}"
else
    if [ -z "${ALERT}" ]; then
        _run
    else
    	clear
        printf "%s\n" "${ALERT}"
    fi
fi
wp_menu_plugins