#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/variable_common
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu

check_version(){
	username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
	cd_dir /home/"${username}"/"${domain}"/public_html/
	printf "${GREEN}Phien ban WordPress dang su dung: %s ${NC}\n" "$(wp core version --allow-root)"
}

run(){
	select_domain
	check_version
}

run
echo ""
sleep 2
menu_wp