#!/bin/bash

#################################################
# Auto Install & Optimize LEMP Stack on CentOS 7#
# Version: 1.0                                  #
# Author: Sanvv - HOSTVN Technical              #
#                                               #
# Please don't remove copyright. Thank!         #
#################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

check_version(){
	username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
	cd_dir /home/"${username}"/"${domain}"/public_html/
	clear
	printf "${GREEN}Phien ban WordPress dang su dung: %s ${NC}\n" "$(wp core version --allow-root)"
}

_run(){
	select_domain

	check_is_wordpress "${username}" "${domain}"
	if [ -z "${ALERT}" ]; then
		check_version
	else
		clear
		printf "${ALERT}\n"
	fi
}

_run
echo ""
sleep 2
menu_wp