#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

check_version(){
    cd_dir /home/"${username}"/"${domain}"/public_html/
    clear
    printf "%s\n" "${GREEN}Phien ban WordPress dang su dung: $(wp core version --allow-root) ${NC}"
}

_run(){
    set_var
    check_is_wordpress "${username}" "${domain}"

    if [ -z "${ALERT}" ]; then
        check_version
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
}

ALERT=""
domain=""
select_domain

if [ -n "${domain}" ]; then
    _run
else
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
fi

menu_wp