#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function
# shellcheck disable=SC1091
source /var/hostvn/menu/validate/rule

set_var(){
	username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

backup(){
	cd_dir /home/"${username}"
	if [[ ! -d "/home/${username}/backup/${DATE}" ]]; then
		mkdir -p /home/"${username}"/backup/"${DATE}"
	fi
	tar -cpzvf /home/"${username}"/backup/"${DATE}"/"${DATE}"_"${domain}".tar.gz "${domain}"
	cd_dir /home/"${username}"/"${domain}"/public_html
	wp db export --allow-root /home/"${username}"/backup/"${DATE}"/"${DATE}"_"${db_name}".sql
	printf "${GREEN}Sao luu du lieu thanh cong.${NC}\n"
	echo ""
}

run(){
	select_domain
	set_var
	check_is_wordpress ${username} ${domain}

	if [[ -z "${ALERT}" ]]; then
		backup
	else
		printf "${ALERT}"
	fi
}

run
sleep 2
menu_wp