#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
	username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

backup(){
	if [[ ! -d "/home/backup/${DATE}/${domain}" ]]; then
        mkdir -p /home/backup/"${DATE}"/"${domain}"
    fi
	cd_dir /home/"${username}"/"${domain}"
	tar -cpzvf /home/backup/"${DATE}"/"${domain}"/"${domain}".tar.gz public_html --exclude "public_html/wp-content/cache"
	cd_dir /home/"${username}"/"${domain}"/public_html
	wp db export --allow-root /home/backup/"${DATE}"/"${domain}"/"${db_name}".sql
	clear
	printf "${GREEN}Sao luu du lieu thanh cong.${NC}\n"
}

run(){
	select_domain
	#validate_domain ${domain}
	set_var
	check_is_wordpress ${username} ${domain}

	if [ -z "${ALERT}" ]; then
		make_backup_dir ${domain}
		backup
	else
		clear
		printf "${ALERT}\n"
	fi
}

run
sleep 2
menu_wp