#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
# Please don't copy copy under any circumstance for business reason! #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

find_string(){
    string=$(grep -rnw "/etc/nginx/conf.d/${domain}.conf" -e 'disable_xmlrpc.conf')
}

xmlrpc(){
    if [ -z "${string}" ]; then
        sed -i '/wordpress_secure.conf/a include /etc/nginx/wordpress/disable_xmlrpc.conf;' /etc/nginx/conf.d/"${domain}".conf
    else
        sed -i '/disable_xmlrpc.conf/d' /etc/nginx/conf.d/"${domain}".conf
    fi
}

_run(){
    select_domain

    if [ -z "${ALERT}" ]; then
        find_string
        xmlrpc
        restart_service
        clear
        printf "${GREEN}Bat/Tat XMLRPC thanh cong${NC}\n"
    else
        clear
        printf "${ALERT}\n"
    fi
}

_run
menu_wp