#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

find_string(){
    string=$(grep -rnw "/etc/nginx/conf.d/${domain}.conf" -e 'disable_xmlrpc.conf')
}

_xmlrpc(){
    if [ -z "${string}" ]; then
        sed -i '/index.html/a include /etc/nginx/wordpress/disable_xmlrpc.conf;' /etc/nginx/conf.d/"${domain}".conf
        noti="${GREEN}Bat chan XMLRPC thanh cong.${NC}/n"
    else
        sed -i '/disable_xmlrpc.conf/d' /etc/nginx/conf.d/"${domain}".conf
        noti="${GREEN}Bo chan XMLRPC thanh cong.${NC}/n"
    fi
}

_run(){
    domain=""
    select_domain

    if [ -n "${domain}" ]; then
        find_string
        _xmlrpc
        restart_service
        clear
        printf "%s\n" "${noti}"
    else
        clear
        printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
    fi
}

_run
wp_menu_advanced