#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

_run(){
	select_domain
    plugins_seo_current=$(grep "plugins_seo" "${USER_DIR}/.${domain:?}.conf" | cut -f2 -d'=')
    if [[ -z "${ALERT}" ]]; then
        sed -i '/plugins_seo=/d' "${USER_DIR}"/."${domain}".conf
        if [[ ${plugins_seo_current} == "yoast_seo" ]]; then
            sed -i '|etc/nginx/wordpress/yoast_seo.conf;|d' "${VHOST_DIR}"/"${domain}".conf
            echo "plugins_seo=" >> "${USER_DIR}"/."${domain}".conf
            printf "${GREEN}Tat cau hinh Yoast Seo thanh cong.${NC}\n"
        elif [[ ${plugins_seo_current} == "rank_math_seo" ]]; then
            printf "${RED}Ban dang su dung Rank Math Seo.${NC}\n"
        elif [[ -z "${plugins_seo_current}" ]]; then
            sec="include /etc/nginx/extra/security.conf;"
            seo="include /etc/nginx/wordpress/yoast_seo.conf;"
            include="${sec}"$'\n'"${seo}"
            sed -i 's|include /etc/nginx/extra/security.conf;|'${include}'|g'
            printf "${GREEN}Bat cau hinh Yoast Seo thanh cong.${NC}\n"
        fi
    else
        printf "${ALERT}\n"
    fi
}

_run
menu_wp