#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

_run(){
    ALERT=""
	select_domain
	check_mathseo=$(grep -rnw "${VHOST_DIR}/${domain}.conf" -e "rank_math_seo")

    if [ -n "${check_mathseo}" ]; then
        while true
        do
            read -r -p "Phat hien cau hinh Rank Math Seo. Ban co muon xoa cau hinh Rank Math Seo khong ? (y/n) " del_rankmath
            echo
            if [[ "${del_rankmath}" =~ ^([yY])$ ]]; then
                sed -i '/rank_math_seo/d' "${VHOST_DIR}"/"${domain}".conf
                break
            elif [[ "${del_yoast}" =~ ^([nN])$ ]]; then
                ALERT=$(printf "${RED}Ban da chon khong xoa config Yoast Seo. Huy cau hinh Rank Math Seo.${NC}\n")
                break
            else
                printf "${RED}Gia tri ban nhap khong chinh xac vui long nhap lai.${NC}\n"
            fi
        done
    fi

    if [[ -z "${ALERT}" ]]; then
        check_yoastseo=$(grep -rnw "${VHOST_DIR}/${domain}.conf" -e "yoast_seo")
        sed -i '/plugins_seo=/d' "${USER_DIR}"/."${domain}".conf
        if [[  -n "${check_yoastseo}" ]]; then
            sed -i 'yoast_seo/d' "${VHOST_DIR}"/"${domain}".conf
            echo "plugins_seo=" >> "${USER_DIR}"/."${domain}".conf
            restart_service
            printf "${GREEN}Tat cau hinh Yoast Seo thanh cong.${NC}\n"
        else
            echo "plugins_seo=yoast_seo" >> "${USER_DIR}"/."${domain}".conf
            sed -i '/index.php/a include /etc/nginx/wordpress/yoast_seo.conf;' "${VHOST_DIR}"/"${domain}".conf
            restart_service
            printf "${GREEN}Bat cau hinh Yoast Seo thanh cong.${NC}\n"
        fi
    else
        printf "${ALERT}\n"
    fi
}

_run
wp_menu_advanced