#!/bin/bash

#################################################
# Auto Install & Optimize LEMP Stack on CentOS 7#
# Version: 1.0                                  #
# Author: Sanvv - HOSTVN Technical              #
# Website: https://hostvn.net                   #
#                                               #
# Please don't remove copyright. Thank!         #
#################################################

CURL_TIMEOUTS='--max-time 20 --connect-timeout 20'
CFINCLUDEFILE='/etc/nginx/extra/cloudflare.conf'

CFIPS=$(/usr/bin/curl -4s "${CURL_TIMEOUTS}" https://www.cloudflare.com/ips-v4/)
CFIP6S=$(/usr/bin/curl -4s "${CURL_TIMEOUTS}" https://www.cloudflare.com/ips-v6/)

for ip in $CFIPS;
do
    if [[ "$(grep "$ip" /etc/csf/csf.allow >/dev/null 2>&1; echo $?)" = '1' ]] || [[ "$(grep "$ip" /etc/csf/csf.ignore >/dev/null 2>&1; echo $?)" = '1' ]]; then
        if [[ "$(ipcalc -c "$ip" >/dev/null 2>&1; echo $?)" -eq '0' ]]; then
            csf -a "$ip" cloudflare
            echo "$ip" >> /etc/csf/csf.ignore
        fi
    fi
done

if [[ "$(awk -F '= ' '/^IPV6 =/ {print $2}' /etc/csf/csf.conf | sed -e 's|\"||g')" = '1' ]]; then
	  for ip in $CFIP6S;
	  do
		    if [[ "$(grep "$ip" /etc/csf/csf.allow >/dev/null 2>&1; echo $?)" = '1' ]] || [[ "$(grep "$ip" /etc/csf/csf.ignore >/dev/null 2>&1; echo $?)" = '1' ]]; then
			      if [[ "$(ipcalc -c "$ip" >/dev/null 2>&1; echo $?)" -eq '0' ]]; then
				        csf -a "$ip" cloudflare
				        echo "$ip" >> /etc/csf/csf.ignore
			      fi
		    fi
	  done
fi

sed -i '/^ip/d' /etc/csf/csf.ignore

if [ -f "$CFINCLUDEFILE" ]; then
		cp -af "$CFINCLUDEFILE" "${CFINCLUDEFILE}.bak"
fi
echo > $CFINCLUDEFILE

for i in $CFIPS; do
    if [[ "$(ipcalc -c "$i" >/dev/null 2>&1; echo $?)" -eq '0' ]]; then
        echo "set_real_ip_from $i;" >> $CFINCLUDEFILE
    fi
done

if [[ -f /etc/sysconfig/network && "$(awk -F "=" '/NETWORKING_IPV6/ {print $2}' /etc/sysconfig/network | grep 'yes' >/dev/null 2>&1; echo $?)" = '0' ]]; then
		for i in $CFIP6S; do
        if [[ "$(ipcalc -c "$i" >/dev/null 2>&1; echo $?)" -eq '0' ]]; then
        		echo "set_real_ip_from $i;" >> $CFINCLUDEFILE
        fi
		done
else
		for i in $CFIP6S; do
        if [[ "$(ipcalc -c "$i" >/dev/null 2>&1; echo $?)" -eq '0' ]]; then
        		echo "#set_real_ip_from $i;" >> $CFINCLUDEFILE
        fi
		done
fi

echo "real_ip_header CF-Connecting-IP;" >> $CFINCLUDEFILE
if [[ "$(diff -u "${CFINCLUDEFILE}.bak" "$CFINCLUDEFILE" >/dev/null 2>&1; echo $?)" -ne '0' ]]; then
		service nginx reload >/dev/null 2>&1
fi
rm -rf "${CFINCLUDEFILE}.bak"