#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

input(){
	read -r -p "Nhap vao user muon doi mat khau: " ftp_user
	read -r -p "Nhap vao mat khau moi: " ftp_pwd
}


change_pass(){
	pure-pw passwd ftp_user <<EOF
${ftp_pwd}
${ftp_pwd}
EOF
	pure-pw mkdb
}

run(){
	select_domain
	set_var
	input

	if ! if_pureftpd_user_exists ftp_user; then
		ALERT=$(printf "${RED}FTP User khong ton tai.${NC}\n")
	fi

	validate_user

	if [[ -z "${ALERT}" ]]; then
		change_pass
	else
		printf "${ALERT}\n"
	fi
}

run
menu_ftp