#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
# Please don't copy copy under any circumstance for business reason! #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

input(){
	read -r -p "Nhap vao user muon doi mat khau: " ftp_user
	read -r -p "Nhap vao mat khau moi: " ftp_pwd
}


change_pass(){
	pure-pw passwd ftp_user <<EOF
${ftp_pwd}
${ftp_pwd}
EOF
	pure-pw mkdb
}

_run(){
	select_domain
	set_var
	input

	if ! if_pureftpd_user_exists ftp_user; then
		ALERT=$(printf "${RED}FTP User khong ton tai.${NC}\n")
	fi

	validate_user "${ftp_user}"

	if [[ -z "${ALERT}" ]]; then
		change_pass
		clear
		printf "${GREEN}Doi password FTP thanh cong.${NC}\n"
	else
	  clear
		printf "${ALERT}\n"
	fi
}

_run
menu_ftp