#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    current_port=$(grep -w "ftp_port" "${FILE_INFO}" | cut -f2 -d'=')
    csf_port=$(grep -w "csf_port" "${FILE_INFO}" | cut -f2 -d'=')
    admin_port=$(grep -w "admin_port" "${FILE_INFO}" | cut -f2 -d'=')
    ssh_port=$(grep -w "Port" /etc/ssh/sshd_config | cut -f2 -d" ")
}

input(){
    clear
    while true
    do
        read -r -p "Nhap vao Port moi [0 = Thoat]: " ftp_port
        echo
        if [[ ${ftp_port} =~ ^-?[0-9]+$ ]];
        then
            break
        else
            printf "%s\n" "${RED}Port khong dung dinh dang, vui long nhap lai.${NC}"
        fi
    done
}

check_port(){
    if [ -z "${ftp_port}" ]; then
        ALERT=$(printf "%s\n" "${RED}Ban chua nhap Port.${NC}")
    fi

    if [[ "${ftp_port}" == "${current_port}" ]]; then
        ALERT=$(printf "%s\n" "${RED}Port ban nhap trung vui Port FTP hien tai.${NC}")
    fi

    if [[ "${ftp_port}" == "${ssh_port}" || "${ftp_port}" == "${csf_port}" || "${ftp_port}" == "${admin_port}" ]]; then
        ALERT=$(printf "%s\n" "${RED}Port ban chon da duoc su dung. Vui long chon port khac.${NC}")
    fi

    check_se=$(semanage port -l | grep "${ftp_port}")
    if [[ "${ftp_port}" == "22" || "${ftp_port}" == "11211" || "${ftp_port}" == "6379" || -n  "${check_se}" ]]; then
        ALERT=$(printf "%s\n" "${RED}Port ban chon da duoc su dung. Vui long chon port khac.${NC}")
    fi

    if check_port_exists "${ftp_port}"; then
        ALERT=$(printf "%s\n" "${RED}Port da duoc su dung. Huy thay doi port SSH.${NC}")
    fi
}

_change_port(){
    sed -i '/Bind/d' /etc/pure-ftpd/pure-ftpd.conf
    sed -i '/ftp_port=/d' "${FILE_INFO}"
    sed -i "s/,${current_port}/,${ftp_port}/g" /etc/csf/csf.conf
    echo "Bind                         ${IPADDRESS},${ftp_port}" >>  /etc/pure-ftpd/pure-ftpd.conf
    echo "ftp_port=${ftp_port}" >>  "${FILE_INFO}"
    semanage port -a -t ftp_port_t -p tcp "${ftp_port}"
    if [[ "${current_port}" != "21" ]]; then
        semanage port -d -p tcp "${current_port}"
    fi
    csf -x
    csf -e
    systemctl restart pure-ftpd
}

_run(){
    set_var
    check_port

    if [[ -z "${ALERT}" ]]; then
        _change_port
        clear
        printf "%s\n" "${GREEN}Doi port FTP thanh cong.${NC}"
    else
      clear
      printf "%s\n" "${ALERT}"
    fi
}

ALERT=""
pureftpd_status="$(pgrep -f pure-ftpd)"
ftp_port=""

if [ -z "${pureftpd_status}" ]; then
    printf "%s\n" "${RED}PURE-FTP khong hoat dong hoac chua duoc cai dat. Vui long kiem tra lai.${NC}"
else
    input
    if [[ "${ftp_port}" == "0" ]]; then
        clear
        printf "%s\n" "${RED}Ban da chon huy thay doi Port.${NC}"
    else
        _run
    fi
fi

menu_ftp