#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
  # shellcheck disable=SC2154
	username=${domain//[-._]/}
}

input(){
	read -r -p "Nhap vao user muon tao: " ftp_user
	read -r -p "Nhap vao mat khau muon tao: " ftp_pwd
	read -r -p "Nhap vao duong dan duoc phep truy cap: " ftp_path
}

show_info(){
	printf "Port FTP: 21"
	printf "FTP User: %s\n" "${ftp_user}"
	printf "FTP Pass: %s\n" "${ftp_pwd}"
	sleep 3
}

create(){
	pure-pw useradd "${ftp_user}" -u "${username}" -g "${username}" -d "${ftp_path}" <<EOF
${ftp_pwd}
${ftp_pwd}
EOF
	pure-pw mkdb
}

_run(){
	select_domain

	set_var
	input

	if if_pureftpd_user_exists ftp_user; then
		ALERT=$(printf "${RED}User da ton tai.${NC}\n")
	fi

	if [[ ! -d "${ftp_path}" ]]; then
		ALERT=$(printf "${RED}Duong dan truy cap ban nhap khong ton tai.${NC}\n")
	fi

	validate_user ${ftp_user}

	if [[ -z "${ALERT}" ]]; then
		create
		show_info
	else
		printf "${ALERT}\n"
	fi
}

_run
menu_ftp