#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    pureftpd_status="$(pgrep -f pure-ftpd)"
    ftp_port=$(grep -w "ftp_port" "${FILE_INFO}" | cut -f2 -d'=');
    username=${domain//[-._]/}
}

input(){
	  read -r -p "Nhap vao user muon tao: " ftp_user
	  read -r -p "Nhap vao mat khau muon tao: " ftp_pwd
	  echo "Nhap vao duong dan duoc phep truy cap. VD: /home/example, /home/example/example.com/public_html"
	  read -r -p "Nhap duong dan: " ftp_path
}

show_info(){
    clear
    echo ""
    printf "Port FTP: %s\n" "${ftp_port}"
    printf "FTP User: %s\n" "${ftp_user}"
    printf "FTP Pass: %s\n" "${ftp_pwd}"
    sleep 3
    echo ""
}

create(){
	  pure-pw useradd "${ftp_user}" -u "${username}" -g "${username}" -d "${ftp_path}" <<EOF
${ftp_pwd}
${ftp_pwd}
EOF
	  pure-pw mkdb
	  systemctl restart pure-ftpd
}

_run(){
    ALERT=""
    select_domain

    set_var
    input

    if if_pureftpd_user_exists ftp_user; then
        ALERT=$(printf "${RED}User da ton tai.${NC}\n")
    fi

    if [ "${ftp_path}" == "/" ]; then
        ALERT=$(printf "${RED}Duong dan truy cap khong chinh xac.${NC}\n")
    fi

    if [[ ! -d "${ftp_path}" ]]; then
        ALERT=$(printf "${RED}Duong dan truy cap ban nhap khong ton tai.${NC}\n")
    fi

    validate_user "${ftp_user}"

    if [[ -z "${ALERT}" ]]; then
        create
        show_info
    else
        printf "${ALERT}\n"
    fi
}

pureftpd_status="$(pgrep -f pure-ftpd)"
if [ -z "${pureftpd_status}" ]; then
    printf "${RED}PURE-FTP khong hoat dong hoac chua duoc cai dat. Vui long kiem tra lai.${NC}\n"
else
    _run
    menu_ftp
fi

