#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

input(){
    while true
    do
        echo "Username khong chua ky tu dac biet va dai 5 ky tu tro len."
        read -r -p "Nhap vao user muon xoa [0 = Thoat]: " ftp_user
        echo
        if validate_user "${ftp_user}" || [ "${ftp_user}" == "0" ]; then
            break
        else
            clear
            printf "%s\n" "${RED}User khong dung dinh dang, vui long nhap lai.${NC}"
        fi
    done
}

_delete(){
    pure-pw userdel "${ftp_user}"
    pure-pw mkdb
    systemctl restart pure-ftpd
}

_run(){
    if [[ -f "/etc/pure-ftpd/pureftpd.passwd" ]]; then
        if ! if_pureftpd_user_exists "${ftp_user}"; then
            ALERT=$(printf "%s\n" "${RED}FTP User khong ton tai.${NC}")
        fi

        if [[ -z "${ALERT}" ]]; then
            _delete
            clear
            printf "%s\n" "${GREEN}Xoa FTP User thanh cong.${NC}"
        else
            clear
            printf "%s\n" "${ALERT}"
        fi
    else
        clear
        printf "%s\n" "${RED}Khong co user FTP nao ton tai tren VPS.${NC}"
    fi
}

ALERT=""
ftp_user=""
pureftpd_status="$(pgrep -f pure-ftpd)"

if [ -z "${pureftpd_status}" ]; then
    clear
    printf "%s\n" "${RED}PURE-FTP khong hoat dong hoac chua duoc cai dat. Vui long kiem tra lai.${NC}"
else
    input
    if [ "${ftp_user}" == "0" ]; then
        clear
        printf "%s\n" "${RED}Ban da huy hanh dong.${NC}"
    else
        _run
    fi
fi

menu_ftp