#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

input(){
	read -r -p "Nhap vao user muon xoa: " ftp_user
}

delete(){
	pure-pw userdel "${ftp_user}"
	pure-pw mkdb
	systemctl restart pure-ftpd
}

_run(){
    ALERT=""
	input
    if [[ -f "/etc/pure-ftpd/pureftpd.passwd" ]]; then
        if ! if_pureftpd_user_exists "${ftp_user}"; then
            ALERT=$(printf "${RED}FTP User khong ton tai.${NC}\n")
        fi

        validate_user "${ftp_user}"

        if [[ -z "${ALERT}" ]]; then
            delete
            printf "${GREEN}Xoa FTP User thanh cong.${NC}\n"
        else
            printf "${ALERT}\n"
        fi
    else
        printf "${RED}Khong co user FTP nao ton tai tren VPS.${NC}\n"
    fi
}

pureftpd_status="$(pgrep -f pure-ftpd)"

if [ -z "${pureftpd_status}" ]; then
    printf "${RED}PURE-FTP khong hoat dong hoac chua duoc cai dat. Vui long kiem tra lai.${NC}\n"
else
    _run
    menu_ftp
fi