#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

confirm(){
    while true
    do
        read -r -p "Ban muon cai dat PURE-FTPD ? (y/n) " promtp_ftp
        echo
        if [[ "${promtp_ftp}" =~ ^([yY])$ || "${promtp_ftp}" =~ ^([nN])$ ]]; then
            break
        else
            printf "%s\n"  "${RED}Gia tri khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done
}

install(){
    if [ -f "/etc/pure-ftpd/pure-ftpd.conf" ]; then
        printf "%s\n" "${RED}PURE-FTPD da duoc cai dat truoc do. Ban khong can cai dat lai.${NC}"
    else
        yum -y install pure-ftpd
        PURE_CONF_PATH="/etc/pure-ftpd"
        if [[ -f "${PURE_CONF_PATH}/pure-ftpd.conf" ]]; then
            mv "${PURE_CONF_PATH}"/pure-ftpd.conf "${PURE_CONF_PATH}"/pure-ftpd.conf.orig
        fi

        cat >> "${PURE_CONF_PATH}/pure-ftpd.conf" << EOpure_ftpd_conf
############################################################
#                                                          #
#             Configuration file for pure-ftpd             #
#                                                          #
############################################################
ChrootEveryone               yes
BrokenClientsCompatibility   no
MaxClientsNumber             50
Daemonize                    yes
MaxClientsPerIP              15
VerboseLog                   no
DisplayDotFiles              yes
AnonymousOnly                no
NoAnonymous                  yes
SyslogFacility               ftp
DontResolve                  yes
MaxIdleTime                  15
PureDB                       /etc/pure-ftpd/pureftpd.pdb
LimitRecursion               10000 8
AnonymousCanCreateDirs       no
MaxLoad                      4
PassivePortRange             35000 35999
AntiWarez                    yes
#Bind                        ${IPADDRESS},21
Umask                        133:022
MinUID                       99
AllowUserFXP                 yes
AllowAnonymousFXP            no
ProhibitDotFilesWrite        no
ProhibitDotFilesRead         no
AutoRename                   no
AnonymousCantUpload          no
AltLog                       stats:/var/log/pureftpd.log
PIDFile                      /run/pure-ftpd.pid
CallUploadScript             no
MaxDiskUsage                 99
CustomerProof                yes
TLS                          1
TLSCipherSuite               HIGH:MEDIUM:+TLSv1:!SSLv2:+SSLv3
CertFile                     /etc/pure-ftpd/ssl/pure-ftpd.pem
ExtCert                      /var/run/pure-certd.sock
EOpure_ftpd_conf

        mkdir -p "${PURE_CONF_PATH}"/ssl
        openssl dhparam -out "${PURE_CONF_PATH}"/ssl/pure-ftpd-dhparams.pem 2048
        openssl req -x509 -days 7300 -sha256 -nodes -subj "/C=VN/ST=Ho_Chi_Minh/L=Ho_Chi_Minh/O=Localhost/CN=${IPADDRESS}" -newkey rsa:2048 -keyout "${PURE_CONF_PATH}"/ssl/pure-ftpd.pem -out "${PURE_CONF_PATH}"/ssl/pure-ftpd.pem
        chmod 600 "${PURE_CONF_PATH}"/ssl/pure-ftpd*.pem
        touch /etc/pure-ftpd/pureftpd.passwd
        systemctl start pure-ftpd
        systemctl enable pure-ftpd
        clear
        printf "%s\n" "${GREEN}Cai dat PURE-FTPD thanh cong.${NC}"
    fi
}

promtp_ftp=""
confirm
if [[ "${promtp_ftp}" =~ ^([yY])$ ]]; then
    install
else
    clear
    printf "%s\n" "${RED}Ban da huy cai dat PURE-FTPD.${NC}"
fi

menu_ftp