#!/bin/bash

#################################################
# Auto Install & Optimize LEMP Stack on CentOS 7#
# Version: 1.0                                  #
# Author: Sanvv - HOSTVN Technical              #
#                                               #
# Please don't remove copyright. Thank!         #
#################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
	username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');

	if [[ -z "${username}" ]]; then
		username=${domain//[-._]/}
	fi

	db_name=$(grep "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');

	if [[ -z "${db_name}" ]]; then
		read -r -p "Nhap vao ten Database muon sao luu: " db_name
	fi
}

backup(){
	if [[ -f "/home/backup/${DATE}/${domain}/${db_name}.sql" ]]; then
		rm -rf /home/backup/"${DATE}"/"${domain}"/"${db_name}".sql
	fi

	cd_dir /home/backup/"${DATE}"/"${domain}"
	mysqldump -uadmin -p"${mysql_pwd}" "${db_name}" > "${db_name}".sql
	clear
	printf "${GREEN}Sao luu du lieu thanh cong.${NC}\n"
}

run(){
	select_domain

	set_var
	if_is_wordpress "$username" "$domain"

	if ! if_db_exists "${db_name}" ;
	then
		ALERT=$(printf "${RED}Database khong ton tai.${NC}")
	fi

	if [ -z "${ALERT}" ]; then
		make_backup_dir "$domain"
		backup
	else
		clear
		printf "${ALERT}\n"
	fi
}

run
menu_database