#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

echo "------------------"
echo "Doi Password Mysql"
echo "------------------"
echo ""

input(){
	read -r -p "Nhap Mysql user: " db_user
	read -r -p "Xac nhan thay doi mat khau cho user ${db_user}? (y/n): " confirm
	password=$(gen_pass "$@")
}

validate(){
	if [[ "${db_user}" = "" ]]; then
		ALERT=$(printf "${RED}Mysql user khong duoc de trong.${NC}\n")
	fi

	if [[ "${password}" = "" ]]; then
		ALERT=$(printf "${RED}Mat khau khong duoc de trong.${NC}\n")
	fi

	if [ "${db_user}" = "admin" ]; then
	    ALERT=$(printf "${RED}Ban khong duoc phep thay doi mat khau tai khoan admin.${NC}\n")
	fi
}

change_pass(){
	if [[ "${confirm}" =~ ^([yY])$ ]]; then
		printf "${GREEN}Dang thay đoi mat khau...${NC}\n"
		sleep 1
	    mysql -e "SET PASSWORD FOR '${db_user}'@'localhost' = PASSWORD('${password}')"
	    clear
	    printf "${GREEN}Thay doi mat khau thanh cong.${NC}\n"
    else
    	clear
    	printf "${GREEN}Ban da huy thay doi mat khau.${NC}\n"
	fi
}

run(){
	input
	validate

	if ! if_mysql_user_exists "${db_user}";
	then
		ALERT=$(printf "${RED}Mysql User khong ton tai.${NC}")
	fi

	if [ -z "${ALERT}" ]; then
		change_pass
	else
		clear
		printf "${ALERT}\n"
	fi
}

run
menu_database