#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

printf "%s==================%s\n" "${GREEN}" "${NC}"
printf "%sDoi Password Mysql%s\n" "${GREEN}" "${NC}"
printf "%s==================%s\n" "${GREEN}" "${NC}"


input(){
    while true
    do
        echo "Username khong chua ky tu dac biet va dai 5 ky tu tro len."
        read -r -p "Nhap Mysql user [0 = Thoat]: " db_user
        echo
        if validate_user "${db_user}" || [ "${db_user}" == "0" ]; then
            break
        else
            printf "%s\n"  "${RED}Gia tri khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done

    if [ "${db_user}" != "0" ]; then
        while true
        do
            read -r -p "Xac nhan thay doi mat khau cho user ${db_user}? (y/n): " confirm
            echo
            if [[ "${confirm}" =~ ^([yY])$ || "${confirm}" =~ ^([nN])$ ]]; then
                break
            else
                printf "%s\n"  "${RED}Gia tri khong chinh xac. Vui long nhap lai.${NC}"
            fi
        done
        password=$(gen_pass "$@")
    fi
}

validate(){
    if [ "${db_user}" = "admin" ]; then
        ALERT=$(printf "%s\n" "${RED}Ban khong duoc phep thay doi mat khau tai khoan admin.${NC}")
    fi
}

_change_pass(){
    if [[ "${confirm}" =~ ^([yY])$ ]]; then
        printf "%s\n" "${GREEN}Dang thay đoi mat khau...${NC}"
        sleep 1
        mysql -uadmin -p"${mysql_pwd}" -e "SET PASSWORD FOR '${db_user}'@'localhost' = PASSWORD('${password}')"

        string=$(grep -rnw "${USER_DIR}" -e "${db_user}" | cut -f1 -d':')
        if [ -n "${string}" ]; then
            for i in ${string} ; do
                sed -i '/db_password/d' "${i}"
                echo "db_password=${password}" >> "${i}"
            done
        fi

        clear
        printf "%s\n" "${GREEN}Thay doi mat khau thanh cong.${NC}"
        printf "%s\n" "${GREEN}Mat khau moi la:${NC} ${RED}${password}${NC}"
    else
        clear
        printf "%s\n" "${GREEN}Ban da huy thay doi mat khau.${NC}"
    fi
}

_run(){
    input "$@"

    if [ "${db_user}" == "0" ]; then
        clear
        printf "%s\n" "${GREEN}Ban da huy thay doi mat khau.${NC}"
    else
        validate

        if ! if_mysql_user_exists "${db_user}";
        then
            ALERT=$(printf "%s\n" "${RED}Mysql User khong ton tai.${NC}")
        fi

        if [ -z "${ALERT}" ]; then
            _change_pass
        else
            clear
            printf "%s\n" "${ALERT}"
        fi
    fi
}

ALERT=""
db_user=""
confirm=""
string=""
_run "$@"
menu_database