#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

input(){
	read -r -p "1. Nhap ten database: " db_name
	read -r -p "2. Nhap Mysql User: " db_user
	read -r -p "Xac nhan them database? (y/n): " promtp_db
	password=$(gen_pass "$@")
}

validate_input(){
	if [ "$db_name" = "" ] || [ "$db_user" = "" ] || [ "$password" = "" ]; then
	    ALERT=$(printf "${RED}Vui long nhap day du thong tin.${NC}\n")
	fi
}

validate(){
	validate_input
	check_database "${db_name}"
	check_mysql_user "${db_user}"
}

create_db(){
	printf "${GREEN}Dang tao database moi...${NC}\n"
	mysql -e "CREATE DATABASE IF NOT EXISTS ${db_name}"
  mysql -e "CREATE USER IF NOT EXISTS '${db_user}'@'localhost' IDENTIFIED BY '$password'"
  mysql -e "GRANT ALL PRIVILEGES ON ${db_name}.* TO '${db_user}'@'localhost'"
  mysql -e "FLUSH PRIVILEGES"
  clear
  printf "${GREEN}Da them databse thanh cong.${NC}\n"
}

show_info(){
	clear
    printf "DB_Name    : s%\n" "${RED}${db_name}${NC}"
    printf "DB_User    : s%\n" "${RED}${db_user}${NC}"
    printf "DB_Password: s%\n" "${RED}${password}${NC}"
    echo ""
    sleep 3
}

_run(){
    ALERT=""
	input "$@"
	if [[ ${promtp_db} =~ ^([yY])$  ]]; then
	   validate

    if [ -z "${ALERT}" ]; then
      create_db
      show_info
    else
      clear
      printf "${ALERT}\n"
    fi
  else
     printf "${RED}Ban da huy them database.${NC}\n"
	fi
}

_run "$@"
menu_database