#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

echo "------------"
echo "Xoa database"
echo "------------"
echo ""

list_db(){
	echo "Danh sach Database tren VPS"
	#https://stackoverflow.com/a/50053525
	#https://dba.stackexchange.com/a/69667
	mysql -e "SHOW DATABASES WHERE \`Database\` NOT IN('information_schema', 'phpmyadmin', 'mysql', 'performance_schema')"
	echo
}

input(){
	read -r -p "Nhap ten database ban can xoa: " db_name
	read -r -p "Xac nhan xoa database? (y/n): " prompt_destroy
}

validate(){
	if [ -z "${db_name}" ]; then
	    ALERT=$(printf "${RED}Database khong duoc bo trong.${NC}\n")
	fi
}

delete_db(){
	if [[ "${prompt_destroy}" =~ ^([yY])$ ]]; then
		printf "${GREEN}Dang tien hanh xoa database...${NC}\n"
		sleep 1
	    mysql -e "DROP DATABASE IF EXISTS ${db_name}"
	    clear
	    printf "${GREEN}Xoa database thanh cong.${NC}\n"
    else
    	clear
    	printf "${RED}Ban da huy xoa database.${NC}\n"
	fi
}

_run(){
    ALERT=""
	list_db
	input
	validate

	if [ -z "${ALERT}" ]; then
		delete_db
	else
		clear
		printf "${ALERT}\n"
	fi
}

_run
menu_database