#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_run(){
    user=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    db_name=$(grep -w "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')

    cd_dir /home/"${user}"/"${domain}"/public_html
    sql_files=()
    for entry_sql in *.{sql,sql.gz}; do
        if [ -f "${entry_sql}" ]; then
            sql_files+=("${entry_sql}")
        fi
    done

    if [ ${#sql_files[@]} -ne 0 ]; then
        echo "Chon file database muon khoi phuc"
        PS3="Nhap vao lua chon cua ban [0 = Thoat]: "
        select opt_sql in "${sql_files[@]}"
        do
            sql=$opt_sql
            break
        done
        if [ -z "${sql}" ]; then
            printf "%s\n" "${RED}Ban da chon huy thao tac.${NC}"
        else
            empty_db
            mysql -uadmin -p"${mysql_pwd}" "${db_name}" < "${sql}"
            clear
            printf "%s\n" "${GREEN}Import Database thanh cong. Vui long xoa file sql vi ly do bao mat.${NC}"
        fi
    else
        printf "%s\n" "${RED}Khong tim thay file sql nao trong public_html.${NC}"
    fi
}

ALERT=""
domain=""
select_domain

if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac.${NC}"
else
    if [ -z "${ALERT}" ]; then
        _run
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
fi

menu_database
