#!/bin/bash

#################################################
# Auto Install & Optimize LEMP Stack on CentOS 7#
# Version: 1.0                                  #
# Author: Sanvv - HOSTVN Technical              #
#                                               #
# Please don't remove copyright. Thank!         #
#################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
	username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
	db_name=$(grep "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

confirm_restore(){
	read -r -p "Ban muon khoi phuc du lieu ? (y\n) " promt_restore
}

restore(){
	cd_dir /home/backup/"${date}"/"${domain}"
	mysql -uadmin -p"${mysql_pwd}" "${db_name}" < "${db_name}".sql
}

run(){
	confirm_restore
	if [[ "${promt_restore}" =~ ^([yY])$ ]]; then
		list_backup
		select_domain
		if_is_wordpress "${username}" "${domain}"
		check_backup_exists

		if ! check_backup_empty "${date}" "${domain}";
		then
			ALERT="${RED}Ten mien nay khong co backup.${NC}\n"
		fi

		if [ ! -f "/home/backup/${date}/${domain}/${domain}.sql" ]; then
			ALERT="${RED}Ten mien nay khong co backup.${NC}\n"
		fi

		if [[ -z "${ALERT}" ]]; then
			set_var
			empty_db
			restore
			clear
			printf "${GREEN}Khoi phuc du lieu thanh cong.${NC}\n"
		else
			clear
			printf "${ALERT}\n"
		fi
	else
		clear
		printf "${RED}Ban da chon huy khoi phuc du lieu.${NC}\n"
	fi
}

run
menu_backup