#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

printf "${GREEN}======================${NC}\n"
printf "${GREEN}Phan quyen Chown/Chmod${NC}\n"
printf "${GREEN}======================${NC}\n"
echo

if [ "$(ls -At "${USER_DIR}")" ]; then
    clear
    echo "Dang phan quyen cho cac domain:"
    sleep 1
    cd_dir "/var/hostvn/users"
    for entry in .*.conf; do
        domain=$( echo "$entry" | sed 's/^.//' | sed 's/.conf//')
        username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
        chmod 711 /home
        chmod 711 /home/"${username}"
        chmod 711 /home/"${username}"/"${domain}"
        chmod 711 /home/"${username}"/"${domain}"/logs
        chmod 755 /home/"${username}"/"${domain}"/public_html
        chown -R "${username}":"${username}" /home/"${username}"
    done
    printf "${GREEN}Phan quyen hoan tat.${NC}\n"
else
    clear
    printf "${RED}Khong co Domain nao ton tai tren he thong.${NC}\n"
    menu_permission
fi

# shellcheck disable=SC2034
CHOICE=0
menu_permission