#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

printf "%s\n" "${GREEN}======================${NC}"
printf "%s\n" "${GREEN}Phan quyen Chown/Chmod${NC}"
printf "%s\n" "${GREEN}======================${NC}"

action(){
    while true
    do
        read -r -p "Xac nhan phan quyen cho ten mien: ${domain}? (y/n): " confirm
        echo
        if [[ "${confirm}" =~ ^([yY])$ || "${confirm}" =~ ^([nN])$ ]]; then
            break
        else
            printf "%s\n"  "${RED}Gia tri khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done

    if [[ "$confirm" =~ ^([yY])$ ]]; then
        #https://www.howtoforge.com/tutorial/linux-grep-command/
        #https://stackoverflow.com/a/6284370
        username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
        chmod 711 /home
        chmod 711 /home/"${username}"
        chmod 711 /home/"${username}"/"${domain}"
        chmod 711 /home/"${username}"/"${domain}"/logs
        chmod 755 /home/"${username}"/"${domain}"/public_html
        find /home/"${username}"/"${domain}"/public_html/ -type d -print0 | xargs -I {} -0 chmod 0755 {}
        find /home/"${username}"/"${domain}"/public_html/ -type f -print0 | xargs -I {} -0 chmod 0644 {}
        chown -R "${username}":"${username}" /home/"${username}"
        clear
        printf "%s\n" "${GREEN}Da phan quyen cho website: ${domain}.${NC}"
    else
        clear
        printf "%s\n" "${RED}Huy phan quyen.${NC}"
    fi
}

_run(){
    select_domain

    if [ -n "${domain}" ]; then
       action
    else
        clear
        printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
    fi
}

confirm=""
domain=""
_run
menu_permission