#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

echo "======================"
echo "Phan quyen Chown/Chmod"
echo "======================"
echo

action(){
    read -r -p "Xac nhan phan quyen cho ten mien: ${domain}? (y/n): " confirm
    if [[ "$confirm" =~ ^([yY])$ ]]; then
        #https://www.howtoforge.com/tutorial/linux-grep-command/
        #https://stackoverflow.com/a/6284370
        username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
        chmod 711 /home
        chmod 711 /home/"${username}"
        chmod 711 /home/"${username}"/"${domain}"
        chmod 711 /home/"${username}"/"${domain}"/logs
        chmod 755 /home/"${username}"/"${domain}"/public_html
        chown -R "${username}":"${username}" /home/"${username}"
        clear
        printf "${GREEN}Da phan quyen cho website: ${domain}.${NC}\n"
    else
        clear
        printf "${RED}Huy phan quyen.${NC}\n"
    fi
}

_run(){
    ALERT=""
    select_domain

    if [ -z "${ALERT}" ]; then
        action
    else
        clear
        printf "${ALERT}\n"
    fi
}

_run
menu_permission