#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    user=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    db_name=$(grep -w "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

create_sftp_connect(){
    while true
    do
        read -r -p "Nhap vao IP VPS moi [0 = Thoat]: " new_vps_ip
        echo
        if valid_ip "${new_vps_ip}" || [ "${new_vps_ip}" == "0" ]; then
            break
        else
            clear
            printf "%s\n"  "${RED}IP khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done

    if [ "${new_vps_ip}" != "0" ]; then
        while true
        do
            read -r -p "Nhap vao Port SSH cua VPS moi [0 = Thoat]: " ssh_port
            echo
            if [[ "${ssh_port}" =~ ^[0-9]+$ ]]; then
                break
            else
                clear
                printf "%s\n"  "${RED}Port SSH khong chinh xac. Vui long nhap lai.${NC}"
            fi
        done

        if [ "${ssh_port}" != 0 ]; then
            while true
            do
                read -r -p "Nhap vao Mat khau SSH cua VPS moi [0 = Thoat]: " ssh_pwd
                echo
                if [[ -n "${ssh_pwd}" ]]; then
                    break
                else
                    clear
                    printf "%s\n"  "${RED}Mat khau SSH la bat buoc.${NC}"
                fi
            done

            if [ "${ssh_pwd}" != 0 ]; then
#                remote_name=${new_vps_ip//[.]/}
                remote_name=${new_vps_ip}
                encrypt_pwd=$(rclone obscure "${ssh_pwd}" --crypt-password string)

                if [[ -n "${new_vps_ip}" && -n "${ssh_port}" && -n "${ssh_pwd}" ]]; then
                    rclone config create "${remote_name}" sftp host "${new_vps_ip}" user root port "${ssh_port}" pass "${encrypt_pwd}"
                fi
            fi
        fi
    fi
}

backup(){
    if [[ ! -d "/home/backup/${domain}" ]]; then
        mkdir -p /home/backup/"${domain}"
    fi
    if [ -f "/home/backup/${domain}/${db_name}.sql" ]; then
        rm -rf /home/backup/"${domain}"/"${db_name}".sql
    fi
    if [ -f "/home/backup/${domain}/${db_name}.sql.gz" ]; then
        rm -rf /home/backup/"${domain}"/"${db_name}".sql.gz
    fi
    if [ -f "/home/backup/${domain}/${domain}.tar.gz" ]; then
        /home/backup/"${domain}"/"${domain}".tar.gz
    fi
    cd_dir /home/backup/"${domain}"
    mysqldump -uadmin -p"${mysql_pwd}" "${db_name}" | gzip > "${db_name}".sql.gz

    cd_dir /home/"${user}"/"${domain}"
    tar -cpzvf /home/backup/"${domain}"/"${domain}".tar.gz public_html \
                --exclude "public_html/wp-content/cache" --exclude "public_html/storage/framework/cache" \
                --exclude "public_html/storage/framework/view"

    rclone sync /home/backup/"${domain}" "${remote_name}":/home/backup/"${domain}"
    clear
    echo
    printf "%s\n" "${GREEN}Bat dau qua trinh chuyen du lieu...${NC}"
    printf "%s\n" "${GREEN}Thoi gian phu thuoc vao dung luong va toc do mang tren vps.${NC}"
    printf "%s\n" "${GREEN}Vui long khong tat SSH cho toi khi qua trinh hoan tat.${NC}"
    echo
}

select_remote(){
    sftp_remotes=()
    # shellcheck disable=SC2207
    list_remote=( $(rclone listremotes) )
    for entry in "${list_remote[@]}"; do
        rt=${entry//:}
        if valid_ip "${rt}"; then
            sftp_remotes+=("${rt}")
        fi
    done

    if [ ${#sftp_remotes[@]} -ne 0 ]; then
        echo "Lua chon VPS chua backup"
        PS3="Nhap vao lua chon cua ban [0 = Thoat]: "

        select opt_sftp in "${sftp_remotes[@]}"
        do
            case $opt_sftp in
                $opt) remote_name=${opt_sftp}; break ;;
            esac
        done
    else
        create_sftp_connect
    fi
}

_run(){
    set_var
    select_remote

    if [ -z "${remote_name}" ]; then
        clear
        printf "%s\n" "${RED}Huy tao thao tac.${NC}"
    else
        backup
        clear
        printf "%s\n" "${GREEN}Sao luu du lieu thanh cong.${NC}"
        printf "%s\n" "${GREEN}Ban co the tim thay ban sao luu tai:\n /home/backup/${domain}${NC}"
    fi
}

domain=""
select_domain

if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
else
    if [ -z "${ALERT}" ]; then
        _run
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
fi

select_backup