#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
	username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
	db_name=$(grep "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

backup(){
	if [[ ! -d "/home/backup/${DATE}/${domain}" ]]; then
		mkdir -p /home/backup/"${DATE}"/"${domain}"
	fi
  if [ -f "/home/backup/${DATE}/${domain}/${db_name}.sql" ]; then
	    rm -rf /home/backup/"${DATE}"/"${domain}"/"${db_name}".sql
	fi
	if [ -f "/home/backup/${DATE}/${domain}/${domain}.tar.gz" ]; then
	    /home/backup/"${DATE}"/"${domain}"/"${domain}".tar.gz
	fi
	cd_dir /home/backup/"${DATE}"/"${domain}"
	mysqldump -uadmin -p"${mysql_pwd}" "${db_name}" > "${db_name}".sql

	cd_dir /home/"${username}"/"${domain}"
	tar -cpzvf /home/backup/"${DATE}"/"${domain}"/"${domain}".tar.gz public_html
}

_run(){
	select_domain

	if [[ -z "${ALERT}" ]]; then
		set_var
		backup
		clear
		printf "${GREEN}Sao luu du lieu thanh cong.${NC}\n"
		printf "${GREEN}Ban co the tim thay ban sao luu tai:\n /home/backup/${DATE}/${domain}/${domain}${NC}\n"
	else
	  clear
		printf "${ALERT}\n"
	fi
}

_run
select_backup