#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    db_name=$(grep -w "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

backup(){
    if [[ ! -d "/home/backup/${CURRENT_DATE}/${domain}" ]]; then
        mkdir -p /home/backup/"${CURRENT_DATE}"/"${domain}"
    fi
    if [ -f "/home/backup/${CURRENT_DATE}/${domain}/${db_name}.sql" ]; then
        rm -rf /home/backup/"${CURRENT_DATE}"/"${domain}"/"${db_name}".sql
    fi
    if [ -f "/home/backup/${CURRENT_DATE}/${domain}/${domain}.tar.gz" ]; then
        /home/backup/"${CURRENT_DATE}"/"${domain}"/"${domain}".tar.gz
    fi
    cd_dir /home/backup/"${CURRENT_DATE}"/"${domain}"
    mysqldump -uadmin -p"${mysql_pwd}" "${db_name}" > "${db_name}".sql

    cd_dir /home/"${username}"/"${domain}"
    tar -cpzvf /home/backup/"${CURRENT_DATE}"/"${domain}"/"${domain}".tar.gz public_html
}

_run(){
    set_var
    backup
    clear
    printf "%s\n" "${GREEN}Sao luu du lieu thanh cong.${NC}"
    printf "%s\n" "${GREEN}Ban co the tim thay ban sao luu tai:\n /home/backup/${CURRENT_DATE}/${domain}${NC}"
}

domain=""
select_domain

if [ -z "${domain}" ]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
else
   _run
fi

select_backup
