#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
	username=$(grep "username" "${USER_DIR}/.${domain:?}.conf" | cut -f2 -d'=')
}

backup(){
	cd_dir /home/"${username}"/"${domain}"
	if [[ ! -d "/home/backup/${DATE}/${domain}" ]]; then
		mkdir -p /home/backup/"${DATE}"/"${domain}"
	fi
	if [ -f "/home/backup/${DATE}/${domain}/${domain}.tar.gz" ]; then
	    /home/backup/"${DATE}"/"${domain}"/"${domain}".tar.gz
	fi
	tar -cpzvf /home/backup/"${DATE}"/"${domain}"/"${domain}".tar.gz public_html
}

run(){
	select_domain

	if [[ -z "${ALERT}" ]]; then
		set_var
		backup
		printf "${GREEN}Sao luu ma nguon thanh cong.${NC}\n"
		printf "${GREEN}Ban co the tim thay ban sao luu tai:\n /home/backup/${DATE}/${domain}/${domain}${NC}\n"
	else
		printf "${ALERT}\n"
	fi
}

run
select_backup