#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

confirm_delete(){
    while true
    do
        read -r -p "Ban muon xoa backup ? (y/n) " promt_delete
        echo
        if [[ "${promt_delete}" =~ ^([yY])$ || "${promt_delete}" =~ ^([nN])$ ]]; then
            break
        else
            printf "%s\n"  "${RED}Gia tri khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done
}

_delete(){
    rm -rf /home/backup/"${date}"/"${domain}"/*
}

_run(){
    confirm_delete

    if [[ "${promt_delete}" =~ ^([yY])$ ]]; then
        list_backup

        if [ -z "${date}" ]; then
            clear
            printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
        else
            if [ -z "${domain}" ]; then
                clear
                printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
            else
                if ! check_backup_empty "${date}" "${domain}"; then
                    ALERT="%s\n" "${RED}Ten mien nay khong co backup.${NC}"
                fi

                if [[ -z "${ALERT}" ]]; then
                    _delete
                    clear
                    printf "%s\n" "${GREEN}Xoa backup thanh cong.${NC}"
                else
                    clear
                    printf "%s\n" "${ALERT}"
                fi
            fi
        fi
    else
        clear
        printf "%s\n" "${RED}Ban da huy xoa backup.${NC}"
    fi
}

if [[ $(ls -A "${USER_DIR}") ]]; then
    ALERT=""
    promt_delete="n"
    date=""
    domain=""
    _run

else
    printf "%s\n" "${RED}Khong co ten mien nao tren VPS.${NC}"
fi

menu_backup