#!/bin/bash

#################################################
# Auto Install & Optimize LEMP Stack on CentOS 7#
# Version: 1.0                                  #
# Author: Sanvv - HOSTVN Technical              #
#                                               #
# Please don't remove copyright. Thank!         #
#################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

confirm_delete(){
	read -r -p "Ban muon xoa backup ? (y\n) " promt_delete
}

delete(){
	rm -rf /home/backup/"${date}"/"${domain}"/*
}

_run(){
	confirm_delete

	if [[ "${promt_delete}" =~ ^([yY])$ ]]; then
		list_backup
		select_domain

		if ! check_backup_empty "${date}" "${domain}";
		then
			ALERT="${RED}Ten mien nay khong co backup.${NC}\n"
		fi

		if [[ -z "${ALERT}" ]]; then
			delete
			clear
			printf "${GREEN}Xoa backup thanh cong.${NC}\n"
		else
			printf "${ALERT}\n"
		fi
	else
	  clear
		printf "${RED}Ban da huy xoa backup.${NC}\n"
	fi
}

_run
menu_backup