#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

confirm_delete(){
	read -r -p "Ban muon xoa backup ? (y/n) " promt_delete
}

delete(){
	rm -rf /home/backup/"${date}"/"${domain}"/*
}

_run(){
	confirm_delete

	if [[ "${promt_delete}" =~ ^([yY])$ ]]; then
	    ALERT=""
		list_backup
		select_domain

		if ! check_backup_empty "${date}" "${domain}";
		then
			ALERT="${RED}Ten mien nay khong co backup.${NC}\n"
		fi

		if [[ -z "${ALERT}" ]]; then
			delete
			clear
			printf "${GREEN}Xoa backup thanh cong.${NC}\n"
		else
			printf "${ALERT}\n"
		fi
	else
	  clear
		printf "${RED}Ban da huy xoa backup.${NC}\n"
	fi
}

_run
menu_backup