#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
	username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
	db_name=$(grep -w "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

confirm_restore(){
	read -r -p "Ban muon khoi phuc du lieu ? (y\n) " promt_restore
}

restore_source(){
	if [[ ! -d "/home/${username}/${domain}/public_html" ]]; then
		mkdir -p /home/"${username}"/"${domain}"/public_html
	fi
	rm -rf /home/"${username}"/"${domain}"/public_html/*
	tar xvzf /home/backup/"${date}"/"${domain}"/"${domain}".tar.gz -C /home/"${username}"/"${domain}"/
	chown -R "${username}":"${username}" /home/"${username}"
}

restore_db(){
	cd_dir /home/backup/"${date}"/"${domain}"
	mysql -uadmin -p"${mysql_pwd}" "${db_name}" < "${db_name}".sql
}

_run(){
	confirm_restore

	if [[ "${promt_restore}" =~ ^([yY])$ ]]; then
	    ALERT=""
		list_backup
		select_domain
        set_var
		if_is_wordpress "${username}" "${domain}"
		check_backup_exists "${date}" "${domain}"

		if ! check_backup_empty "${date}" "${domain}";
		then
			ALERT="${RED}Ten mien nay khong co backup.${NC}\n"
		fi

		if [ ! -f "/home/backup/${date}/${domain}/${domain}.tar.gz" ]; then
			ALERT="${RED}Ten mien nay khong co backup.${NC}\n"
		fi

		if [ ! -f "/home/backup/${date}/${domain}/${db_name}.sql" ]; then
			ALERT="${RED}Ten mien nay khong co backup.${NC}\n"
		fi

		if [ -z "${ALERT}" ]; then

			restore_source
			empty_db
			restore_db
			clear
			printf "${GREEN}Khoi phuc du lieu thanh cong.${NC}\n"
		else
			clear
			printf "${ALERT}\n"
		fi
	else
		clear
		printf "${RED}Ban da chon huy khoi phuc du lieu.${NC}\n"
	fi
}

_run
menu_backup
