#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
	username=$(grep "username" "${USER_DIR}/.${domain:?}.conf" | cut -f2 -d'=')
	db_name=$(grep "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

confirm_restore(){
	read -r -p "Ban muon khoi phuc du lieu ? (y\n) " promt_restore
}

restore_source(){
	if [[ ! -d "/home/${username}/${domain}/public_html" ]]; then
		mkdir -p /home/"${username}"/"${domain}"/public_html
	fi
	rm -rf /home/"${username}"/"${domain}"/public_html/*
	tar xvzf /home/backup/"${date:?}"/"${domain}"/"${domain}".tar.gz -C /home/"${username}"/"${domain}"/
	chown -R "${username}":"${username}" /home/"${username}"
}

restore_db(){
	cd_dir /home/backup/"${date}"/"${domain}"
	mysql -uadmin -p"${mysql_pwd:?}" "${db_name}" < "${db_name}".sql
}

run(){
	confirm_restore

	if [[ "${promt_restore}" =~ ^([yY])$ ]]; then
		list_backup
		select_domain
    set_var
		if_is_wordpress "${username}" "${domain}"
		check_backup_exists "${date}" "${domain}"

		if ! check_backup_empty "${date}" "${domain}";
		then
			ALERT="${RED}Ten mien nay khong co backup.${NC}\n"
		fi

		if [ ! -f "/home/backup/${date}/${domain}/${domain}.tar.gz" ]; then
			ALERT="${RED}Ten mien nay khong co backup.${NC}\n"
		fi

		if [ ! -f "/home/backup/${date}/${domain}/${db_name}.sql" ]; then
			ALERT="${RED}Ten mien nay khong co backup.${NC}\n"
		fi

		if [ -z "${ALERT}" ]; then

			restore_source
			empty_db
			restore_db
			clear
			printf "${GREEN}Khoi phuc du lieu thanh cong.${NC}\n"
		else
			clear
			printf "${ALERT}\n"
		fi
	else
		clear
		printf "${RED}Ban da chon huy khoi phuc du lieu.${NC}\n"
	fi
}

run
menu_backup
