#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    db_name=$(grep -w "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

confirm_restore(){
    while true
    do
        read -r -p "Ban muon khoi phuc du lieu ? (y/n) " promt_restore
        echo
        if [[ "${promt_restore}" =~ ^([yY])$ || "${promt_restore}" =~ ^([nN])$ ]]; then
            break
        else
            printf "%s\n"  "${RED}Gia tri khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done
}

_restore(){
    cd_dir /home/backup/"${date}"/"${domain}"
#    mysql -uadmin -p"${mysql_pwd}" "${db_name}" < "${db_name}".sql.gz
    sql_files=()
    for entry in *.{sql,sql.gz}; do
        if [ -f "${entry}" ]; then
            sql_files+=("${entry}")
        fi
    done

    echo "Chon file database muon khoi phuc"
    PS3="Nhap vao lua chon cua ban [0 = Thoat]: "
    select opt in "${sql_files[@]}"
    do
        sql=$opt
        break
    done

    if [[ ${sql} == *"sql.gz"* ]]; then
        gzip < "${sql}" | mysql -uadmin -p"${mysql_pwd}" "${db_name}"
    else
        mysql -uadmin -p"${mysql_pwd}" "${db_name}" < "${sql}"
    fi
}

_run(){
    set_var
    check_backup_exists "${date}" "${domain}"

    if ! check_backup_empty "${date}" "${domain}";
    then
        ALERT="%s\n" "${RED}Ten mien nay khong co backup.${NC}"
    fi

    if [ ! -f "/home/backup/${date}/${domain}/${db_name}.sql.gz" ]; then
        ALERT="%s\n" "${RED}Ten mien nay khong co backup.${NC}"
    fi

    if [[ -z "${ALERT}" ]]; then
        empty_db
        _restore
        clear
        printf "%s\n" "${GREEN}Khoi phuc du lieu thanh cong.${NC}"
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
}

if [[ $(ls -A "${USER_DIR}") ]]; then
    promt_restore=""
    date=""
    domain=""
    ALERT=""

    confirm_restore
    if [[ "${promt_restore}" =~ ^([yY])$ ]]; then
        list_backup
        if [ -z "${date}" ]; then
            clear
            printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
        else
            if [ -z "${domain}" ]; then
                clear
                printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
            else
                _run
            fi
        fi
    else
        clear
        printf "%s\n" "${RED}Ban da chon huy khoi phuc du lieu.${NC}"
    fi
else
    printf "%s\n" "${RED}Khong co ten mien nao tren VPS.${NC}"
fi

select_restore