#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s=====================%s\n" "${GREEN}" "${NC}"
printf "%s  Khoi phuc du lieu  %s\n" "${GREEN}" "${NC}"
printf "%s=====================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Khoi phuc full%s\n" "${GREEN}" "${NC}"
    printf "%s2. Khoi phuc ma nguon%s\n" "${GREEN}" "${NC}"
    printf "%s3. Khoi phuc database%s\n" "${GREEN}" "${NC}"
    printf "%s ====================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; restore_full ;;
        2) clear; restore_source;;
        3) clear; restore_db ;;
        0) clear; menu_backup ;;
        *) clear; printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done