#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s===================%s\n" "${GREEN}" "${NC}"
printf "%s  Sao luu du lieu  %s\n" "${GREEN}" "${NC}"
printf "%s===================%s\n" "${GREEN}" "${NC}"
echo ""

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Sao luu ma nguon%s\n" "${GREEN}" "${NC}"
    printf "%s2. Sao luu database%s\n" "${GREEN}" "${NC}"
    printf "%s3. Sao luu full%s\n" "${GREEN}" "${NC}"
    printf "%s ================%s\n" "${GREEN}" "${NC}"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; backup_source;;
        2) clear; backup_db ;;
        3) clear; backup_full ;;
        0) clear; menu_backup ;;
        *) clear; printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}";;
    esac
done