#!/bin/bash

CHOICE=1

printf "${GREEN}===================${NC}\n"
printf "${GREEN}  Sao luu du lieu  ${NC}\n"
printf "${GREEN}===================${NC}\n"
echo ""

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}1. Sao luu ma nguon${NC}\n"
    printf "${GREEN}2. Sao luu database${NC}\n"
    printf "${GREEN}3. Sao luu full${NC}\n"
    printf "${GREEN} --------------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; backup_source;;
        2) clear; backup_db ;;
        3) clear; backup_full ;;
        0) clear; menu_backup ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done