#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

check_expired(){
    if [[ -f "/etc/letsencrypt/live/${domain}/cert.pem" ]]; then
        clear
        openssl x509 -noout -dates -in /etc/letsencrypt/live/"${domain}"/cert.pem
    else
        clear
        printf "%s\n" "${RED}Ten mien nay chua đuoc cai dat Let's Encrypt.${NC}"
    fi
}

_run(){
    domain=""
    select_domain

    if [ -z "${domain}" ]; then
        clear
        printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
    else
        clear
        check_expired
    fi
}

_run
menu_letencrypt