#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

check_expired(){
	if [[ -f "/etc/letsencrypt/live/${domain}/cert.pem" ]]; then
	    openssl x509 -noout -dates -in /etc/letsencrypt/live/"${domain}"/cert.pem
	else
		printf "${RED}Ten mien nay chua đuoc cai dat Let's Encrypt.${NC}\n"
	fi
}


select_domain
check_expired
echo ""
menu_letencrypt