#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

check_expired(){
    if [[ -f "/root/.acme.sh/${domain}/${domain}.conf" ]]; then
        clear
        expired=$(grep -w "/root/.acme.sh/${domain}/${domain}.conf" -e "Le_NextRenewTimeStr" | cut -f2 -d'=')
        printf "%s\n" "${GREEN}Ngay het han:${NC} ${RED}${expired}${NC}"
    else
        clear
        printf "%s\n" "${RED}Ten mien nay chua đuoc cai dat Let's Encrypt.${NC}"
    fi
}

_run(){
    domain=""
    select_domain

    if [[ -z "${domain}" && -z "${ALERT}" ]]; then
        clear
        printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
    else
        if [ -z "${ALERT}" ]; then
            clear
            check_expired
        else
            clear
            printf "%s\n" "${ALERT}"
        fi
    fi
}

_run
menu_letencrypt