#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2002
# shellcheck disable=SC2154
# shellcheck disable=SC2034
source /var/hostvn/menu/helpers/function

printf "%s=========================%s\n" "${GREEN}" "${NC}"
printf "%sGo bo SSL - Let's Encrypt%s\n" "${GREEN}" "${NC}"
printf "%s=========================%s\n" "${GREEN}" "${NC}"
echo

validate(){
    check_nginx_status
    check_le_exists "${domain}"
}

remove_ssl_cert(){
    certbot-auto revoke --cert-path /etc/letsencrypt/live/"${domain}"/cert.pem
    certbot-auto delete --cert-name "${domain}"
}

edit_vhost(){
    cat >> "${VHOST_DIR}/${domain}.conf" << END
upstream php-${username} {
    server ${fastcgi_pass}
}

server {
    listen 80;
    server_name ${domain} www.${domain};

    #access_log off;
    #access_log /home/${username}/${domain}/logs/access.log;
    #error_log off;
    error_log /home/${username}/${domain}/logs/error.log;
    ${root}
    index index.php index.html index.htm;

    ${rewrite}

    location ~ \.php\$ {
        try_files \$uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)\$;
        fastcgi_index index.php;
        include /etc/nginx/fastcgi_params;
        include /etc/nginx/extra/nginx_limits.conf;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        if (-f \$request_filename)
        {
            fastcgi_pass php-${username};
        }
    }
    ${brute}
    include /etc/nginx/extra/staticfiles.conf;
    include /etc/nginx/extra/security.conf;
    ${wp_secure}
    ${xmlrpc}
}
END
}

_run(){
    validate

    if [ -z "${ALERT}" ]; then
        username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
        php_mode="$(grep "php_mode" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')"
        select_source
        root="root /home/${username}/${domain}/public_html;"
        if [ "${SOURCE}" == "laravel" ]; then
            root="root /home/${username}/${domain}/public_html/public;"
        fi

        if [[ "${SOURCE}" == "wordpress" ]]; then
            wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
            xmlrpc="include /etc/nginx/wordpress/disable_xmlrpc.conf;"
            brute_force_wp "${username}"
        fi
        rm -rf /etc/nginx/conf.d/"${domain}".conf
        set_rewrite
        fastcgi
        edit_vhost
        remove_ssl_cert
        systemctl restart nginx.service
        clear
        printf "%s\n" "${GREEN}Go bo SSL Let's Encrypt thanh cong.${NC}"
        if [[ "${SOURCE}" == "wordpress" ]]; then
            printf "%s\n" "${GREEN}Luu y: Ban can cau hinh lai Plugins cache va Plugins Seo tai menu 7-7${NC}"
        fi
        echo ""
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
}

ALERT=""
domain=""
select_domain

if [ -n "${domain}" ]; then
    _run
else
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
fi

menu_letencrypt