#!/bin/bash

debug_(){
    LOG_FILE=/var/log/hostvn/$(date +%F)_remove_le.log
    exec 5> "${LOG_FILE}"
    BASH_XTRACEFD="5"
    PS4='$LINENO: '
    set -x
}

debug_

# shellcheck disable=SC1091
source /var/hostvn/hostvn.conf
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/variable_common
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

echo "-------------------------------------------------------------------------"
echo "Gỡ bỏ SSL - Let's Encrypt"
echo "-------------------------------------------------------------------------"
echo

set_variable(){
    server_ip=$(ip route get 1 | awk '{print $NF;exit}')
    username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    php_mode=$(grep "php_mode" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    plugin_cache="$(grep "plugin_cache" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')"
    rewrite="include /etc/nginx/rewrite/${SOURCE}.conf;"
    cache="include /etc/nginx/extra/staticfiles.conf;"
    wp_secure=""
    brute=""
}

check_le_exists(){
    if [[ ! -d "/etc/letsencrypt/live/${domain}" ]]; then
        echo "Tên miền ${domain} chưa được cài đặt Let's Encrypt"
        sleep 2
        menu_letencrypt
    fi
}

check_plugins_cache(){
    if [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/w3-total-cache" ]]; then
        cache="include /etc/nginx/wordpress/w3c.conf;"
        wp_secure="/etc/nginx/wordpress/wordpress_secure.conf"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/wp-fastest-cache" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/wpfc.conf;"
        wp_secure="/etc/nginx/wordpress/wordpress_secure.conf"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/wp-rocket" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/wprocket.conf;"
        wp_secure="/etc/nginx/wordpress/wordpress_secure.conf"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/wp-super-cache" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/wpsc.conf;"
        wp_secure="/etc/nginx/wordpress/wordpress_secure.conf"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/cache-enabler" ]]; then
        rewrite=""
        cache="include /etc/nginx/wordpress/enabler.conf;"
        wp_secure="/etc/nginx/wordpress/wordpress_secure.conf"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/swift-performance-lite" && "${plugin_cache}" == "swift1" ]]; then
        cache="include /etc/nginx/extra/staticfiles.conf;"
        wp_secure="/etc/nginx/wordpress/wordpress_secure.conf"
    elif [[ -d "/home/${username}/${domain}/public_html/wp-content/plugins/swift-performance-lite" && "${plugin_cache}" == "swift2" ]]; then
        cache="include /etc/nginx/wordpress/swift2.conf;"
        wp_secure="/etc/nginx/wordpress/wordpress_secure.conf"
    else
        plugin_cache="other"
        wp_secure="/etc/nginx/wordpress/wordpress_secure.conf"
    fi
}

backup_vhost(){
    if [[ -f "/etc/nginx/backup_vhost/${domain}.conf.orig" ]]; then
        rm -rf /etc/nginx/backup_vhost/"${domain}".conf.orig
    fi

    mv "/etc/nginx/conf.d/$domain.conf" "/etc/nginx/backup_vhost/${domain}.conf.orig"
}

remove_ssl_cert(){
	rm -rf /etc/letsencrypt/live/"${domain}"
}

create_vhost(){
    backup_vhost
    set_rewrite
    fastcgi

    if [[ "${SOURCE}" == "wordpress" ]]; then
        check_plugins_cache
        brute_force_wp
    fi

    cat >> "${VHOST_DIR}/${domain}.conf" << END
server {
    listen 80;
    server_name ${domain} www.${domain};

    #access_log off;
    #access_log /home/${username}/${domain}/logs/access.log;
    #error_log off;
    error_log /home/${username}/${domain}/logs/error.log;
    ${root}
    index index.php index.html index.htm;

    ${rewrite}
    ${cache}

    location ~ \.php\$ {
        try_files \$uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)\$;
        fastcgi_index index.php;
        include /etc/nginx/fastcgi_params;
        include /etc/nginx/extra/nginx_limits.conf;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        if (-f \$request_filename)
        {
            ${fastcgi_pass}
        }
    }

    ${brute}
    ${wp_secure}
    include /etc/nginx/extra/security.conf;
}
END
}

restart_nginx(){
    systemctl restart nginx.service
}

run(){
    check_nginx_status
    select_domain
    check_domain_exists
    check_le_exists
    select_source

    if [[ "${SOURCE}" == "wordpress" ]]; then
        plugin_cache
    fi

    set_variable
    create_vhost
    remove_ssl_cert
    restart_nginx
}

run

echo ""
echo "Gỡ bỏ SSL Let's Encrypt thành công"
sleep 2
menu_letencrypt