#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
    php_mode="$(grep "php_mode" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')"
}

input(){
    false
    while [ $? -eq 1 ]
    do
        read -r -p "Nhap domain moi (Khong co www) [0 = Thoat]: " newdomain
        if [ "${newdomain}" == "0" ]; then
            break
        else
            newdomain=$(echo "${newdomain}" | tr '[:upper:]' '[:lower:]')
            echo "${newdomain}" | grep -q "\."
            if [ $? -eq 0 ]; then
                "${BASH_DIR}"/menu/validate/check_value domain "${newdomain}"
                if [[ $? -eq 1 ]]; then
                    clear
                    printf "%s\n" "${RED}Ten mien ban nhap khong chinh xac vui long nhap lai.${NC}"
                    false
                fi
            else
                clear
                printf "%s\n" "${RED}Ten mien ban nhap khong chinh xac vui long nhap lai.${NC}"
                false
            fi
        fi
    done
}

change_path(){
    mv /home/"${username}"/"${domain}" /home/"${username}"/"${newdomain}"
}

change_vhost(){
    mv /etc/nginx/conf.d/"${domain}".conf /etc/nginx/conf.d/"${newdomain}".conf
    sed -i "s/${domain}/${newdomain}/g" /etc/nginx/conf.d/"${newdomain}".conf
}

change_phpconfig(){
    php_conf_path="/etc/php-fpm.d"
    if [[ "${php2_release}" == "yes" && "${php_mode}" == "2" ]]; then
        php_conf_path="/etc/opt/remi/${php2_version}/php-fpm.d"
        if [[ "${php2_version}" == "php56" ]]; then
            php_conf_path="/opt/remi/${php2_version}/root/etc/php-fpm.d"
        fi
    fi

    mv "${php_conf_path}"/"${domain}".conf "${php_conf_path}"/"${newdomain}".conf
    sed -i "s/${domain}/${newdomain}/g" "${php_conf_path}"/"${newdomain}".conf
}

change_user_config(){
    mv "${USER_DIR}"/."${domain}".conf "${USER_DIR}"/."${newdomain}".conf
}

_run(){
    if ! if_is_wordpress "${username}" "${domain}"; then
        change_path
        change_user_config
        change_vhost
        change_phpconfig
        systemctl reload nginx
        systemctl restart php-fpm.service
        if [ "${php2_release}" == "yes" ]; then
            systemctl restart "${php2_version}"-php-fpm
        fi
        clear
        printf "%s\n" "${GREEN}Doi domain thanh cong.${NC}"
    else
        clear
        printf "%s\n" "${RED}Website dang su dung WordPress. Vui long su dung chuc nang doi ten mien trong menu WordPress.${NC}"
    fi
}

ALERT=""
domain=""
newdomain=""

select_domain

if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
else
    if [ -z "${ALERT}" ]; then
        set_var
        input
        if [ "${newdomain}" == "0" ]; then
            clear
            printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
        else
            _run
        fi
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
fi

menu_domain