#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
    username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');

    if [[ -z "${username}" ]]; then
        username=${domain//[-._]/}
    fi

    php_mode=$(grep "php_mode" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

input(){
	  read -r -p "Nhap vao ten mien moi: " newdomain
}

change_path(){
	  mv /home/"${username}"/"${domain}" /home/"${username}"/"${newdomain}"
}

backup_vhost(){
    if [[ -f "/etc/nginx/backup_vhost/${domain}.conf.orig" ]]; then
        rm -rf /etc/nginx/backup_vhost/"${domain}".conf.orig
    fi

    mv "/etc/nginx/conf.d/$domain.conf" "/etc/nginx/backup_vhost/${domain}.conf.orig"
}

change_vhost(){
	  backup_vhost
	  check_plugins_cache
	  fastcgi

	  cat >> "${VHOST_DIR}/${newdomain}.conf" << END
server {
    listen 80;
    server_name ${newdomain} www.${newdomain};

    #access_log off;
    #access_log /home/${username}/${newdomain}/logs/access.log;
    #error_log off;
    error_log /home/${username}/${newdomain}/logs/error.log;
    root /home/${username}/${newdomain}/public_html/public;
    index index.php index.html index.htm;

    ${rewrite}
    ${cache}

    location ~ \.php\$ {
        try_files \$uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)\$;
        fastcgi_index index.php;
        include /etc/nginx/fastcgi_params;
        include /etc/nginx/extra/nginx_limits.conf;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        if (-f \$request_filename)
        {
            ${fastcgi_pass}
        }
    }

    include /etc/nginx/extra/security.conf;
}
END
}

change_phpconfig(){
    php_conf_path="/etc/php-fpm.d"
    if [[ "${php2_release}" == "yes" && "${php_mode}" == "2" ]]; then
        php_conf_path="/etc/opt/remi/${php2_version}/php-fpm.d"
        if [[ "${php2_version}" == "php56" ]]; then
            php_conf_path="/opt/remi/${php2_version}/root/etc/php-fpm.d"
        fi
    fi

    mv "${php_conf_path}"/"${domain}".conf "${php_conf_path}"/"${newdomain}".conf
    sed -i "s/${domain}/${newdomain}/g" "${php_conf_path}"/"${newdomain}".conf
}

change_user_config(){
    mv "${USER_DIR}"/."${domain}".conf "${USER_DIR}"/."${newdomain}".conf
}

_run(){
    select_domain
    set_var
    if_is_wordpress "${username}" "${domain}"
    input
    validate_domain "${newdomain}"
    check_domain_exists "${domain}"

    if [ -z "${ALERT}" ]; then
        select_source
        set_rewrite
        change_path
        change_vhost
        change_phpconfig
        change_user_config
        clear
        printf "${GREEN}Doi domain thanh cong.${NC}\n"
    else
        clear
        printf "${ALERT}\n"
    fi
}

_run
menu_domain