#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function
# shellcheck disable=SC1091
source /var/hostvn/menu/validate/rule

set_var(){
	username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');

	if [[ -z "${username}" ]]; then
		username=${domain//[-._]/}
	fi

	php_mode=$(grep "php_mode" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

input(){
	read -r -p "Nhap vao ten mien moi: " newdomain
}

valid_domain(){
	if [[ -z "${newdomain}" ]]; then
		ALERT=$(printf "${RED}Ban chua nhap Domain.${NC}\n")
	fi

	if [[ "${newdomain}" = "${newdomain}/.}" ]]; then
		ALERT=$(printf "${RED}Domain ban nhap khong dung dinh dang.${NC}\n")
	fi
}

change_path(){
	mv /home/"${username}"/"${domain}" /home/"${username}"/"${newdomain}"
}

backup_vhost(){
    if [[ -f "/etc/nginx/backup_vhost/${domain}.conf.orig" ]]; then
        rm -rf /etc/nginx/backup_vhost/"${domain}".conf.orig
    fi

    mv "/etc/nginx/conf.d/$domain.conf" "/etc/nginx/backup_vhost/${domain}.conf.orig"
}

change_vhost(){
	backup_vhost
	check_plugins_cache
	fastcgi

	cat >> "${VHOST_DIR}/${newdomain}.conf" << END
server {
    listen 80;
    server_name ${newdomain} www.${newdomain};

    #access_log off;
    #access_log /home/${username}/${newdomain}/logs/access.log;
    #error_log off;
    error_log /home/${username}/${newdomain}/logs/error.log;
    root /home/${username}/${newdomain}/public_html/public;
    index index.php index.html index.htm;

    ${rewrite}
    ${cache}

    location ~ \.php\$ {
        try_files \$uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)\$;
        fastcgi_index index.php;
        include /etc/nginx/fastcgi_params;
        include /etc/nginx/extra/nginx_limits.conf;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        if (-f \$request_filename)
        {
            ${fastcgi_pass}
        }
    }

    include /etc/nginx/extra/security.conf;
}
END
}

change_phpconfig(){
	php_conf_path="/etc/php-fpm.d"
	if [[ "${php2_release}" == "yes" && "${php_mode}" == "2" ]]; then
        php_conf_path="/opt/remi/${php2_version}/root/etc/php-fpm.d"
    fi

    mv "${php_conf_path}"/"${domain}".conf "${php_conf_path}"/"${newdomain}".conf
    sed -i 's/${domain}/${newdomain}/g' "${php_conf_path}"/"${newdomain}".conf
}

run(){
	select_domain
	set_var
	if_is_wordpress "${username}" "${domain}"
	input
	valid_domain

	if [[ -z "${ALERT}" ]]; then
		select_source
		set_rewrite
		change_path
		change_vhost
		change_phpconfig
		change_in_db
		printf "${GREEN}Doi domain thanh cong.${NC}\n"
	else
		printf "${ALERT}"
	fi
}

run
menu_domain