#!/bin/bash

debug_(){
    LOG_FILE=/var/log/hostvn/del_domain.log
    exec 5> ${LOG_FILE}
    BASH_XTRACEFD="5"
    PS4='$LINENO: '
    set -x
}

debug_

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function
# shellcheck disable=SC1091
source /var/hostvn/hostvn.conf
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/variable_common

echo "-------------------------------------------------------------------------"
echo "Xóa Domain"
echo "-------------------------------------------------------------------------"

set_var(){
	db_name=$(grep "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
    db_user=$(grep "db_user" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
    username=$(grep "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
    php_mode=$(grep "php_mode" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
    vhost_config="${VHOST_DIR}/${domain}.conf"
    php_config_path="/etc/php-fpm.d/${domain}.conf"
}

destroy_user(){
	userdel -f -r "$1"
}

destroy_ftp_user(){
	pure-pw userdel "$1"
	pure-pw mkdb
}

destroy_db(){
	mysql -e "REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${db_user}'@'localhost'"
    mysql -e "DROP USER IF EXISTS '${db_user}'@'localhost'"
    mysql -e "DROP DATABASE IF EXISTS ${db_name}"
}

remove_path(){
	if [[ "{$php_mode}" == 2 ]]; then
    	php_config_path="/opt/remi/${php2_version}/root/etc/php-fpm.d/${domain}.conf"
	fi

	rm -rf /home/"${username:?}"
	rm -rf "${vhost_config}"
	rm -rf "${USER_DIR}"/."${domain}".conf
    rm -rf "${php_config_path}"
}

confirm(){
	read -r -p "Bạn thực sự muốn xoá ${domain}? "

	echo "Bạn thực sự muốn xoá ${domain}?  "
    PS3="Nhập vào lựa chọn của bạn [1-3]"
    options=("Yes" "No" "Cancel")
    select opt in "${options[@]}"
    do
        case $opt in
            "Yes") confirm_destroy_domain="y"; break;;
            "No") confirm_destroy_domain="N"; break;;
			"Cancel") menu_domain; break;;
            *) printf "Bạn nhập sai, vui lòng nhập lại\n";;
        esac
    done

	echo "Bạn có muốn xóa database ${db_name}? (y/n): "
    PS3="Nhập vào lựa chọn của bạn [1-3]"
    options=("Yes" "No" "Cancel")
    select opt in "${options[@]}"
    do
        case $opt in
            "Yes") confirm_destroy_db="y"; break;;
            "No") confirm_destroy_db="N"; break;;
			"Cancel") menu_domain; break;;
            *) printf "Bạn nhập sai, vui lòng nhập lại\n";;
        esac
    done
}

run(){
	select_domain
	check_domain_exists
	set_var
	confirm

	if [[ "${confirm_destroy_domain}" =~ ^([nN])$ ]]; then
		echo "Bạn đã chọn huỷ xoá domain. Bye bye"
		menu_domain
	fi

	if [[ "${confirm_destroy_db}" =~ ^([yY])$ ]]; then
		destroy_db
	fi

	destroy_user "$username"
	destroy_ftp_user "$username"
	remove_path
	restart_service
}

run
clear
echo "Xóa Domain thành công."
echo
menu_domain