#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/script/menu/helpers/functions

echo "-------------------------------------------------------------------------"
echo "Xóa Domain"
echo "-------------------------------------------------------------------------"

set_var(){
	db_name=$(grep "db_name" "/var/hostvn/script/users/.""${domain}"".conf" | cut -f2 -d'=');
    db_user=$(grep "db_user" "/var/hostvn/script/users/.""${domain}"".conf" | cut -f2 -d'=');
    username=$(grep "username" "/var/hostvn/script/users/.""${domain}"".conf" | cut -f2 -d'=');
}

destroy_user(){
	userdel -f -r "$1"
}

destroy_ftp_user(){
	pure-pw "$1"
}

destroy_db(){
	mysql -e "REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${db_user}'@'localhost'"
    mysql -e "DROP USER IF EXISTS '${db_user}'@'localhost'"
    mysql -e "DROP DATABASE IF EXISTS ${db_name}"
}

remove_path(){
	rm -rf /home/"${username:?}"
	rm -rf /var/hostvn/script/users/."${domain}".conf
	rm -rf /etc/nginx/conf.d/"${domain}".conf
    rm -rf /etc/php-fpm.d/"${domain}".conf
}

confirm(){
	read -r -p "Bạn thực sự muốn xoá ${domain}? "

	echo "Bạn thực sự muốn xoá ${domain}?  "
    PS3="Nhập vào lựa chọn của bạn [1-3]"
    options=("Yes" "No" "Cancel")
    select opt in "${options[@]}"
    do
        case $opt in
            "Yes") confirm_destroy_domain="y"; break;;
            "No") confirm_destroy_domain="N"; break;;
			"Cancel") controller_domain; break;;
            *) printf "Bạn nhập sai, vui lòng nhập lại\n";;
        esac
    done

	echo "Bạn có muốn xóa database ${db_name}? (y/n): "
    PS3="Nhập vào lựa chọn của bạn [1-3]"
    options=("Yes" "No" "Cancel")
    select opt in "${options[@]}"
    do
        case $opt in
            "Yes") confirm_destroy_db="y"; break;;
            "No") confirm_destroy_db="N"; break;;
			"Cancel") controller_domain; break;;
            *) printf "Bạn nhập sai, vui lòng nhập lại\n";;
        esac
    done
}

run(){
	select_domain
	check_domain_exists
	set_var
	confirm

	if [[ "${confirm_destroy_domain}" =~ ^([nN])$ ]]; then
		echo "Bạn đã chọn huỷ xoá domain. Bye bye"
		controller_domain
	fi

	if [[ "${confirm_destroy_db}" =~ ^([yY])$ ]]; then
		destroy_db
	fi

	destroy_user "$username"
	destroy_ftp_user "$username"
	remove_path
	restart_service
}

run
clear
echo "Xóa Domain thành công."
echo
controller_domain