#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/variable_common

list_domain(){
	if [ "$(ls -At ${USER_DIR})" ]; then
    	clear
    	echo "Danh sách Domain trên VPS:"
    	echo
    	i=1
    	cd_dir "${USER_DIR}"
    	for entry in .*.conf; do
    		[[ -e "${entry}" ]] || break
    	    domain=$( echo "$entry" | sed 's/^.//' | sed 's/.conf//')
    	    echo "$i) $domain"
    		i=$((i+1));
    	done
        echo "-------------------------------------------------------------------------"
    	echo "Tổng Domain: $((i-1))"
        menu_domain
    else
    	clear
    	echo "Không có Domain nào tồn tại trên hệ thống"
    fi
}

list_domain
echo ""
menu_domain