#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

list_domain(){
    if [ "$(ls -At ${USER_DIR})" ]; then
        clear
        echo "Danh sach Domain tren VPS:"
        echo
        i=1
        cd_dir "${USER_DIR}"
        for entry in .*.conf; do
            [[ -e "${entry}" ]] || break
            domain=${entry/.}
            domain=${domain//.conf}
            printf "$i) ${GREEN}${domain}${NC}\n"
            i=$((i+1));
        done
        echo "-------------------------------------------------------------------------"
        echo "Tong Domain: $((i-1))"
    else
        clear
        printf "${RED}Khong co Domain nao ton tai tren he thong.${NC}\n"
    fi
}

list_domain
echo ""
menu_domain