#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_run(){
    string1=$(grep -rnw "/etc/php.d/opcache-default.blacklist" -e "${domain}")
    username=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
    if [ -z "${string1}" ]; then
        echo "/home/${username}/${domain}/public_html" >> /etc/php.d/opcache-default.blacklist
        systemctl restart php-fpm
    fi

    if [ "${php2_release}" == "yes" ]; then
        PHP2_INI_PATH="/etc/opt/remi/${PHP_VERSION_2}/php.d"
        if [[ ${PHP_VERSION_2} == "php56" ]]; then
            PHP2_INI_PATH="/opt/remi/${PHP_VERSION_2}/root/etc/php.d"
        fi
        string2=$(grep -rnw "${PHP2_INI_PATH}/opcache-default.blacklist" -e "${domain}")
        if [ -z "${string2}" ]; then
            echo "/home/${username}/${domain}/public_html" >> "${PHP2_INI_PATH}"/opcache-default.blacklist
            systemctl restart "${php2_version}"-php-fpm
        fi
    fi
    clear
    printf "%s\n" "${GREEN}Them website vao blacklist thanh cong.${NC}"
}

domain=""

select_domain

if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
    manage_opcache
else
    if [ -z "${ALERT}" ]; then
        _run
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
fi

manage_opcache

