#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

if nginx -t; then
  systemctl restart nginx
  systemctl restart php-fpm.service
  if [ "${php2_release}" == "yes" ]; then
    systemctl restart "${php2_version}"-php-fpm
  fi
  clear
  printf "%s\n" "${GREEN}Xoa cache Opcache thanh cong.${NC}"
else
  printf "%s\n" "${RED}Cau hinh Nginx khong chinh xac. Vui long kiem tra lai${NC}"
fi

manage_opcache
