#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
source /var/hostvn/menu/helpers/function

_run(){
    sed -i "/${domain}/d" /etc/php.d/opcache-default.blacklist
    systemctl restart php-fpm

    if [ "${php2_release}" == "yes" ]; then
        PHP2_INI_PATH="/etc/opt/remi/${PHP_VERSION_2}/php.d"
        if [[ ${PHP_VERSION_2} == "php56" ]]; then
            PHP2_INI_PATH="/opt/remi/${PHP_VERSION_2}/root/etc/php.d"
        fi
        sed -i "/${domain}/d" "${PHP2_INI_PATH}"/opcache-default.blacklist
        systemctl restart "${php2_version}"-php-fpm
    fi
    clear
    printf "%s\n" "${GREEN}Xoa website khoi blacklist thanh cong.${NC}"
    manage_opcache
}

domain=""
select_domain

if [ -z "${domain}" ]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
    manage_opcache
else
    _run
fi