#!/bin/bash

echo "-----------------"
echo "Thay đoi port SSH"
echo "-----------------"

set_var(){
	current_port=$(grep "Port " /etc/ssh/sshd_config | cut -f2 -d" ")
}

input(){
	read -r -p "Nhap vao port ban muon đoi: " port_new
}

check_port(){
	set_var
	if [ "$port_new" = '' ]; then
	    ALERT=$(printf "${RED}Ban chua nhap Port.${NC}\n")
	fi

	if [[ ! $port_new =~ ^-?[0-9]+$ ]]; then
	    ALERT=$(printf "${RED}Port khong dung dinh dang, vui long nhap lai.${NC}\n")
	fi

	if [[ "${port_new}" == "${current_port}" ]]; then
	    ALERT=$(printf "${RED}Port ban nhap trung vui Port SSH hiun tai.${NC}\n")
	fi

	if [[ "${port_new}" == "${admin_port}" ]]; then
	    ALERT=$(printf "${RED}Port ban nhap trung vui Port Admin tool.${NC}\n")
	fi
}

change_port(){
	echo "Dang tien hanh thay đoi port SSH..."
   	echo ""
   	sleep 1
    sed -i 's/Port '${port_open}'/Port '${port_new}'/g' /etc/ssh/sshd_config
    sed -i 's/,'${port_open}',/,'${port_new}',/g' /etc/csf/csf.conf
    sed -i 's/PORTS_sshd = "22, '${port_open}'"/PORTS_sshd = "22, '${port_new}'"/g' /etc/csf/csf.conf
    sed -i 's/ssh_port='${port_open}'/ssh_port='${port_new}'/g' "${BASH_DIR}"/hostvn.conf
    systemctl reload sshd.service
    csf -x
    csf -e
    systemctl restart csf
    systemctl restart lfd
    printf "${GREEN}Da thay đoi Port SSH sang ${port_new} thanh cong.${NC}\n"
}

run(){
	input
	check_port
	if [[ -z "${ALERT}" ]]; then
		change_port
	else
		printf "${ALERT}"
	fi
}

run
echo ""
sleep 2
menu_ssh