#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_run(){
    clear
    user=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
    printf "%s\n" "${GREEN}Dung luong hien tai cua website:${NC} ${RED}${domain}${NC}"
    echo
    du -sh /home/"${user}"/"${domain}"
    echo
}

ALERT=""
domain=""

select_domain

if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac.${NC}"
else
    if [ -z "${ALERT}" ]; then
        _run
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
fi

menu_tools

