#!/bin/bash

cd_dir(){
    cd "$1" || return
}

# Print space
printf_s(){
    if [ $1 -le 0 ]
    then
        echo ""
    else
        printf '%0.s ' $(seq 1 $1)
    fi
}

valid_number(){
    REGEX_NUMBER='^[0-9]+$'
    if ! [[ $1 =~ ${REGEX_NUMBER} ]]; then
        return 0
    else
        return 1
    fi
}

convert_to_mb(){
    local -i bytes=$1;
    if [[ $bytes -lt 1024 ]]; then
        echo "${bytes} B"
    elif [[ $bytes -lt 1048576 ]]; then
        echo "$(( (bytes + 1023)/1024 )) MB"
    else
        echo "$(( (bytes + 1048575)/1048576 )) GB"
    fi
}

select_domain(){
    domain=""
    if [ "$(ls -At ${USER_DIR})" ]; then
        echo "Danh sach domain"
        selects=()
        cd_dir "${USER_DIR}"
        for entry in .*.conf; do
            domain=$( echo "$entry" | sed 's/^.//' | sed 's/.conf//')
            if [ "${domain}" != "${domain/.}" ]; then
                selects+=(${domain})
            fi
        done
        PS3="Nhap lua chon cua ban [0=Exit]: "
        select select in "${selects[@]}"
        do
            domain=$select
            break
        done
    else
        ALERT=$(printf "${RED}Khong co Domain nao ton tai tren he thong.${NC}\n")
    fi
}

# Select Source
select_source(){
    SOURCE="Other"
    echo "Lua chon ma nguon đe tao Rewrite Url"
    PS3='Nhap lua chon cua ban (1-14): '
    options=("WordPress" "Laravel" "CodeIgniter" "Xenforo" "Joomla" "Drupal" "OpenCart" "WHMCS" "PrestaShop" "Yii" "NextCloud" "Discuz" "Ecshop" "Other")
    select opt in "${options[@]}"
    do
        case $opt in
            "WordPress") SOURCE="wordpress"; break;;
            "Laravel") SOURCE="laravel"; break;;
            "CodeIgniter") SOURCE="codeigniter"; break;;
            "Xenforo") SOURCE="xenforo"; break;;
            "Joomla") SOURCE="joomla"; break;;
            "Drupal") SOURCE="drupal"; break;;
            "OpenCart") SOURCE="opencart"; break;;
            "WHMCS") SOURCE="whmcs"; break;;
            "PrestaShop") SOURCE="prestashop"; break;;
            "Yii") SOURCE="yii"; break;;
            "NextCloud") SOURCE="nextcloud"; break;;
            "Discuz") SOURCE="discuz"; break;;
            "Ecshop") SOURCE="ecshop"; break;;
            "Other") SOURCE="default"; break;;
            *) printf "${RED}Ban nhap sai, he thong se tao Rewrite Url mac dinh.${NC}\n"; break;;
        esac
    done
}

set_rewrite(){
    if [ "${SOURCE}" == "wordpress" ]; then
        rewrite="include /etc/nginx/rewrite/wordpress.conf;"
        wp_secure="include /etc/nginx/wordpress/wordpress_secure.conf;"
    elif [ "${SOURCE}" == "laravel" ]; then
        rewrite="include /etc/nginx/rewrite/laravel.conf;"
    elif [ "${SOURCE}" == "codeigniter" ]; then
        rewrite="include /etc/nginx/rewrite/codeigniter.conf;"
    elif [ "${SOURCE}" == "xenforo" ]; then
        rewrite="include /etc/nginx/rewrite/xenforo.conf;"
    elif [ "${SOURCE}" == "joomla" ]; then
        rewrite="include /etc/nginx/rewrite/joomla.conf;"
    elif [ "${SOURCE}" == "drupal" ]; then
        rewrite="include /etc/nginx/rewrite/drupal.conf;"
    elif [ "${SOURCE}" == "opencart" ]; then
        rewrite="include /etc/nginx/rewrite/opencart.conf;"
    elif [ "${SOURCE}" == "whmcs" ]; then
        rewrite="include /etc/nginx/rewrite/whmcs.conf;"
    elif [ "${SOURCE}" == "prestashop" ]; then
        rewrite="include /etc/nginx/rewrite/prestashop.conf;"
    elif [ "${SOURCE}" == "yii" ]; then
        rewrite="include /etc/nginx/rewrite/yii.conf;"
    elif [ "${SOURCE}" == "nextcloud" ]; then
        rewrite="include /etc/nginx/rewrite/nextcloud.conf;"
    elif [ "${SOURCE}" == "discuz" ]; then
        rewrite="include /etc/nginx/rewrite/discuz.conf;"
    elif [ "${SOURCE}" == "ecshop" ]; then
        rewrite="include /etc/nginx/rewrite/ecshop.conf;"
    else
        rewrite="include /etc/nginx/rewrite/default.conf;"
    fi
}

fastcgi(){
    fastcgi_pass="fastcgi_pass unix:/var/run/php-fpm/${username}.sock;"

    if [[ "${php_mode}" == "2" ]]; then
        fastcgi_pass="fastcgi_pass unix:/opt/remi/${php2_version}/root/var/run/php-fpm/${username}.sock;"
    fi
}

brute_force_wp(){
    brute="location = /wp-login.php {
        limit_req zone=two burst=1 nodelay;
        include /etc/nginx/fastcgi_params;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        ${fastcgi_pass}
    }"
}

restart_service(){
    systemctl restart nginx.service
    systemctl restart php-fpm.service
}