#!/bin/bash

menu_primary(){
    hostvn
}

menu_domain(){
    . /var/hostvn/menu/domain
}

menu_letencrypt(){
    . /var/hostvn/menu/letencrypt
}

menu_ssh(){
    . /var/hostvn/menu/ssh
}

menu_cache(){
    . /var/hostvn/menu/cache
}

menu_nginx(){
    . /var/hostvn/menu/nginx
}

menu_csf(){
    . /var/hostvn/menu/csf
}

menu_permission(){
    . /var/hostvn/menu/permission
}

menu_info(){
    . /var/hostvn/menu/info
}

menu_ssl(){
    . /var/hostvn/menu/ssl_manage
}

menu_sslpaid(){
    . /var/hostvn/menu/ssl_paid
}

menu_php(){
    . /var/hostvn/menu/php
}

menu_database(){
    . /var/hostvn/menu/database
}

menu_wp(){
    . /var/hostvn/menu/wordpress
}

menu_lemp(){
	. /var/hostvn/menu/lemp
}

domain_list(){
	. /var/hostvn/menu/controller/domain/list
}

domain_create(){
	. /var/hostvn/menu/controller/domain/create
}

domain_destroy(){
	. /var/hostvn/menu/controller/domain/destroy
}

memcached_c(){
	. /var/hostvn/menu/controller/cache/memcached
}

redis_c(){
	. /var/hostvn/menu/controller/cache/redis
}

clear_cache(){
	. /var/hostvn/menu/controller/cache/clear_cache
}

le_create(){
	. /var/hostvn/menu/controller/letencrypt/create
}

le_remove(){
	. /var/hostvn/menu/controller/letencrypt/remove
}

le_check_expired(){
	. /var/hostvn/menu/controller/letencrypt/check_expired
}

permission_one(){
	. /var/hostvn/menu/controller/permission/one
}

permission_all(){
	. /var/hostvn/menu/controller/permission/all
}

ssh_change_port(){
	. /var/hostvn/menu/controller/ssh/change_port
}

ssl_create(){
	. /var/hostvn/menu/controller/ssl/create
}

ssl_remove(){
	. /var/hostvn/menu/controller/ssl/remove
}

php_setting(){
	. /var/hostvn/menu/controller/php/php_setting
}

info_webserver(){
	. /var/hostvn/menu/controller/info/webserver
}

info_vps(){
	. /var/hostvn/menu/controller/info/vps
}

info_other(){
	. /var/hostvn/menu/controller/info/other
}

wp_version(){
	. /var/hostvn/menu/controller/wordpress/version
}

wp_update(){
	. /var/hostvn/menu/controller/wordpress/update_wp
}

wp_update_plugins(){
	. /var/hostvn/menu/controller/wordpress/update_plugins
}

wp_repair_db(){
	. /var/hostvn/menu/controller/wordpress/repair_db
}

wp_optimize_db(){
	. /var/hostvn/menu/controller/wordpress/optimize_db
}

wp_backup(){
	. /var/hostvn/menu/controller/wordpress/wp_backup
}

wp_change_domain(){
	. /var/hostvn/menu/controller/wordpress/change_domain
}

account_info(){
	. /var/hostvn/menu/controller/info/account_info
}

db_list(){
	. /var/hostvn/menu/controller/database/list
}

db_create(){
	. /var/hostvn/menu/controller/database/create
}

db_change_pass(){
	. /var/hostvn/menu/controller/database/change_pass
}

db_destroy(){
	. /var/hostvn/menu/controller/database/destroy_db
}

db_backup(){
	. /var/hostvn/menu/controller/database/backup
}

db_destroy_backup(){
	. /var/hostvn/menu/controller/database/destroy_backup
}

db_restore(){
	. /var/hostvn/menu/controller/database/restore
}