#!/bin/bash

menu_primary(){
    hvn
}

menu_domain(){
    . /var/hostvn/menu/domain
}

menu_letencrypt(){
    . /var/hostvn/menu/letencrypt
}

menu_ssh(){
    . /var/hostvn/menu/ssh
}

menu_cache(){
    . /var/hostvn/menu/cache
}

menu_nginx(){
    . /var/hostvn/menu/nginx
}

menu_csf(){
    . /var/hostvn/menu/csf
}

menu_permission(){
    . /var/hostvn/menu/permission
}

menu_info(){
    . /var/hostvn/menu/info
}

menu_ssl(){
    . /var/hostvn/menu/ssl
}

menu_php(){
    . /var/hostvn/menu/php
}

menu_database(){
    . /var/hostvn/menu/database
}

menu_wp(){
    . /var/hostvn/menu/wordpress
}

domain_list(){
	. /var/hostvn/menu/controller/domain/list
}

domain_create(){
	. /var/hostvn/menu/controller/domain/create
}

domain_destroy(){
	. /var/hostvn/menu/controller/domain/destroy
}

memcached_c(){
	. /var/hostvn/menu/controller/cache/memcached
}

redis_c(){
	. /var/hostvn/menu/controller/cache/redis
}

le_create(){
	. /var/hostvn/menu/controller/letencrypt/create
}

le_remove(){
	. /var/hostvn/menu/controller/letencrypt/remove
}

permission_one(){
	. /var/hostvn/menu/controller/permission/one
}

permission_all(){
	. /var/hostvn/menu/controller/permission/all
}

ssh_change_port(){
	. /var/hostvn/menu/controller/ssh/change_port
}

ssl_create(){
	. /var/hostvn/menu/controller/ssl/create
}

ssl_remove(){
	. /var/hostvn/menu/controller/ssl/remove
}

php_setting(){
	. /var/hostvn/menu/controller/php/php_setting
}

info_webserver(){
	. /var/hostvn/menu/controller/info/webserver
}

info_vps(){
	. /var/hostvn/menu/controller/info/vps
}

info_other(){
	. /var/hostvn/menu/controller/info/other
}