#!/bin/bash

# LEMP variables common
# Version: 1.0
# Author: Sanvv

IPADDRESS=$(ip route get 1 | awk '{print $NF;exit}')

# Set directory variables
BASH_DIR="/var/hostvn"
USER_DIR="/var/hostvn/users"
VHOST_DIR="/etc/nginx/conf.d"
MYSQL_DIR="/var/lib/mysql"