#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
# Please don't copy copy under any circumstance for business reason! #
######################################################################

# shellcheck disable=SC2034

set_variable(){
    CPU_CORES=$(grep -c "processor" /proc/cpuinfo)
    RAM_TOTAL=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
    RAM_MB=$(echo "scale=0;${RAM_TOTAL}/1024" | bc)
}

php_parameter(){
    set_variable

    if [[ ${CPU_CORES} -ge 4 && ${CPU_CORES} -lt 6 && ${RAM_TOTAL} -gt 1049576 && ${RAM_TOTAL} -le 2097152 ]]; then
        PM_MAX_CHILDREN=$((CPU_CORES * 6))
        PM_START_SERVERS=$((CPU_CORES * 4))
        PM_MIN_SPARE_SERVER=$((CPU_CORES * 2))
        PM_MAX_SPARE_SERVER=$((CPU_CORES * 6))
        PM_MAX_REQUEST=2000
    elif [[ ${CPU_CORES} -ge 4 && ${CPU_CORES} -lt 6 && ${RAM_TOTAL} -gt 2097152 && ${RAM_TOTAL} -le 3145728 ]]; then
        PM_MAX_CHILDREN=$((CPU_CORES * 6))
        PM_START_SERVERS=$((CPU_CORES * 4))
        PM_MIN_SPARE_SERVER=$((CPU_CORES * 2))
        PM_MAX_SPARE_SERVER=$((CPU_CORES * 6))
        PM_MAX_REQUEST=2000
    elif [[ ${CPU_CORES} -ge 4 && ${CPU_CORES} -lt 6 && ${RAM_TOTAL} -gt 3145728 && ${RAM_TOTAL} -le 4194304 ]]; then
        PM_MAX_CHILDREN=$((CPU_CORES * 6))
        PM_START_SERVERS=$((CPU_CORES * 4))
        PM_MIN_SPARE_SERVER=$((CPU_CORES * 2))
        PM_MAX_SPARE_SERVER=$((CPU_CORES * 6))
        PM_MAX_REQUEST=2000
    elif [[ ${CPU_CORES} -ge 4 && ${CPU_CORES} -lt 6 && ${RAM_TOTAL} -gt 4194304 ]]; then
        PM_MAX_CHILDREN=$((CPU_CORES * 6))
        PM_START_SERVERS=$((CPU_CORES * 4))
        PM_MIN_SPARE_SERVER=$((CPU_CORES * 2))
        PM_MAX_SPARE_SERVER=$((CPU_CORES * 6))
        PM_MAX_REQUEST=2000
    elif [[ ${CPU_CORES} -ge 6 && ${CPU_CORES} -lt 8 && ${RAM_TOTAL} -gt 3145728 && ${RAM_TOTAL} -le 4194304 ]]; then
        PM_MAX_CHILDREN=$((CPU_CORES * 6))
        PM_START_SERVERS=$((CPU_CORES * 4))
        PM_MIN_SPARE_SERVER=$((CPU_CORES * 2))
        PM_MAX_SPARE_SERVER=$((CPU_CORES * 6))
        PM_MAX_REQUEST=2000
    elif [[ ${CPU_CORES} -ge 6 && ${CPU_CORES} -lt 8 && ${RAM_TOTAL} -gt 4194304 ]]; then
        PM_MAX_CHILDREN=$((CPU_CORES * 6))
        PM_START_SERVERS=$((CPU_CORES * 4))
        PM_MIN_SPARE_SERVER=$((CPU_CORES * 2))
        PM_MAX_SPARE_SERVER=$((CPU_CORES * 6))
        PM_MAX_REQUEST=2000
    elif [[ ${CPU_CORES} -ge 8 && ${CPU_CORES} -lt 16 && ${RAM_TOTAL} -gt 3145728 && ${RAM_TOTAL} -le 4194304 ]]; then
        PM_MAX_CHILDREN=$((CPU_CORES * 6))
        PM_START_SERVERS=$((CPU_CORES * 4))
        PM_MIN_SPARE_SERVER=$((CPU_CORES * 2))
        PM_MAX_SPARE_SERVER=$((CPU_CORES * 6))
        PM_MAX_REQUEST=2000
    elif [[ ${CPU_CORES} -ge 8 && ${CPU_CORES} -lt 12 && ${RAM_TOTAL} -gt 4194304 ]]; then
        PM_MAX_CHILDREN=$((CPU_CORES * 6))
        PM_START_SERVERS=$((CPU_CORES * 4))
        PM_MIN_SPARE_SERVER=$((CPU_CORES * 2))
        PM_MAX_SPARE_SERVER=$((CPU_CORES * 6))
        PM_MAX_REQUEST=2000
    elif [[ ${CPU_CORES} -ge 13 && ${CPU_CORES} -lt 16 && ${RAM_TOTAL} -gt 4194304 ]]; then
        PM_MAX_CHILDREN=$((CPU_CORES * 6))
        PM_START_SERVERS=$((CPU_CORES * 4))
        PM_MIN_SPARE_SERVER=$((CPU_CORES * 2))
        PM_MAX_SPARE_SERVER=$((CPU_CORES * 6))
        PM_MAX_REQUEST=2000
    elif [[ ${CPU_CORES} -ge 17 && ${RAM_TOTAL} -gt 4194304 ]]; then
        PM_MAX_CHILDREN=$((CPU_CORES * 5))
        PM_START_SERVERS=$((CPU_CORES * 4))
        PM_MIN_SPARE_SERVER=$((CPU_CORES * 2))
        PM_MAX_SPARE_SERVER=$((CPU_CORES * 5))
        PM_MAX_REQUEST=2000
    else
        PM_MAX_CHILDREN=$(echo "scale=0;${RAM_MB}*0.4/30" | bc)
        PM_START_SERVERS=$((CPU_CORES * 4))
        PM_MIN_SPARE_SERVER=$((CPU_CORES * 2))
        PM_MAX_SPARE_SERVER=$((CPU_CORES * 4))
        PM_MAX_REQUEST=500
    fi
}