#!/bin/bash

# LEMP variables common
# Version: 1.0
# Author: Sanvv

# Color
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# other varialbe
IPADDRESS=$(ip route get 1 | awk '{print $NF;exit}')
ALERT=""

# Set directory variables
BASH_DIR="/var/hostvn"
USER_DIR="/var/hostvn/users"
VHOST_DIR="/etc/nginx/conf.d"
MYSQL_DIR="/var/lib/mysql"
FILE_INFO="${BASH_DIR}/hostvn.conf"