#!/bin/bash

CHOICE=1

echo "========================"
echo "Cai dat ma nguon tu dong"
echo "========================"
echo ""

while [ "${CHOICE}" != "0" ]
do
    echo "1. WordPress"
    echo "2. Joomla"
    echo "3. Drupal"
    echo "4. Laravel"
    echo "5. CodeIgniter"
    echo "6. Nextcloud"
    echo "7. PrestaShop"
    echo "8. OpenCart"
    echo " ------------------"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; menu_primary;;
        2) clear; menu_primary;;
        3) clear; menu_primary;;
        4) clear; menu_primary;;
        5) clear; menu_primary;;
        6) clear; menu_primary;;
        7) clear; menu_primary;;
        8) clear; menu_primary;;
        0) clear; menu_primary;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done