#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu

CHOICE=1

echo "========================================================================="
echo "Quản lý Cache"
echo "========================================================================="
echo "-------------------------------------------------------------------------"
echo "Hướng dẫn: https://hostvn.net"
echo "-------------------------------------------------------------------------"
echo

while [ "${CHOICE}" != "0" ]
do
    echo "1. Memcached"
    echo "2. Redis"
    echo " ----------------------------------------------- "
    read -p " Nhập vào lựa chọn của bạn [0 = Thoát] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) memcached_c ;;
        2) redis_c ;;
        0) menu_primary ;;
        *) clear; echo -e "Lựa chọn của bạn không chính xác. Vui lòng chọn lại.";;
    esac
done