#!/bin/bash
echo "========================================================================="
echo "Quản lý Cache"
echo "========================================================================="
PS3='Nhập lựa chọn của bạn (1-2) [0=Thoát]: '
options=("Memcached" "Redis")
select opt in "${options[@]}"
do
    case $opt in
        "Memcached")
            '/var/hostvn/script/menu/controller/cache/memcached'
            ;;
        "Redis")
            '/var/hostvn/script/menu/controller/cache/redis'
            ;;
        *) hvn;;
    esac
done