#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu

CHOICE=1

echo "========================================================================="
echo "Quản lý CSF Firewall"
echo "========================================================================="
echo "-------------------------------------------------------------------------"
echo "Hướng dẫn: https://hostvn.net"
echo "-------------------------------------------------------------------------"
echo

while [ "${CHOICE}" != "0" ]
do
    echo "1. Kiểm tra Block IP"
    echo "2. Block IP"
    echo "3. Gỡ Block IP"
    echo "4. Gỡ Block toàn bộ IP"
    echo "5. Allow IP"
    echo "6. Restart CSF"
    echo "7. Tắt CSF"
    echo "8. Bật CSF"
    echo " ----------------------------------------------- "
    read -p " Nhập vào lựa chọn của bạn [0 = Thoát] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1)
            read -r -p "Nhập vào IP muốn kiểm tra: " ip
            csf -g "${ip}"
            echo ""
            menu_csf
            ;;
        2)
            read -r -p "Nhập vào IP muốn block: " ip
            csf -d "${ip}"
            echo ""
            menu_csf
            ;;
        3)
            read -r -p "Nhập vào IP muốn gỡ block: " ip
            csf -dr "${ip}"
            echo ""
            menu_csf
            ;;
        4)
            csf -tf
            csf -df
            systemctl restart csf
            systemctl restart lfd
            echo ""
            menu_csf
            ;;
        5)
            read -r -p "Nhập vào IP muốn allow: " ip
            csf -a "${ip}"
            echo ""
            menu_csf
            ;;
        6)
            csf -r
            systemctl restart csf
            systemctl restart lfd
            echo ""
            menu_csf
            ;;
        7)
            csf -x
            systemctl stop csf
            systemctl stop lfd
            systemctl disable csf
            systemctl disable lfd
            echo ""
            menu_csf
            ;;
        8)
            csf -e
            systemctl start csf
            systemctl start lfd
            systemctl enable csf
            systemctl enable lfd
            echo ""
            menu_csf
            ;;
        0) menu_primary ;;
        *) clear; echo -e "Lựa chọn của bạn không chính xác. Vui lòng chọn lại.";;
    esac
done