#!/bin/bash

CHOICE=1

echo "============================="
echo "    Quan ly CSF Firewall     "
echo "============================="
printf "CSF GUI: %s\n" "${RED}https://${IPADDRESS}:${csf_port}${NC}"
echo "-----------------------------"
echo

while [ "${CHOICE}" != "0" ]
do
    echo "1. Kiem tra Block IP"
    echo "2. Block IP"
    echo "3. Go Block IP"
    echo "4. Go Block toan bo IP"
    echo "5. Allow IP"
    echo "6. Cap quyen truy cap CSF GUI"
    echo "7. Restart CSF"
    echo "8. Tat CSF"
    echo "9. Bat CSF"
    echo " ----------------------------"
    read -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1)
            read -r -p "Nhap vao IP muon kiem tra: " ip
            csf -g "${ip}"
            echo ""
            menu_csf
            ;;
        2)
            read -r -p "Nhap vao IP muon block: " ip
            csf -d "${ip}"
            echo ""
            menu_csf
            ;;
        3)
            read -r -p "Nhap vao IP muon go block: " ip
            csf -dr "${ip}"
            echo ""
            menu_csf
            ;;
        4)
            csf -tf
            csf -df
            systemctl restart csf
            systemctl restart lfd
            echo ""
            menu_csf
            ;;
        5)
            read -r -p "Nhap vao IP muon allow: " ip
            csf -a "${ip}"
            echo ""
            menu_csf
            ;;
        6)
            read -r -p "Nhap vao IP muon cap quyen truy cap CSF GUI: " ip
            echo "${ip}" >>  /etc/csf/ui/ui.allow
            csf -x
            csf -e
            echo ""
            menu_csf
            ;;
        7)
            csf -x
            csf -e
            systemctl restart csf
            systemctl restart lfd
            echo ""
            menu_csf
            ;;
        8)
            csf -x
            systemctl stop csf
            systemctl stop lfd
            systemctl disable csf
            systemctl disable lfd
            echo ""
            menu_csf
            ;;
        9)
            csf -e
            systemctl start csf
            systemctl start lfd
            systemctl enable csf
            systemctl enable lfd
            echo ""
            menu_csf
            ;;
        0) clear; menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done