#!/bin/bash
echo "========================================================================="
echo "Quản lý Domain"
echo "========================================================================="
echo "-------------------------------------------------------------------------"
echo "Hướng dẫn: https://hostvn.net"
echo "-------------------------------------------------------------------------"
echo
PS3='Nhập lựa chọn của bạn (1-3) [0=Exit]: '
options=("Danh sách Domain" "Thêm Domain"  "Xóa Domain")
select opt_domain in "${options[@]}"
do
    case $opt_domain in
        "Danh sách Domain")
            '/var/hostvn/script/menu/controller/domain/list'
            ;;
        "Thêm Domain")
            '/var/hostvn/script/menu/controller/domain/create'
            ;;
        "Xóa Domain")
            '/var/hostvn/script/menu/controller/domain/destroy'
            ;;
        *) '/var/hostvn/script/menu/hvn';;
    esac
done