#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu

CHOICE=1

echo "========================================================================="
echo "Quản lý Domain"
echo "========================================================================="
echo

while [ "${CHOICE}" != "0" ]
do
    echo "1. Danh sách Domain"
    echo "2. Thêm Domain"
    echo "3. Xóa Domain"
    echo " ----------------------------------------------- "
    read -p " Nhập vào lựa chọn của bạn [0 = Thoát] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) domain_list ;;
        2) domain_create ;;
        3) domain_destroy ;;
        0) menu_primary ;;
        *) clear; echo -e "Lựa chọn của bạn không chính xác. Vui lòng chọn lại.";;
    esac
done