#!/bin/bash

CHOICE=1

echo "==================="
echo "   Quan ly Domain  "
echo "==================="
echo ""

while [ "${CHOICE}" != "0" ]
do
    echo "1. Danh sach Domain"
    echo "2. Them Domain"
    echo "3. Xoa Domain"
    echo " ------------------"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) domain_list ;;
        2) domain_create ;;
        3) domain_destroy ;;
        0) menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done