#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/hostvn.conf
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/variable_common

CHOICE=1

printf "${GREEN}==================================================${NC}\n"
printf "${GREEN}       %s Scripts - Cong cu quan ly VPS    ${NC}\n" "${AUTHOR}"
printf "${GREEN}                  %s                              ${NC}\n" "${AUTHOR_WEB}"
printf "${GREEN}==================================================${NC}\n"
printf "${GREEN}IP VPS: %s${NC}\n" "${IPADDRESS}"
printf "${GREEN}phpMyAdmin: %s${NC}\n" "http://${IPADDRESS}:${admin_port}/phpmyadmin"
printf "${GREEN}CSF GUI: %s${NC}\n" "https://${IPADDRESS}:${csf_port} "
printf "${GREEN}Phim tat: Ctrl + C hoac nhap 0 đe thoat            ${NC}\n"
printf "${GREEN}---------------------------------------------------${NC}\n"

while [ "${CHOICE}" != "0" ]
do
    printf "${GREEN}---------------------------------------------------${NC}\n"
    printf "${GREEN}1. Quan ly ten mien${NC}\n"
    printf "${GREEN}2. Quan ly SSL${NC}\n"
    printf "${GREEN}3. Quan ly Cache${NC}\n"
    printf "${GREEN}4. Quan ly LEMP (Nginx - MariaDB - PHP - FTP - Log)${NC}\n"
    printf "${GREEN}5. Quan ly CSF Firewall${NC}\n"
    printf "${GREEN}6. Phan quyen Chown/Chmod${NC}\n"
    printf "${GREEN}7. Quan ly WordPress${NC}\n"
    printf "${GREEN}8. Sao luu du lieu${NC}\n"
    printf "${GREEN}9. Admin Tool${NC}\n"
    printf "${GREEN}10. Quan ly VPS${NC}\n"
    printf "${GREEN}11. Xem thong tin tai khoan${NC}\n"
    printf "${GREEN}12. Quan ly Cronjob${NC}\n"
    printf "${GREEN}--------------------------------------------------${NC}\n"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; menu_domain;;
        2) clear; menu_ssl;;
        3) clear; menu_cache;;
        4) clear; menu_lemp;;
        5) clear; menu_csf;;
        6) clear; menu_permission;;
        7) clear; menu_wp;;
        8) clear; menu_backup ;;
        9) clear; menu_admin ;;
        10) clear; menu_vps;;
        11) clear; menu_account ;;
        12) clear; menu_cronjob ;;
        0) clear; echo -e "${GREEN}Bye Bye... Cam on ban da su dung HOSTVN.NET Script${NC}\n";;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done