#!/bin/bash
clear
# shellcheck disable=SC1091
source /var/hostvn/hostvn.conf
# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu

ip=$(ip route get 1 | awk '{print $NF;exit}')
CHOICE=1

echo "========================================================================="
echo "                  HOSTVN Scripts - Công cụ quản lý VPS"
echo "                              HOSTVN.NET"
echo "========================================================================="
echo "IP VPS: ${ip}"
echo "phpMyAdmin: http://${ip}:${admin_port}/phpmyadmin"
echo "Phím tắt: Ctrl + C hoặc nhập 0 để thoát"
echo "-------------------------------------------------------------------------"

while [ "${CHOICE}" != "0" ]
do
    echo "1. Quản lý Domain"
    echo "2. Quản lý Let's Encrypt"
    echo "3. Quản lý SSH"
    echo "4. Quản lý Cache"
    echo "5. Quản lý Nginx"
    echo "6. Quản lý CSF Firewall"
    echo "7. Phân quyền Chown/Chmod"
    echo "8. Thông tin VPS"
    echo " ----------------------------------------------- "
    read -p " Nhập vào lựa chọn của bạn [0 = Thoát] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; menu_domain;;
        2) clear; menu_letencrypt;;
        3) clear; menu_ssh;;
        4) clear; menu_cache;;
        5) clear; menu_nginx;;
        6) clear; menu_csf;;
        7) clear; menu_permission;;
        8) clear; menu_info;;
        0) clear; echo -e "Tạm biệt";;
        *) clear; echo -e "Lựa chọn của bạn không chính xác. Vui lòng chọn lại.";;
    esac
done