#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu

CHOICE=1

echo "=========================="
echo "Kiểm tra thông tin máy chủ"
echo "=========================="
echo

while [ "${CHOICE}" != "0" ]
do
    echo "1. Trạng thái Webserver"
    echo "2. Thông tin VPS"
    echo "3. Thông tin khác"
    echo " ----------------------------------------------- "
    read -p " Nhập vào lựa chọn của bạn [0 = Thoát] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) info_webserver ;;
        2) info_vps ;;
		3) info_other ;;
        0) menu_primary ;;
        *) echo -e "Lựa chọn của bạn không chính xác. Vui lòng chọn lại.";;
    esac
done