#!/bin/bash

CHOICE=1

echo "=========================="
echo "Kiem tra thong tin may chu"
echo "=========================="
echo

while [ "${CHOICE}" != "0" ]
do
    echo "1. Trang thai Webserver"
    echo "2. Thong tin VPS"
    echo "3. Thong tin khac"
    echo "4. Cap nhat VPS"
    echo " ----------------------"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; info_webserver ;;
        2) clear; info_vps ;;
		3) clear; info_other ;;
        3) 
            echo "Chuan bi cap nhat VPS..."
            sleep 2
            yum -y update
            clear
            menu_info 
            ;;
        0) clear; menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done