#!/bin/bash

CHOICE=1

echo "=========================="
echo "Kiem tra thong tin may chu"
echo "=========================="
echo

while [ "${CHOICE}" != "0" ]
do
    echo "1. Trang thai Webserver"
    echo "2. Thong tin VPS"
    echo "3. Thong tin khac"
    echo " ----------------------"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) info_webserver ;;
        2) info_vps ;;
		3) info_other ;;
        0) menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done