#!/bin/bash

CHOICE=1

echo "====================="
echo "Quan ly Let's Encrypt"
echo "====================="
echo

while [ "${CHOICE}" != "0" ]
do
    echo "1. Them Let's Encrypt"
    echo "2. Kiem tra thoi han"
    echo "3. Go bo Let's Encrypt"
    echo " ---------------------"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; le_create ;;
        2) clear; le_check_expired ;;
        3) clear; le_remove ;;
        0) clear; menu_ssl ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done