#!/bin/bash

CHOICE=1

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu

echo "========================================================================="
echo "Quản lý Nginx"
echo "========================================================================="
printf "%s\n" "$(nginx -v)"
echo "-------------------------------------------------------------------------"
echo "Trạng thái: $(systemctl status nginx.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "-------------------------------------------------------------------------"
echo

while [ "${CHOICE}" != "0" ]
do
    echo "1. Khởi động lại nginx"
    echo "2. Kiểm tra cấu hình Nginx"
    echo "3. Cập nhật Nginx"
    echo " ----------------------------------------------- "
    read -p " Nhập vào lựa chọn của bạn [0 = Thoát] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1)
            clear
            echo "Đang khởi động lại..."
            sleep 1
            systemctl restart nginx
            sleep 2
            echo
            menu_nginx
            ;;
        2)
            clear
            sleep 1
            nginx -t
            sleep 2
            echo
            menu_nginx
            ;;
        3)
            yum -y update nginx
            echo
            menu_nginx
            ;;
        0) menu_primary ;;
        *) echo -e "Lựa chọn của bạn không chính xác. Vui lòng chọn lại.";;
    esac
done