#!/bin/bash

CHOICE=1

echo "============================="
echo "        Quan ly Nginx        "
echo "============================="
printf "%s\n" "$(nginx -v)"
echo "-----------------------------"
echo "Trạng thái: $(systemctl status nginx.service | grep 'Active' | cut -f2 -d':' | xargs | cut -f1 -d' ' | xargs)"
echo "-----------------------------"
echo

while [ "${CHOICE}" != "0" ]
do
    echo "1. Khoi đong lai nginx"
    echo "2. Kiem tra cau hinh Nginx"
    echo "3. Cap nhat Nginx"
    echo " -------------------------"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1)
            clear
            echo "Đang khoi đong lai..."
            sleep 1
            systemctl restart nginx
            sleep 2
            echo
            menu_nginx
            ;;
        2)
            clear
            sleep 1
            nginx -t
            sleep 2
            echo
            menu_nginx
            ;;
        3)
            yum -y update nginx
            echo
            menu_nginx
            ;;
        0) menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done