#!/bin/bash

CHOICE=1

echo "======================"
echo "Phan quyen Chown/Chmod"
echo "======================"
echo

while [ "${CHOICE}" != "0" ]
do
    echo "1. Phan quyen website        "
    echo "2. Phan quyen toan bo website"
    echo " ----------------------------"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) permission_one ;;
        2) permission_all ;;
        0) menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done