#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu

CHOICE=1

echo "======================"
echo "Phân quyền Chown/Chmod"
echo "======================"
echo

while [ "${CHOICE}" != "0" ]
do
    echo "1. Đổi port SSH"
    echo "2. Đổi Password SSH"
    echo " ----------------------------------------------- "
    read -p " Nhập vào lựa chọn của bạn [0 = Thoát] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) ssh_change_port ;;
        2)
            passwd
            menu_ssh
            ;;
        0) menu_primary ;;
        *) echo -e "Lựa chọn của bạn không chính xác. Vui lòng chọn lại.";;
    esac
done