#!/bin/bash

CHOICE=1

echo "======================"
echo "Phan quyen Chown/Chmod"
echo "======================"
echo

while [ "${CHOICE}" != "0" ]
do
    echo "1. Doi port SSH"
    echo "2. Doi Password SSH"
    echo " ------------------"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) ssh_change_port ;;
        2)
            passwd
            menu_ssh
            ;;
        0) menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done