#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu

CHOICE=1

echo "==================="
echo "Quản lý SSL trả phí"
echo "==================="
echo

while [ "${CHOICE}" != "0" ]
do
    echo "1. Cài đặt SSL"
    echo "2. Gỡ bỏ SSL"
    echo " ----------------------------------------------- "
    read -p " Nhập vào lựa chọn của bạn [0 = Thoát] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) ssl_create ;;
        2) ssl_remove ;;
        0) menu_primary ;;
        *) clear; echo -e "Lựa chọn của bạn không chính xác. Vui lòng chọn lại.";;
    esac
done