#!/bin/bash

CHOICE=1

echo "==================="
echo "Quan ly SSL tra phi"
echo "==================="
echo

while [ "${CHOICE}" != "0" ]
do
    echo "1. Cai đat SSL"
    echo "2. Go bo SSL"
    echo " -------------"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; ssl_create ;;
        2) clear; ssl_remove ;;
        0) clear; menu_ssl ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done