#!/bin/bash

CHOICE=1

echo "==================="
echo "     Quan ly SSL   "
echo "==================="
echo ""

while [ "${CHOICE}" != "0" ]
do
    echo "1. SSL Let's Encrypt"
    echo "2. SSL tra phi"
    echo " ------------------"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; menu_letencrypt;;
        2) clear; menu_sslpaid;;
        0) clear; menu_ssl ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done