#!/bin/bash

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/menu

CHOICE=1

# check_is_wordpress(){
#     if [[ ! -d "/home/${username}/${domain}/public_html/wp-content" ]]; then
#         echo "Website này không sử dụng WordPress"
#         sleep 1
#         menu_wp
#     fi
# }

echo "================="
echo "Quản lý WordPress"
echo "================="
echo

while [ "${CHOICE}" != "0" ]
do
    echo "1. Kiểm tra phiên bản WordPress"
    echo "2. Cập nhật WordPress"
    echo "3. Cập nhật plugins (Trừ plugins trả phí)"
    echo "4. Tối ưu database"
    echo "5. Repair database"
    echo "6. Sao lưu dữ liệu"
    echo "7. Khôi phục dữ liệu"
    echo " ----------------------------------------------- "
    read -r -p " Nhập vào lựa chọn của bạn [0 = Thoát] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) wp_version ;;
        2) update_wp ;;
		3) wp_update_plugins ;;
		4) wp_optimize_db ;;
		5) wp_repair_db ;;
		6) wp_backup ;;
		7) echo "Đang nghĩ..."; sleep 2; menu_wp ;;
        0) menu_primary ;;
        *) clear; echo -e "Lựa chọn của bạn không chính xác. Vui lòng chọn lại.";;
    esac
done
