#!/bin/bash

CHOICE=1

echo "========================================="
echo "            Quan ly WordPress            "
echo "========================================="
echo

while [ "${CHOICE}" != "0" ]
do
    echo "1. Kiem tra phien ban WordPress"
    echo "2. Cap nhat phien ban WordPress"
    echo "3. Cap nhat plugins (Tru plugins tra phi)"
    echo "4. Toi ưu database"
    echo "5. Repair database"
    echo "6. Sao lưu du lieu"
    echo "7. Khoi phuc du lieu"
    echo "8. Thay doi ten mien"
    echo " ----------------------------------------"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; wp_version ;;
        2) clear; wp_update ;;
		3) clear; wp_update_plugins ;;
		4) clear; wp_optimize_db ;;
		5) clear; wp_repair_db ;;
		6) clear; wp_backup ;;
		7) echo "Dang nghi..."; sleep 2; menu_wp ;;
        8) clear; wp_change_domain ;;
        0) clear; menu_primary ;;
        *) clear; printf "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}\n";;
    esac
done
