#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on CentOS 7, 8        #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please don't remove copyright. Thank!                 #
#   Please don't copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/helpers/function

set_var(){
    # shellcheck disable=SC2154
    username=${domain//[-._]/}
}

view_log(){
	  clear
    printf "${RED}Hien thi 10 dong log moi nhat...\n"
    echo ""
    tail /home/"${username}"/"${domain}"/logs/error.log
    printf "${RED}Vi tri file log: /home/${username}/${domain}/logs/error.log${NC}\n"
}

_run(){
    select_domain

    if ! if_domain_exists "${domain}"; then
        ALERT=$(printf "${RED}Domain khong ton tai tren VPS.${NC}\n")
    fi

    if [[ -z "${ALERT}" ]]; then
        set_var
        view_log
    else
      printf "${ALERT}\n"
    fi
}

_run
menu_log